// File: msg_xx_entryserver.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 本文档定义入口服务通用协议
// 与各个第三方登陆平台相关的参数，不从客户端传递，配置在入口服即可。
// AuthKey算法。
// 首字母为标志位，表示使用哪种加密算法。目前传'A'
//
// 算法AuthKeyA()密码加密传输算法
// 1. 把用户密码做32位MD5计算，得到32位字符串1，并转换为大写得到字符串2。
// 2. 在'0'~'9'和'A'~'F'中随机生成两个字符，替换字符串2第0和第31两个字符，得到字符串3。
// 3. 对字符串3再做一次32位MD5计算得到字符串4，并转换为大写得到字符串5。
// 4. 使用刚得到的两个随机值分别替换字符串5的第0和第31两个字符，得到字符串6。
// 5. 'A'与字符串6连接即为验证码(auth_key)。
//
// auth_key = AuthKeyA(device_id)
//


#ifndef _MESSAGE_MSG_XX_ENTRYSERVER_H_
#define _MESSAGE_MSG_XX_ENTRYSERVER_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"
#include "msg_xx_global.h"

namespace message {

////////////////////////////////////////////////////////////////////////////////
// 游戏分区信息
// class GameGroupInfo
////////////////////////////////////////////////////////////////////////////////
class GameGroupInfo : public Aone2MessageBody
{
public:
	// 服务器状态
	class Status
	{
	public:
		enum _tagStatus
		{
			UNKNOWN = 0,  // 未知
			CLOSE = 1,  // 维护
			NORMAL = 2,  // 普通
			BUSY = 3,  // 繁忙
			FULL = 4,  // 爆满
		} m_value;

		Status() : m_value((_tagStatus)0) {}
		Status(int i) : m_value((_tagStatus)i) {}
		Status& operator=(int i) { m_value = (_tagStatus)i; return *this; }
		operator int() { return m_value; }
		operator int() const { return m_value; }
	};

public:
	GameGroupInfo();

	virtual ~GameGroupInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_group_id;  // 分区ID
	string  m_group_name;  // 分区名
	string  m_server_ip;  // 对外服务IP地址(维护和爆满状态时置空)
	uint16  m_server_port;  // 对外服务端口(维护和爆满状态时置0)
	Status  m_status;  // 检测状态
	bool  m_is_recommend;  // 是否为推荐区
	bool  m_is_initialed;  // 是否为新区
};

////////////////////////////////////////////////////////////////////////////////
// 检测客户端版本请求
// class CheckVerReqBody = 1500
////////////////////////////////////////////////////////////////////////////////
class CheckVerReqBody : public Aone2MessageBody
{
public:
	CheckVerReqBody();

	virtual ~CheckVerReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
};

////////////////////////////////////////////////////////////////////////////////
// 检测客户端版本回复
// class CheckVerRespBody = 1501
////////////////////////////////////////////////////////////////////////////////
class CheckVerRespBody : public Aone2MessageBody
{
public:
	// 版本状态
	class Status
	{
	public:
		enum _tagStatus
		{
			UNKNOWN = 0,  // 未知
			NORAML = 1,  // 正常，可登陆
			LIMITED = 2,  // 版本过低，功能受限
			OVERDUE = 3,  // 版本过低，不能进行游戏
		} m_value;

		Status() : m_value((_tagStatus)0) {}
		Status(int i) : m_value((_tagStatus)i) {}
		Status& operator=(int i) { m_value = (_tagStatus)i; return *this; }
		operator int() { return m_value; }
		operator int() const { return m_value; }
	};

public:
	CheckVerRespBody();

	virtual ~CheckVerRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint8  m_major_version;  // 主版本
	uint8  m_minor_version;  // 子版本
	uint8  m_revision_version;  // 修正版本
	Status  m_status;  // 检测状态
	string  m_notice;  // 公告或版本描述
	string  m_download_url;  // 最新版本下载URL地址
	string  m_update_url;  // 最新版本更新URL地址
	string  m_big_patcher_url;  // 微端资源下载URL地址
};

////////////////////////////////////////////////////////////////////////////////
// 获取游戏分区列表请求
// 根据版本和渠道，拉取的是所有分区中的一部分
// class GetGameGroupsReqBody = 1502
////////////////////////////////////////////////////////////////////////////////
class GetGameGroupsReqBody : public Aone2MessageBody
{
public:
	GetGameGroupsReqBody();

	virtual ~GetGameGroupsReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
};

////////////////////////////////////////////////////////////////////////////////
// 获取游戏服务列表回复
// class GetGameGroupsRespBody = 1503
////////////////////////////////////////////////////////////////////////////////
class GetGameGroupsRespBody : public Aone2MessageBody
{
public:
	GetGameGroupsRespBody();

	virtual ~GetGameGroupsRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<GameGroupInfo>  m_groups;  // 分区列表
};

////////////////////////////////////////////////////////////////////////////////
// 创建角色请求
// class CreateRoleReqBody = 1504
////////////////////////////////////////////////////////////////////////////////
class CreateRoleReqBody : public Aone2MessageBody
{
public:
	CreateRoleReqBody();

	virtual ~CreateRoleReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_user_account;  // 用户账号
	uint32  m_user_token;  // 用户身份验证码
	uint32  m_group_id;  // 指定分区(自动选择时置0)
	uint32  m_role_type;  // 角色类型
	string  m_role_name;  // 角色名
	vector<KVPair>  m_role_features;  // 角色属性列表
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
	string  m_encrypt_number;  // 加密后的身份证号
};

////////////////////////////////////////////////////////////////////////////////
// 创建角色回复
// class CreateRoleRespBody = 1505
////////////////////////////////////////////////////////////////////////////////
class CreateRoleRespBody : public Aone2MessageBody
{
public:
	CreateRoleRespBody();

	virtual ~CreateRoleRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	RoleShortInfo  m_role;  // 角色创建信息
};

////////////////////////////////////////////////////////////////////////////////
// 用户登陆请求
// class UserLoginReqBody = 1506
////////////////////////////////////////////////////////////////////////////////
class UserLoginReqBody : public Aone2MessageBody
{
public:
	UserLoginReqBody();

	virtual ~UserLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_token;  // 登陆验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
};

////////////////////////////////////////////////////////////////////////////////
// 用户登陆回复
// class UserLoginRespBody = 1507
////////////////////////////////////////////////////////////////////////////////
class UserLoginRespBody : public Aone2MessageBody
{
public:
	UserLoginRespBody();

	virtual ~UserLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_token;  // (本平台)用户身份验证码
	vector<RoleShortInfo>  m_roles;  // 角色列表信息
	vector<GameGroupInfo>  m_groups;  // 分区列表
};

////////////////////////////////////////////////////////////////////////////////
// 获取指定角色信息请求
// class GetRoleInfoReqBody = 1508
////////////////////////////////////////////////////////////////////////////////
class GetRoleInfoReqBody : public Aone2MessageBody
{
public:
	GetRoleInfoReqBody();

	virtual ~GetRoleInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_role_id;  // 角色ID
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
};

////////////////////////////////////////////////////////////////////////////////
// 获取指定角色信息回复
// class GetRoleInfoRespBody = 1509
////////////////////////////////////////////////////////////////////////////////
class GetRoleInfoRespBody : public Aone2MessageBody
{
public:
	GetRoleInfoRespBody();

	virtual ~GetRoleInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	RoleShortInfo  m_role;  // 角色信息
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////
typedef Aone2Request <CheckVerReqBody, 1500> CheckVerRequest;
typedef Aone2Response<CheckVerRespBody, 1501> CheckVerResponse;
typedef Aone2Request <GetGameGroupsReqBody, 1502> GetGameGroupsRequest;
typedef Aone2Response<GetGameGroupsRespBody, 1503> GetGameGroupsResponse;
typedef Aone2Request <CreateRoleReqBody, 1504> CreateRoleRequest;
typedef Aone2Response<CreateRoleRespBody, 1505> CreateRoleResponse;
typedef Aone2Request <UserLoginReqBody, 1506> UserLoginRequest;
typedef Aone2Response<UserLoginRespBody, 1507> UserLoginResponse;
typedef Aone2Request <GetRoleInfoReqBody, 1508> GetRoleInfoRequest;
typedef Aone2Response<GetRoleInfoRespBody, 1509> GetRoleInfoResponse;


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_ENTRYSERVER_H_
