// File: msg_xx_apiserver_ex.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 本文档定义API服务通用协议
// 7100 -- 7500:API服务(I)


#ifndef _MESSAGE_MSG_XX_APISERVER_EX_H_
#define _MESSAGE_MSG_XX_APISERVER_EX_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"
#include "msg_xx_global.h"

namespace message {

////////////////////////////////////////////////////////////////////////////////
// 客户端报错日志请求
// 接口1:http post+json,url路径:/api/record_client_core.do
// 接口2:aone2协议,协议号:7100
// user_id和device_id不能同时为空
// role_name在未登录游戏时可以记录一些其他信息 如:所在ui等,当然,需要做一个特殊标识,以便和名字有所区别
// 注意:客户端自行处理频率问题 如:记录最近十条日志,如有相同,不再发送
// class RecordClientCoreReqBody = 7100
////////////////////////////////////////////////////////////////////////////////
class RecordClientCoreReqBody : public Aone2MessageBody
{
public:
	RecordClientCoreReqBody();

	virtual ~RecordClientCoreReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;
	string  m_role_id;
	string  m_group_id;
	string  m_role_name;
	string  m_errorLine;  // 报错行号
	string  m_errorStack;  // 堆栈信息
	DeviceInfo  m_device_info;  // 机型信息
	AppVersionInfo  m_version_info;  // 版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 客户端报错日志回复
// class RecordClientCoreRespBody = 7101
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody RecordClientCoreRespBody;


////////////////////////////////////////////////////////////////////////////////
// 拉取节假日请求
// 接口1:http post+json,url路径:/api/holiday_info.do
// 接口2:aone2协议,协议号:7102
// class HolidayInfoReqBody = 7102
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody HolidayInfoReqBody;


////////////////////////////////////////////////////////////////////////////////
// 拉取节假日回复
// class HolidayInfoRespBody = 7103
////////////////////////////////////////////////////////////////////////////////
class HolidayInfoRespBody : public Aone2MessageBody
{
public:
	HolidayInfoRespBody();

	virtual ~HolidayInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<string>  m_days;  // 节假日信息(2021-05-31)
};

////////////////////////////////////////////////////////////////////////////////
// uid互换请求
// 接口1:http post+json,url路径:/api/swap_uid.do
// 接口2:aone2协议,协议号:7104
// class SwapUidReqBody = 7104
////////////////////////////////////////////////////////////////////////////////
class SwapUidReqBody : public Aone2MessageBody
{
public:
	SwapUidReqBody();

	virtual ~SwapUidReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id1;  // 用户ID
	uint32  m_user_id2;  // 被互换用户ID
	string  m_token;  // 用户身份验证码
};

////////////////////////////////////////////////////////////////////////////////
// uid交换请求
// class SwapUidRespBody = 7105
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody SwapUidRespBody;


////////////////////////////////////////////////////////////////////////////////
// 查询账号信息请求
// 接口1: http post + json，url路径：/api/query_aone_account.do?appid=xxx&sign=xxxx
// class QueryAoneAccountReqBody = 7106
////////////////////////////////////////////////////////////////////////////////
class QueryAoneAccountReqBody : public Aone2MessageBody
{
public:
	QueryAoneAccountReqBody();

	virtual ~QueryAoneAccountReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;  // 账号(6~50个字符，可使用字母、数字、下划线，不能以下划线开头，区分大小写)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVersion方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// 查询账号信息回复
// class QueryAoneAccountRespBody = 7107
////////////////////////////////////////////////////////////////////////////////
class QueryAoneAccountRespBody : public Aone2MessageBody
{
public:
	QueryAoneAccountRespBody();

	virtual ~QueryAoneAccountRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_account;  // Aone账号
	string  m_device_id;  // 绑定设备ID
	string  m_phone;  // 绑定电话
	string  m_mail;  // 绑定邮箱
	string  m_weixin;  // 绑定微信
	uint32  m_flag;  // 标识
	string  m_create_time;  // 账号创建时间(yyyy-mm-dd hh:mm:ss)
};

////////////////////////////////////////////////////////////////////////////////
// 检测验证码是否正确请求
// 接口1: http post + json，url路径：/api/check_phone_token.do?appid=xxx&sign=xxxx
// class CheckPhoneTokenReqBody = 7108
////////////////////////////////////////////////////////////////////////////////
class CheckPhoneTokenReqBody : public Aone2MessageBody
{
public:
	CheckPhoneTokenReqBody();

	virtual ~CheckPhoneTokenReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_phone;  // 手机号
	string  m_phone_token;  // 手机号验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVersion方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// 检测验证码是否正确回复
// class CheckPhoneTokenRespBody = 7109
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody CheckPhoneTokenRespBody;


////////////////////////////////////////////////////////////////////////////////
// 根据账号/手机号查询uid请求
// 接口1: http post + json，url路径：/api/query_aone_uid.do
// class QueryAoneUidReqBody = 7110
////////////////////////////////////////////////////////////////////////////////
class QueryAoneUidReqBody : public Aone2MessageBody
{
public:
	QueryAoneUidReqBody();

	virtual ~QueryAoneUidReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;  // 账号(6~50个字符，可使用字母、数字、下划线，不能以下划线开头，区分大小写)
	string  m_phone;  // 手机号
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVersion方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// 根据账号/手机号查询uid回复
// class QueryAoneUidRespBody = 7111
////////////////////////////////////////////////////////////////////////////////
class QueryAoneUidRespBody : public Aone2MessageBody
{
public:
	QueryAoneUidRespBody();

	virtual ~QueryAoneUidRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 通过账号查询对应uid请求
// 接口1: http post + json，url路径：/api/query_uid_by_account.do
// class QueryUidByAccountReqBody = 7112
////////////////////////////////////////////////////////////////////////////////
class QueryUidByAccountReqBody : public Aone2MessageBody
{
public:
	QueryUidByAccountReqBody();

	virtual ~QueryUidByAccountReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_type;
	string  m_account;
};

////////////////////////////////////////////////////////////////////////////////
// 通过账号查询对应uid回复
// class QueryUidByAccountRespBody = 7113
////////////////////////////////////////////////////////////////////////////////
class QueryUidByAccountRespBody : public Aone2MessageBody
{
public:
	QueryUidByAccountRespBody();

	virtual ~QueryUidByAccountRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_uid;
};

////////////////////////////////////////////////////////////////////////////////
// 账号注销请求
// 接口1:http post+json,url路径:/api/account_write_off.do?appid=xxx&sign=xxxx
// 接口2:aone2协议,协议号:7114
// class AccountWriteOffReqBody = 7114
////////////////////////////////////////////////////////////////////////////////
class AccountWriteOffReqBody : public Aone2MessageBody
{
public:
	AccountWriteOffReqBody();

	virtual ~AccountWriteOffReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;  // 用户账号
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 账号注销请求
// class AccountWriteOffRespBody = 7115
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AccountWriteOffRespBody;


////////////////////////////////////////////////////////////////////////////////
// 账号延期注销请求
// class AccountDelayWriteOffReqBody = 7116
////////////////////////////////////////////////////////////////////////////////
class AccountDelayWriteOffReqBody : public Aone2MessageBody
{
public:
	AccountDelayWriteOffReqBody();

	virtual ~AccountDelayWriteOffReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_token;  // 登录时的token
	uint32  m_type;  // 0: 拉取注销时间; 1: 取消注销; 2: 30天后注销; 3: 立刻注销
	string  m_ip;  // IP
	string  m_device_id;  // 绑定设备ID
	string  m_channel;  // 渠道
};

////////////////////////////////////////////////////////////////////////////////
// 账号延期注销请求
// class AccountDelayWriteOffRespBody = 7117
////////////////////////////////////////////////////////////////////////////////
class AccountDelayWriteOffRespBody : public Aone2MessageBody
{
public:
	AccountDelayWriteOffRespBody();

	virtual ~AccountDelayWriteOffRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_write_off_time;  // 注销时间
};

////////////////////////////////////////////////////////////////////////////////
// 米大师支付请求
// class MidasPayReqBody = 7118
////////////////////////////////////////////////////////////////////////////////
class MidasPayReqBody : public Aone2MessageBody
{
public:
	MidasPayReqBody();

	virtual ~MidasPayReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_product_id;  // 商品唯一ID(类似于com.aonesoft.zqgame.item1，不特指商品名，不确定的可置空)
	uint32  m_product_quantity;  // 商品数量
	string  m_cp_role_id;  // cp 角色ID
	string  m_cp_group_id;  // cp 分区ID
	string  m_cp_ext;  // 做发行时留给开发商扩展的字段，回调时原样返回(限长255字节)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	string  m_openid;  // 与APP通信的用户key。根据APPID以及QQ号码生成，即不同的appid下，同一个QQ号生成的OpenID是不一样的。
	string  m_openkey;  // 登录使用的session key (登陆时应用宝返回给客户端)
	string  m_pf;  // 应用的来源平台 (平台跳转应用时直接传给应用)
	string  m_pfkey;  // 平台的信息加密串，根据openid，openkey，pf，appid等生成。
	string  m_payitem;  // 物品信息  ID*price*num  ID表示物品ID，price表示单价（以Q点为单位，必须为整数，单价最少不能少于2Q点)
	string  m_appmode;  // 1表示用户不可以修改物品数量，2表示用户可以选择购买物品的数量。
	string  m_goodsmeta;  // 物品信息，格式必须是“name*des” (长度必须<=256字符，必须使用utf8编码)
	string  m_goodsurl;  // 物品的图片url, 长度<=512字符,注意图片规格最大为：116*116 px。
};

////////////////////////////////////////////////////////////////////////////////
// 米大师支付回复
// class MidasPayRespBody = 7119
////////////////////////////////////////////////////////////////////////////////
class MidasPayRespBody : public Aone2MessageBody
{
public:
	MidasPayRespBody();

	virtual ~MidasPayRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_pay_no;  // 订单号
	uint32  m_discount;  // 折扣
	string  m_token;  // (1) 交易的token号 (2) 订单的token号 (2) 订单的token号
	string  m_url_params;  // 真正购买物品的url参数。
};

////////////////////////////////////////////////////////////////////////////////
// qq大厅支付请求
// class QQGameHallPayReqBody = 7120
////////////////////////////////////////////////////////////////////////////////
class QQGameHallPayReqBody : public Aone2MessageBody
{
public:
	QQGameHallPayReqBody();

	virtual ~QQGameHallPayReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_product_id;  // 商品唯一ID(类似于com.aonesoft.zqgame.item1，不特指商品名，不确定的可置空)
	uint32  m_product_quantity;  // 商品数量
	string  m_cp_role_id;  // cp 角色ID
	string  m_cp_group_id;  // cp 分区ID
	string  m_cp_ext;  // 做发行时留给开发商扩展的字段，回调时原样返回(限长255字节)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	string  m_openid;  // 与APP通信的用户key。根据APPID以及QQ号码生成，即不同的appid下，同一个QQ号生成的OpenID是不一样的。
	string  m_openkey;  // 登录使用的session key (登陆时应用宝返回给客户端)
	string  m_pf;  // 应用的来源平台 (平台跳转应用时直接传给应用)
	string  m_pfkey;  // 平台的信息加密串，根据openid，openkey，pf，appid等生成。
	string  m_amt;  // 表示购买的所有物品的总价格，即物品的单价*建议数量（以Q点为单位，1Q币=10Q点）
	string  m_payitem;  // 物品信息  ID*price*num  ID表示物品ID，price表示单价（以Q点为单位，必须为整数，单价最少不能少于2Q点)
	string  m_appmode;  // 1表示用户不可以修改物品数量，2表示用户可以选择购买物品的数量。
	string  m_goodsmeta;  // 物品信息，格式必须是“name*des” (长度必须<=256字符，必须使用utf8编码)
	string  m_goodsurl;  // 物品的图片url, 长度<=512字符,注意图片规格最大为：116*116 px。
};

////////////////////////////////////////////////////////////////////////////////
// qq大厅支付回复
// class QQGameHallPayRespBody = 7121
////////////////////////////////////////////////////////////////////////////////
class QQGameHallPayRespBody : public Aone2MessageBody
{
public:
	QQGameHallPayRespBody();

	virtual ~QQGameHallPayRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_pay_no;  // 订单号
	uint32  m_discount;  // 折扣
	string  m_token;  // (1) 交易的token号 (2) 订单的token号 (2) 订单的token号
	string  m_url_params;  // 真正购买物品的url参数。
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////
typedef Aone2Request <RecordClientCoreReqBody, 7100> RecordClientCoreRequest;
typedef Aone2Response<RecordClientCoreRespBody, 7101> RecordClientCoreResponse;
typedef Aone2Request <HolidayInfoReqBody, 7102> HolidayInfoRequest;
typedef Aone2Response<HolidayInfoRespBody, 7103> HolidayInfoResponse;
typedef Aone2Request <SwapUidReqBody, 7104> SwapUidRequest;
typedef Aone2Response<SwapUidRespBody, 7105> SwapUidResponse;
typedef Aone2Request <QueryAoneAccountReqBody, 7106> QueryAoneAccountRequest;
typedef Aone2Response<QueryAoneAccountRespBody, 7107> QueryAoneAccountResponse;
typedef Aone2Request <CheckPhoneTokenReqBody, 7108> CheckPhoneTokenRequest;
typedef Aone2Response<CheckPhoneTokenRespBody, 7109> CheckPhoneTokenResponse;
typedef Aone2Request <QueryAoneUidReqBody, 7110> QueryAoneUidRequest;
typedef Aone2Response<QueryAoneUidRespBody, 7111> QueryAoneUidResponse;
typedef Aone2Request <QueryUidByAccountReqBody, 7112> QueryUidByAccountRequest;
typedef Aone2Response<QueryUidByAccountRespBody, 7113> QueryUidByAccountResponse;
typedef Aone2Request <AccountWriteOffReqBody, 7114> AccountWriteOffRequest;
typedef Aone2Response<AccountWriteOffRespBody, 7115> AccountWriteOffResponse;
typedef Aone2Request <AccountDelayWriteOffReqBody, 7116> AccountDelayWriteOffRequest;
typedef Aone2Response<AccountDelayWriteOffRespBody, 7117> AccountDelayWriteOffResponse;
typedef Aone2Request <MidasPayReqBody, 7118> MidasPayRequest;
typedef Aone2Response<MidasPayRespBody, 7119> MidasPayResponse;
typedef Aone2Request <QQGameHallPayReqBody, 7120> QQGameHallPayRequest;
typedef Aone2Response<QQGameHallPayRespBody, 7121> QQGameHallPayResponse;


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_APISERVER_EX_H_
