// File: msg_xx_global.cpp
// Auth: generated by auto tool 'lazybone'
// Desc: message define


#include "msg_xx_global.h"
#include "aone2_helper.h"

namespace message {

///////////////////////////////////////////////////////////////////////////////
// class DeviceInfo
///////////////////////////////////////////////////////////////////////////////
DeviceInfo::DeviceInfo()
{
}

DeviceInfo::~DeviceInfo()
{
	// empty
}

int DeviceInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_device_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_device_id)) return -1;

	// m_locale
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_locale)) return -1;

	// m_language
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_language)) return -1;

	// m_model
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_model)) return -1;

	// m_os
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_os)) return -1;

	// m_imei
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_imei)) return -1;

	// m_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_ip)) return -1;

	// m_mac
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_mac)) return -1;

	// m_idfa
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_idfa)) return -1;

	return msglen;
}

int DeviceInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_device_id
	if (!coder.set_string(m_device_id)) return -1;

	// m_locale
	if (!coder.set_string(m_locale)) return -1;

	// m_language
	if (!coder.set_string(m_language)) return -1;

	// m_model
	if (!coder.set_string(m_model)) return -1;

	// m_os
	if (!coder.set_string(m_os)) return -1;

	// m_imei
	if (!coder.set_string(m_imei)) return -1;

	// m_ip
	if (!coder.set_string(m_ip)) return -1;

	// m_mac
	if (!coder.set_string(m_mac)) return -1;

	// m_idfa
	if (!coder.set_string(m_idfa)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 DeviceInfo::calc_length()
{
	uint32 length = 0;

	// m_device_id
	length += Aone2Coder::size_string(m_device_id);

	// m_locale
	length += Aone2Coder::size_string(m_locale);

	// m_language
	length += Aone2Coder::size_string(m_language);

	// m_model
	length += Aone2Coder::size_string(m_model);

	// m_os
	length += Aone2Coder::size_string(m_os);

	// m_imei
	length += Aone2Coder::size_string(m_imei);

	// m_ip
	length += Aone2Coder::size_string(m_ip);

	// m_mac
	length += Aone2Coder::size_string(m_mac);

	// m_idfa
	length += Aone2Coder::size_string(m_idfa);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class AppVersionInfo
///////////////////////////////////////////////////////////////////////////////
AppVersionInfo::AppVersionInfo()
{
	m_app_id = 0;
	m_major_version = 0;
	m_minor_version = 0;
	m_revision_version = 0;
}

AppVersionInfo::~AppVersionInfo()
{
	// empty
}

int AppVersionInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_app_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_app_id)) return -1;

	// m_app_lang
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_app_lang)) return -1;

	// m_channel
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_channel)) return -1;

	// m_major_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_major_version)) return -1;

	// m_minor_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_minor_version)) return -1;

	// m_revision_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_revision_version)) return -1;

	// m_ext
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_ext)) return -1;

	return msglen;
}

int AppVersionInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_app_id
	if (!coder.set_uint32(m_app_id)) return -1;

	// m_app_lang
	if (!coder.set_string(m_app_lang)) return -1;

	// m_channel
	if (!coder.set_string(m_channel)) return -1;

	// m_major_version
	if (!coder.set_uint8(m_major_version)) return -1;

	// m_minor_version
	if (!coder.set_uint8(m_minor_version)) return -1;

	// m_revision_version
	if (!coder.set_uint8(m_revision_version)) return -1;

	// m_ext
	if (!coder.set_string(m_ext)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 AppVersionInfo::calc_length()
{
	uint32 length = 0;

	// m_app_id
	length += Aone2Coder::size_uint32(m_app_id);

	// m_app_lang
	length += Aone2Coder::size_string(m_app_lang);

	// m_channel
	length += Aone2Coder::size_string(m_channel);

	// m_major_version
	length += Aone2Coder::size_uint8(m_major_version);

	// m_minor_version
	length += Aone2Coder::size_uint8(m_minor_version);

	// m_revision_version
	length += Aone2Coder::size_uint8(m_revision_version);

	// m_ext
	length += Aone2Coder::size_string(m_ext);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class KVPair
///////////////////////////////////////////////////////////////////////////////
KVPair::KVPair()
{
}

KVPair::~KVPair()
{
	// empty
}

int KVPair::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_key)) return -1;

	// m_value
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_value)) return -1;

	return msglen;
}

int KVPair::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_key
	if (!coder.set_string(m_key)) return -1;

	// m_value
	if (!coder.set_string(m_value)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 KVPair::calc_length()
{
	uint32 length = 0;

	// m_key
	length += Aone2Coder::size_string(m_key);

	// m_value
	length += Aone2Coder::size_string(m_value);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class RoleShortInfo
///////////////////////////////////////////////////////////////////////////////
RoleShortInfo::RoleShortInfo()
{
	m_user_id = 0;
	m_role_id = 0;
	m_owner_groupid = 0;
	m_last_groupid = 0;
	m_role_type = 0;
	m_role_level = 0;
	m_role_vip = 0;
}

RoleShortInfo::~RoleShortInfo()
{
	// empty
}

int RoleShortInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_role_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_id)) return -1;

	// m_owner_groupid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_owner_groupid)) return -1;

	// m_last_groupid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_last_groupid)) return -1;

	// m_last_logintime
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_last_logintime)) return -1;

	// m_role_createtime
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_createtime)) return -1;

	// m_role_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_type)) return -1;

	// m_role_level
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_level)) return -1;

	// m_role_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_name)) return -1;

	// m_role_features
	if (decoder.remain() == 0) return msglen;
	uint32 role_features_count = 0;
	if (!decoder.get_uint32(role_features_count)) return -1;
	for(uint32 i = 0; i < role_features_count; i++)
	{
		m_role_features.emplace_back(KVPair());
		KVPair& role_features_ = m_role_features.back();
		int role_features_ret = role_features_.parse_bytes(decoder.position(), decoder.remain());
		if (role_features_ret <= 0) return role_features_ret;
		if (!decoder.set_pos(decoder.position() + role_features_ret)) return -1;
	}

	// m_channel
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_channel)) return -1;

	// m_device_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_device_id)) return -1;

	// m_role_vip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_vip)) return -1;

	return msglen;
}

int RoleShortInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_role_id
	if (!coder.set_uint32(m_role_id)) return -1;

	// m_owner_groupid
	if (!coder.set_uint32(m_owner_groupid)) return -1;

	// m_last_groupid
	if (!coder.set_uint32(m_last_groupid)) return -1;

	// m_last_logintime
	if (!coder.set_string(m_last_logintime)) return -1;

	// m_role_createtime
	if (!coder.set_string(m_role_createtime)) return -1;

	// m_role_type
	if (!coder.set_uint32(m_role_type)) return -1;

	// m_role_level
	if (!coder.set_uint32(m_role_level)) return -1;

	// m_role_name
	if (!coder.set_string(m_role_name)) return -1;

	// m_role_features
	if (!coder.set_uint32(m_role_features.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_role_features.size(); i++)
	{
		int role_features_ret = m_role_features[i].to_bytes(coder.position(), coder.remain());
		if (role_features_ret <= 0) return role_features_ret;
		coder.set_pos(coder.position() + role_features_ret);
	}

	// m_channel
	if (!coder.set_string(m_channel)) return -1;

	// m_device_id
	if (!coder.set_string(m_device_id)) return -1;

	// m_role_vip
	if (!coder.set_uint32(m_role_vip)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 RoleShortInfo::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_role_id
	length += Aone2Coder::size_uint32(m_role_id);

	// m_owner_groupid
	length += Aone2Coder::size_uint32(m_owner_groupid);

	// m_last_groupid
	length += Aone2Coder::size_uint32(m_last_groupid);

	// m_last_logintime
	length += Aone2Coder::size_string(m_last_logintime);

	// m_role_createtime
	length += Aone2Coder::size_string(m_role_createtime);

	// m_role_type
	length += Aone2Coder::size_uint32(m_role_type);

	// m_role_level
	length += Aone2Coder::size_uint32(m_role_level);

	// m_role_name
	length += Aone2Coder::size_string(m_role_name);

	// m_role_features
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_role_features.size(); i++)
	{
		length += m_role_features[i].calc_length();
	}

	// m_channel
	length += Aone2Coder::size_string(m_channel);

	// m_device_id
	length += Aone2Coder::size_string(m_device_id);

	// m_role_vip
	length += Aone2Coder::size_uint32(m_role_vip);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class PayProductInfo
///////////////////////////////////////////////////////////////////////////////
PayProductInfo::PayProductInfo()
{
	m_amount = 0.0f;
	m_amount_usd = 0.0f;
	m_coin = 0;
}

PayProductInfo::~PayProductInfo()
{
	// empty
}

int PayProductInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_id)) return -1;

	// m_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_name)) return -1;

	// m_describe
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_describe)) return -1;

	// m_currency
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_currency)) return -1;

	// m_amount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_double(m_amount)) return -1;

	// m_amount_usd
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_double(m_amount_usd)) return -1;

	// m_coin
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_coin)) return -1;

	// m_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_type)) return -1;

	// m_discount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_discount)) return -1;

	return msglen;
}

int PayProductInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_id
	if (!coder.set_string(m_id)) return -1;

	// m_name
	if (!coder.set_string(m_name)) return -1;

	// m_describe
	if (!coder.set_string(m_describe)) return -1;

	// m_currency
	if (!coder.set_string(m_currency)) return -1;

	// m_amount
	if (!coder.set_double(m_amount)) return -1;

	// m_amount_usd
	if (!coder.set_double(m_amount_usd)) return -1;

	// m_coin
	if (!coder.set_uint32(m_coin)) return -1;

	// m_type
	if (!coder.set_string(m_type)) return -1;

	// m_discount
	if (!coder.set_string(m_discount)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 PayProductInfo::calc_length()
{
	uint32 length = 0;

	// m_id
	length += Aone2Coder::size_string(m_id);

	// m_name
	length += Aone2Coder::size_string(m_name);

	// m_describe
	length += Aone2Coder::size_string(m_describe);

	// m_currency
	length += Aone2Coder::size_string(m_currency);

	// m_amount
	length += Aone2Coder::size_double(m_amount);

	// m_amount_usd
	length += Aone2Coder::size_double(m_amount_usd);

	// m_coin
	length += Aone2Coder::size_uint32(m_coin);

	// m_type
	length += Aone2Coder::size_string(m_type);

	// m_discount
	length += Aone2Coder::size_string(m_discount);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class PayProductExtInfo
///////////////////////////////////////////////////////////////////////////////
PayProductExtInfo::PayProductExtInfo()
{
}

PayProductExtInfo::~PayProductExtInfo()
{
	// empty
}

int PayProductExtInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_id)) return -1;

	// m_cp_product_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_product_id)) return -1;

	// m_history_discount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_history_discount)) return -1;

	return msglen;
}

int PayProductExtInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_id
	if (!coder.set_string(m_id)) return -1;

	// m_cp_product_id
	if (!coder.set_string(m_cp_product_id)) return -1;

	// m_history_discount
	if (!coder.set_string(m_history_discount)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 PayProductExtInfo::calc_length()
{
	uint32 length = 0;

	// m_id
	length += Aone2Coder::size_string(m_id);

	// m_cp_product_id
	length += Aone2Coder::size_string(m_cp_product_id);

	// m_history_discount
	length += Aone2Coder::size_string(m_history_discount);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Payways
///////////////////////////////////////////////////////////////////////////////
Payways::Payways()
{
}

Payways::~Payways()
{
	// empty
}

int Payways::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_pay_channel
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pay_channel)) return -1;

	// m_pay_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string_vector(m_pay_type)) return -1;

	return msglen;
}

int Payways::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_pay_channel
	if (!coder.set_string(m_pay_channel)) return -1;

	// m_pay_type
	if (!coder.set_string_vector(m_pay_type)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 Payways::calc_length()
{
	uint32 length = 0;

	// m_pay_channel
	length += Aone2Coder::size_string(m_pay_channel);

	// m_pay_type
	length += Aone2Coder::size_string_vector(m_pay_type);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ChannelVersionInfo
///////////////////////////////////////////////////////////////////////////////
ChannelVersionInfo::ChannelVersionInfo()
{
	m_major_version = 0;
	m_minor_version = 0;
	m_revision_version = 0;
	m_announce_rate = 0;
	m_is_show_announce = 0;
	m_update_option = 0;
	m_is_test = 0;
	m_is_whitelist = 0;
}

ChannelVersionInfo::~ChannelVersionInfo()
{
	// empty
}

int ChannelVersionInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_major_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_major_version)) return -1;

	// m_minor_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_minor_version)) return -1;

	// m_revision_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_revision_version)) return -1;

	// m_update_addr
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_update_addr)) return -1;

	// m_announce_addr
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_announce_addr)) return -1;

	// m_announce_begin
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_announce_begin)) return -1;

	// m_announce_end
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_announce_end)) return -1;

	// m_announce_rate
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_announce_rate)) return -1;

	// m_is_show_announce
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_show_announce)) return -1;

	// m_version_desc
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_version_desc)) return -1;

	// m_update_option
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_update_option)) return -1;

	// m_is_test
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_test)) return -1;

	// m_is_whitelist
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_whitelist)) return -1;

	return msglen;
}

int ChannelVersionInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_major_version
	if (!coder.set_uint8(m_major_version)) return -1;

	// m_minor_version
	if (!coder.set_uint8(m_minor_version)) return -1;

	// m_revision_version
	if (!coder.set_uint8(m_revision_version)) return -1;

	// m_update_addr
	if (!coder.set_string(m_update_addr)) return -1;

	// m_announce_addr
	if (!coder.set_string(m_announce_addr)) return -1;

	// m_announce_begin
	if (!coder.set_string(m_announce_begin)) return -1;

	// m_announce_end
	if (!coder.set_string(m_announce_end)) return -1;

	// m_announce_rate
	if (!coder.set_uint32(m_announce_rate)) return -1;

	// m_is_show_announce
	if (!coder.set_bool(m_is_show_announce)) return -1;

	// m_version_desc
	if (!coder.set_string(m_version_desc)) return -1;

	// m_update_option
	if (!coder.set_uint32(m_update_option)) return -1;

	// m_is_test
	if (!coder.set_bool(m_is_test)) return -1;

	// m_is_whitelist
	if (!coder.set_bool(m_is_whitelist)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 ChannelVersionInfo::calc_length()
{
	uint32 length = 0;

	// m_major_version
	length += Aone2Coder::size_uint8(m_major_version);

	// m_minor_version
	length += Aone2Coder::size_uint8(m_minor_version);

	// m_revision_version
	length += Aone2Coder::size_uint8(m_revision_version);

	// m_update_addr
	length += Aone2Coder::size_string(m_update_addr);

	// m_announce_addr
	length += Aone2Coder::size_string(m_announce_addr);

	// m_announce_begin
	length += Aone2Coder::size_string(m_announce_begin);

	// m_announce_end
	length += Aone2Coder::size_string(m_announce_end);

	// m_announce_rate
	length += Aone2Coder::size_uint32(m_announce_rate);

	// m_is_show_announce
	length += Aone2Coder::size_bool(m_is_show_announce);

	// m_version_desc
	length += Aone2Coder::size_string(m_version_desc);

	// m_update_option
	length += Aone2Coder::size_uint32(m_update_option);

	// m_is_test
	length += Aone2Coder::size_bool(m_is_test);

	// m_is_whitelist
	length += Aone2Coder::size_bool(m_is_whitelist);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ChannelInfo
///////////////////////////////////////////////////////////////////////////////
ChannelInfo::ChannelInfo()
{
}

ChannelInfo::~ChannelInfo()
{
	// empty
}

int ChannelInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_id)) return -1;

	// m_alias
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_alias)) return -1;

	// m_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_name)) return -1;

	// m_channel_params
	if (decoder.remain() == 0) return msglen;
	uint32 channel_params_count = 0;
	if (!decoder.get_uint32(channel_params_count)) return -1;
	for(uint32 i = 0; i < channel_params_count; i++)
	{
		m_channel_params.emplace_back(KVPair());
		KVPair& channel_params_ = m_channel_params.back();
		int channel_params_ret = channel_params_.parse_bytes(decoder.position(), decoder.remain());
		if (channel_params_ret <= 0) return channel_params_ret;
		if (!decoder.set_pos(decoder.position() + channel_params_ret)) return -1;
	}

	// m_channel_products
	if (decoder.remain() == 0) return msglen;
	uint32 channel_products_count = 0;
	if (!decoder.get_uint32(channel_products_count)) return -1;
	for(uint32 i = 0; i < channel_products_count; i++)
	{
		m_channel_products.emplace_back(PayProductInfo());
		PayProductInfo& channel_products_ = m_channel_products.back();
		int channel_products_ret = channel_products_.parse_bytes(decoder.position(), decoder.remain());
		if (channel_products_ret <= 0) return channel_products_ret;
		if (!decoder.set_pos(decoder.position() + channel_products_ret)) return -1;
	}

	// m_mcc_codes
	if (decoder.remain() == 0) return msglen;
	uint32 mcc_codes_count = 0;
	if (!decoder.get_uint32(mcc_codes_count)) return -1;
	for(uint32 i = 0; i < mcc_codes_count; i++)
	{
		m_mcc_codes.emplace_back(KVPair());
		KVPair& mcc_codes_ = m_mcc_codes.back();
		int mcc_codes_ret = mcc_codes_.parse_bytes(decoder.position(), decoder.remain());
		if (mcc_codes_ret <= 0) return mcc_codes_ret;
		if (!decoder.set_pos(decoder.position() + mcc_codes_ret)) return -1;
	}

	// m_bank_payways
	if (decoder.remain() == 0) return msglen;
	uint32 bank_payways_count = 0;
	if (!decoder.get_uint32(bank_payways_count)) return -1;
	for(uint32 i = 0; i < bank_payways_count; i++)
	{
		m_bank_payways.emplace_back(Payways());
		Payways& bank_payways_ = m_bank_payways.back();
		int bank_payways_ret = bank_payways_.parse_bytes(decoder.position(), decoder.remain());
		if (bank_payways_ret <= 0) return bank_payways_ret;
		if (!decoder.set_pos(decoder.position() + bank_payways_ret)) return -1;
	}

	// m_card_payways
	if (decoder.remain() == 0) return msglen;
	uint32 card_payways_count = 0;
	if (!decoder.get_uint32(card_payways_count)) return -1;
	for(uint32 i = 0; i < card_payways_count; i++)
	{
		m_card_payways.emplace_back(Payways());
		Payways& card_payways_ = m_card_payways.back();
		int card_payways_ret = card_payways_.parse_bytes(decoder.position(), decoder.remain());
		if (card_payways_ret <= 0) return card_payways_ret;
		if (!decoder.set_pos(decoder.position() + card_payways_ret)) return -1;
	}

	// m_channel_products_ext
	if (decoder.remain() == 0) return msglen;
	uint32 channel_products_ext_count = 0;
	if (!decoder.get_uint32(channel_products_ext_count)) return -1;
	for(uint32 i = 0; i < channel_products_ext_count; i++)
	{
		m_channel_products_ext.emplace_back(PayProductExtInfo());
		PayProductExtInfo& channel_products_ext_ = m_channel_products_ext.back();
		int channel_products_ext_ret = channel_products_ext_.parse_bytes(decoder.position(), decoder.remain());
		if (channel_products_ext_ret <= 0) return channel_products_ext_ret;
		if (!decoder.set_pos(decoder.position() + channel_products_ext_ret)) return -1;
	}

	// m_channel_version_info
	if (decoder.remain() == 0) return msglen;
	uint32 channel_version_info_count = 0;
	if (!decoder.get_uint32(channel_version_info_count)) return -1;
	for(uint32 i = 0; i < channel_version_info_count; i++)
	{
		m_channel_version_info.emplace_back(ChannelVersionInfo());
		ChannelVersionInfo& channel_version_info_ = m_channel_version_info.back();
		int channel_version_info_ret = channel_version_info_.parse_bytes(decoder.position(), decoder.remain());
		if (channel_version_info_ret <= 0) return channel_version_info_ret;
		if (!decoder.set_pos(decoder.position() + channel_version_info_ret)) return -1;
	}

	return msglen;
}

int ChannelInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_id
	if (!coder.set_string(m_id)) return -1;

	// m_alias
	if (!coder.set_string(m_alias)) return -1;

	// m_name
	if (!coder.set_string(m_name)) return -1;

	// m_channel_params
	if (!coder.set_uint32(m_channel_params.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_channel_params.size(); i++)
	{
		int channel_params_ret = m_channel_params[i].to_bytes(coder.position(), coder.remain());
		if (channel_params_ret <= 0) return channel_params_ret;
		coder.set_pos(coder.position() + channel_params_ret);
	}

	// m_channel_products
	if (!coder.set_uint32(m_channel_products.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_channel_products.size(); i++)
	{
		int channel_products_ret = m_channel_products[i].to_bytes(coder.position(), coder.remain());
		if (channel_products_ret <= 0) return channel_products_ret;
		coder.set_pos(coder.position() + channel_products_ret);
	}

	// m_mcc_codes
	if (!coder.set_uint32(m_mcc_codes.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_mcc_codes.size(); i++)
	{
		int mcc_codes_ret = m_mcc_codes[i].to_bytes(coder.position(), coder.remain());
		if (mcc_codes_ret <= 0) return mcc_codes_ret;
		coder.set_pos(coder.position() + mcc_codes_ret);
	}

	// m_bank_payways
	if (!coder.set_uint32(m_bank_payways.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_bank_payways.size(); i++)
	{
		int bank_payways_ret = m_bank_payways[i].to_bytes(coder.position(), coder.remain());
		if (bank_payways_ret <= 0) return bank_payways_ret;
		coder.set_pos(coder.position() + bank_payways_ret);
	}

	// m_card_payways
	if (!coder.set_uint32(m_card_payways.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_card_payways.size(); i++)
	{
		int card_payways_ret = m_card_payways[i].to_bytes(coder.position(), coder.remain());
		if (card_payways_ret <= 0) return card_payways_ret;
		coder.set_pos(coder.position() + card_payways_ret);
	}

	// m_channel_products_ext
	if (!coder.set_uint32(m_channel_products_ext.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_channel_products_ext.size(); i++)
	{
		int channel_products_ext_ret = m_channel_products_ext[i].to_bytes(coder.position(), coder.remain());
		if (channel_products_ext_ret <= 0) return channel_products_ext_ret;
		coder.set_pos(coder.position() + channel_products_ext_ret);
	}

	// m_channel_version_info
	if (!coder.set_uint32(m_channel_version_info.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_channel_version_info.size(); i++)
	{
		int channel_version_info_ret = m_channel_version_info[i].to_bytes(coder.position(), coder.remain());
		if (channel_version_info_ret <= 0) return channel_version_info_ret;
		coder.set_pos(coder.position() + channel_version_info_ret);
	}

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 ChannelInfo::calc_length()
{
	uint32 length = 0;

	// m_id
	length += Aone2Coder::size_string(m_id);

	// m_alias
	length += Aone2Coder::size_string(m_alias);

	// m_name
	length += Aone2Coder::size_string(m_name);

	// m_channel_params
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_channel_params.size(); i++)
	{
		length += m_channel_params[i].calc_length();
	}

	// m_channel_products
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_channel_products.size(); i++)
	{
		length += m_channel_products[i].calc_length();
	}

	// m_mcc_codes
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_mcc_codes.size(); i++)
	{
		length += m_mcc_codes[i].calc_length();
	}

	// m_bank_payways
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_bank_payways.size(); i++)
	{
		length += m_bank_payways[i].calc_length();
	}

	// m_card_payways
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_card_payways.size(); i++)
	{
		length += m_card_payways[i].calc_length();
	}

	// m_channel_products_ext
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_channel_products_ext.size(); i++)
	{
		length += m_channel_products_ext[i].calc_length();
	}

	// m_channel_version_info
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_channel_version_info.size(); i++)
	{
		length += m_channel_version_info[i].calc_length();
	}

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class LanguagesInfo
///////////////////////////////////////////////////////////////////////////////
LanguagesInfo::LanguagesInfo()
{
}

LanguagesInfo::~LanguagesInfo()
{
	// empty
}

int LanguagesInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_code
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_code)) return -1;

	// m_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_name)) return -1;

	// m_describe
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_describe)) return -1;

	return msglen;
}

int LanguagesInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_code
	if (!coder.set_string(m_code)) return -1;

	// m_name
	if (!coder.set_string(m_name)) return -1;

	// m_describe
	if (!coder.set_string(m_describe)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 LanguagesInfo::calc_length()
{
	uint32 length = 0;

	// m_code
	length += Aone2Coder::size_string(m_code);

	// m_name
	length += Aone2Coder::size_string(m_name);

	// m_describe
	length += Aone2Coder::size_string(m_describe);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class GroupInfo
///////////////////////////////////////////////////////////////////////////////
GroupInfo::GroupInfo()
{
	m_aone_group_id = 0;
}

GroupInfo::~GroupInfo()
{
	// empty
}

int GroupInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_aone_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_aone_group_id)) return -1;

	// m_cp_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_group_id)) return -1;

	return msglen;
}

int GroupInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_aone_group_id
	if (!coder.set_uint32(m_aone_group_id)) return -1;

	// m_cp_group_id
	if (!coder.set_string(m_cp_group_id)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 GroupInfo::calc_length()
{
	uint32 length = 0;

	// m_aone_group_id
	length += Aone2Coder::size_uint32(m_aone_group_id);

	// m_cp_group_id
	length += Aone2Coder::size_string(m_cp_group_id);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ForbidInfo
///////////////////////////////////////////////////////////////////////////////
ForbidInfo::ForbidInfo()
{
	// empty
}

ForbidInfo::~ForbidInfo()
{
	// empty
}

int ForbidInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_forbid_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string_vector(m_forbid_ip)) return -1;

	// m_forbid_device_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string_vector(m_forbid_device_id)) return -1;

	// m_forbid_uid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32_vector(m_forbid_uid)) return -1;

	return msglen;
}

int ForbidInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_forbid_ip
	if (!coder.set_string_vector(m_forbid_ip)) return -1;

	// m_forbid_device_id
	if (!coder.set_string_vector(m_forbid_device_id)) return -1;

	// m_forbid_uid
	if (!coder.set_uint32_vector(m_forbid_uid)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 ForbidInfo::calc_length()
{
	uint32 length = 0;

	// m_forbid_ip
	length += Aone2Coder::size_string_vector(m_forbid_ip);

	// m_forbid_device_id
	length += Aone2Coder::size_string_vector(m_forbid_device_id);

	// m_forbid_uid
	length += Aone2Coder::size_uint32_vector(m_forbid_uid);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ProductWhiteList
///////////////////////////////////////////////////////////////////////////////
ProductWhiteList::ProductWhiteList()
{
	// empty
}

ProductWhiteList::~ProductWhiteList()
{
	// empty
}

int ProductWhiteList::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string_vector(m_ip)) return -1;

	return msglen;
}

int ProductWhiteList::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_ip
	if (!coder.set_string_vector(m_ip)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 ProductWhiteList::calc_length()
{
	uint32 length = 0;

	// m_ip
	length += Aone2Coder::size_string_vector(m_ip);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class WebsiteProductInfo
///////////////////////////////////////////////////////////////////////////////
WebsiteProductInfo::WebsiteProductInfo()
{
	m_id = 0;
	m_max_group_id = 0;
}

WebsiteProductInfo::~WebsiteProductInfo()
{
	// empty
}

int WebsiteProductInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_id)) return -1;

	// m_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_key)) return -1;

	// m_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_name)) return -1;

	// m_describe
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_describe)) return -1;

	// m_product_line_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_product_line_name)) return -1;

	// m_paynotify_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_paynotify_url)) return -1;

	// m_payserver
	if (decoder.remain() == 0) return msglen;
	int payserver_ret = m_payserver.parse_bytes(decoder.position(), decoder.remain());
	if (payserver_ret <= 0) return payserver_ret;
	if (!decoder.set_pos(decoder.position() + payserver_ret)) return -1;

	// m_bbs_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_bbs_url)) return -1;

	// m_entryservers
	if (decoder.remain() == 0) return msglen;
	uint32 entryservers_count = 0;
	if (!decoder.get_uint32(entryservers_count)) return -1;
	for(uint32 i = 0; i < entryservers_count; i++)
	{
		m_entryservers.emplace_back(ServerInfo());
		ServerInfo& entryservers_ = m_entryservers.back();
		int entryservers_ret = entryservers_.parse_bytes(decoder.position(), decoder.remain());
		if (entryservers_ret <= 0) return entryservers_ret;
		if (!decoder.set_pos(decoder.position() + entryservers_ret)) return -1;
	}

	// m_languages
	if (decoder.remain() == 0) return msglen;
	uint32 languages_count = 0;
	if (!decoder.get_uint32(languages_count)) return -1;
	for(uint32 i = 0; i < languages_count; i++)
	{
		m_languages.emplace_back(LanguagesInfo());
		LanguagesInfo& languages_ = m_languages.back();
		int languages_ret = languages_.parse_bytes(decoder.position(), decoder.remain());
		if (languages_ret <= 0) return languages_ret;
		if (!decoder.set_pos(decoder.position() + languages_ret)) return -1;
	}

	// m_groups
	if (decoder.remain() == 0) return msglen;
	uint32 groups_count = 0;
	if (!decoder.get_uint32(groups_count)) return -1;
	for(uint32 i = 0; i < groups_count; i++)
	{
		m_groups.emplace_back(GroupInfo());
		GroupInfo& groups_ = m_groups.back();
		int groups_ret = groups_.parse_bytes(decoder.position(), decoder.remain());
		if (groups_ret <= 0) return groups_ret;
		if (!decoder.set_pos(decoder.position() + groups_ret)) return -1;
	}

	// m_channels
	if (decoder.remain() == 0) return msglen;
	uint32 channels_count = 0;
	if (!decoder.get_uint32(channels_count)) return -1;
	for(uint32 i = 0; i < channels_count; i++)
	{
		m_channels.emplace_back(ChannelInfo());
		ChannelInfo& channels_ = m_channels.back();
		int channels_ret = channels_.parse_bytes(decoder.position(), decoder.remain());
		if (channels_ret <= 0) return channels_ret;
		if (!decoder.set_pos(decoder.position() + channels_ret)) return -1;
	}

	// m_share_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_share_url)) return -1;

	// m_redirect_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_redirect_url)) return -1;

	// m_share_domain
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_share_domain)) return -1;

	// m_forbid_info
	if (decoder.remain() == 0) return msglen;
	int forbid_info_ret = m_forbid_info.parse_bytes(decoder.position(), decoder.remain());
	if (forbid_info_ret <= 0) return forbid_info_ret;
	if (!decoder.set_pos(decoder.position() + forbid_info_ret)) return -1;

	// m_max_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_max_group_id)) return -1;

	// m_product_whitelist
	if (decoder.remain() == 0) return msglen;
	int product_whitelist_ret = m_product_whitelist.parse_bytes(decoder.position(), decoder.remain());
	if (product_whitelist_ret <= 0) return product_whitelist_ret;
	if (!decoder.set_pos(decoder.position() + product_whitelist_ret)) return -1;

	return msglen;
}

int WebsiteProductInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_id
	if (!coder.set_uint32(m_id)) return -1;

	// m_key
	if (!coder.set_string(m_key)) return -1;

	// m_name
	if (!coder.set_string(m_name)) return -1;

	// m_describe
	if (!coder.set_string(m_describe)) return -1;

	// m_product_line_name
	if (!coder.set_string(m_product_line_name)) return -1;

	// m_paynotify_url
	if (!coder.set_string(m_paynotify_url)) return -1;

	// m_payserver
	int payserver_ret = m_payserver.to_bytes(coder.position(), coder.remain());
	if (payserver_ret <= 0) return payserver_ret;
	coder.set_pos(coder.position() + payserver_ret);

	// m_bbs_url
	if (!coder.set_string(m_bbs_url)) return -1;

	// m_entryservers
	if (!coder.set_uint32(m_entryservers.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_entryservers.size(); i++)
	{
		int entryservers_ret = m_entryservers[i].to_bytes(coder.position(), coder.remain());
		if (entryservers_ret <= 0) return entryservers_ret;
		coder.set_pos(coder.position() + entryservers_ret);
	}

	// m_languages
	if (!coder.set_uint32(m_languages.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_languages.size(); i++)
	{
		int languages_ret = m_languages[i].to_bytes(coder.position(), coder.remain());
		if (languages_ret <= 0) return languages_ret;
		coder.set_pos(coder.position() + languages_ret);
	}

	// m_groups
	if (!coder.set_uint32(m_groups.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_groups.size(); i++)
	{
		int groups_ret = m_groups[i].to_bytes(coder.position(), coder.remain());
		if (groups_ret <= 0) return groups_ret;
		coder.set_pos(coder.position() + groups_ret);
	}

	// m_channels
	if (!coder.set_uint32(m_channels.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_channels.size(); i++)
	{
		int channels_ret = m_channels[i].to_bytes(coder.position(), coder.remain());
		if (channels_ret <= 0) return channels_ret;
		coder.set_pos(coder.position() + channels_ret);
	}

	// m_share_url
	if (!coder.set_string(m_share_url)) return -1;

	// m_redirect_url
	if (!coder.set_string(m_redirect_url)) return -1;

	// m_share_domain
	if (!coder.set_string(m_share_domain)) return -1;

	// m_forbid_info
	int forbid_info_ret = m_forbid_info.to_bytes(coder.position(), coder.remain());
	if (forbid_info_ret <= 0) return forbid_info_ret;
	coder.set_pos(coder.position() + forbid_info_ret);

	// m_max_group_id
	if (!coder.set_uint32(m_max_group_id)) return -1;

	// m_product_whitelist
	int product_whitelist_ret = m_product_whitelist.to_bytes(coder.position(), coder.remain());
	if (product_whitelist_ret <= 0) return product_whitelist_ret;
	coder.set_pos(coder.position() + product_whitelist_ret);

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 WebsiteProductInfo::calc_length()
{
	uint32 length = 0;

	// m_id
	length += Aone2Coder::size_uint32(m_id);

	// m_key
	length += Aone2Coder::size_string(m_key);

	// m_name
	length += Aone2Coder::size_string(m_name);

	// m_describe
	length += Aone2Coder::size_string(m_describe);

	// m_product_line_name
	length += Aone2Coder::size_string(m_product_line_name);

	// m_paynotify_url
	length += Aone2Coder::size_string(m_paynotify_url);

	// m_payserver
	length += m_payserver.calc_length();

	// m_bbs_url
	length += Aone2Coder::size_string(m_bbs_url);

	// m_entryservers
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_entryservers.size(); i++)
	{
		length += m_entryservers[i].calc_length();
	}

	// m_languages
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_languages.size(); i++)
	{
		length += m_languages[i].calc_length();
	}

	// m_groups
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_groups.size(); i++)
	{
		length += m_groups[i].calc_length();
	}

	// m_channels
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_channels.size(); i++)
	{
		length += m_channels[i].calc_length();
	}

	// m_share_url
	length += Aone2Coder::size_string(m_share_url);

	// m_redirect_url
	length += Aone2Coder::size_string(m_redirect_url);

	// m_share_domain
	length += Aone2Coder::size_string(m_share_domain);

	// m_forbid_info
	length += m_forbid_info.calc_length();

	// m_max_group_id
	length += Aone2Coder::size_uint32(m_max_group_id);

	// m_product_whitelist
	length += m_product_whitelist.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class H5ProductInfo
///////////////////////////////////////////////////////////////////////////////
H5ProductInfo::H5ProductInfo()
{
	m_limit_count = 0;
	m_show_type = 0;
	m_is_first = 0;
	m_give_token = 0;
}

H5ProductInfo::~H5ProductInfo()
{
	// empty
}

int H5ProductInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_id)) return -1;

	// m_title
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_title)) return -1;

	// m_content
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_content)) return -1;

	// m_desc
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_desc)) return -1;

	// m_limit_count
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_limit_count)) return -1;

	// m_pay_index
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pay_index)) return -1;

	// m_show_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_show_type)) return -1;

	// m_is_first
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_first)) return -1;

	// m_give_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_give_token)) return -1;

	return msglen;
}

int H5ProductInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_id
	if (!coder.set_string(m_id)) return -1;

	// m_title
	if (!coder.set_string(m_title)) return -1;

	// m_content
	if (!coder.set_string(m_content)) return -1;

	// m_desc
	if (!coder.set_string(m_desc)) return -1;

	// m_limit_count
	if (!coder.set_uint32(m_limit_count)) return -1;

	// m_pay_index
	if (!coder.set_string(m_pay_index)) return -1;

	// m_show_type
	if (!coder.set_uint32(m_show_type)) return -1;

	// m_is_first
	if (!coder.set_bool(m_is_first)) return -1;

	// m_give_token
	if (!coder.set_uint32(m_give_token)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 H5ProductInfo::calc_length()
{
	uint32 length = 0;

	// m_id
	length += Aone2Coder::size_string(m_id);

	// m_title
	length += Aone2Coder::size_string(m_title);

	// m_content
	length += Aone2Coder::size_string(m_content);

	// m_desc
	length += Aone2Coder::size_string(m_desc);

	// m_limit_count
	length += Aone2Coder::size_uint32(m_limit_count);

	// m_pay_index
	length += Aone2Coder::size_string(m_pay_index);

	// m_show_type
	length += Aone2Coder::size_uint32(m_show_type);

	// m_is_first
	length += Aone2Coder::size_bool(m_is_first);

	// m_give_token
	length += Aone2Coder::size_uint32(m_give_token);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class H5ChargeRewardInfo
///////////////////////////////////////////////////////////////////////////////
H5ChargeRewardInfo::H5ChargeRewardInfo()
{
	m_index = 0;
	m_charge_sum = 0;
	m_is_reward = 0;
}

H5ChargeRewardInfo::~H5ChargeRewardInfo()
{
	// empty
}

int H5ChargeRewardInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_index
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_index)) return -1;

	// m_charge_sum
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_charge_sum)) return -1;

	// m_is_reward
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_reward)) return -1;

	// m_goods
	if (decoder.remain() == 0) return msglen;
	uint32 goods_count = 0;
	if (!decoder.get_uint32(goods_count)) return -1;
	for(uint32 i = 0; i < goods_count; i++)
	{
		m_goods.emplace_back(KVPair());
		KVPair& goods_ = m_goods.back();
		int goods_ret = goods_.parse_bytes(decoder.position(), decoder.remain());
		if (goods_ret <= 0) return goods_ret;
		if (!decoder.set_pos(decoder.position() + goods_ret)) return -1;
	}

	// m_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_name)) return -1;

	return msglen;
}

int H5ChargeRewardInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_index
	if (!coder.set_uint32(m_index)) return -1;

	// m_charge_sum
	if (!coder.set_uint32(m_charge_sum)) return -1;

	// m_is_reward
	if (!coder.set_bool(m_is_reward)) return -1;

	// m_goods
	if (!coder.set_uint32(m_goods.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_goods.size(); i++)
	{
		int goods_ret = m_goods[i].to_bytes(coder.position(), coder.remain());
		if (goods_ret <= 0) return goods_ret;
		coder.set_pos(coder.position() + goods_ret);
	}

	// m_name
	if (!coder.set_string(m_name)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 H5ChargeRewardInfo::calc_length()
{
	uint32 length = 0;

	// m_index
	length += Aone2Coder::size_uint32(m_index);

	// m_charge_sum
	length += Aone2Coder::size_uint32(m_charge_sum);

	// m_is_reward
	length += Aone2Coder::size_bool(m_is_reward);

	// m_goods
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_goods.size(); i++)
	{
		length += m_goods[i].calc_length();
	}

	// m_name
	length += Aone2Coder::size_string(m_name);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class H5RolePayInfo
///////////////////////////////////////////////////////////////////////////////
H5RolePayInfo::H5RolePayInfo()
{
	m_role_id = 0;
	m_user_id = 0;
	m_group_id = 0;
	m_role_level = 0;
	m_vip_level = 0;
	m_charge_sum = 0;
	m_charge_count = 0;
	m_h5_oversea_coin = 0;
}

H5RolePayInfo::~H5RolePayInfo()
{
	// empty
}

int H5RolePayInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_role_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_id)) return -1;

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_group_id)) return -1;

	// m_role_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_name)) return -1;

	// m_role_level
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_level)) return -1;

	// m_vip_level
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_vip_level)) return -1;

	// m_product_items
	if (decoder.remain() == 0) return msglen;
	uint32 product_items_count = 0;
	if (!decoder.get_uint32(product_items_count)) return -1;
	for(uint32 i = 0; i < product_items_count; i++)
	{
		m_product_items.emplace_back(H5ProductInfo());
		H5ProductInfo& product_items_ = m_product_items.back();
		int product_items_ret = product_items_.parse_bytes(decoder.position(), decoder.remain());
		if (product_items_ret <= 0) return product_items_ret;
		if (!decoder.set_pos(decoder.position() + product_items_ret)) return -1;
	}

	// m_role_channel
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_channel)) return -1;

	// m_group_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_group_name)) return -1;

	// m_charge_sum
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_charge_sum)) return -1;

	// m_charge_count
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_charge_count)) return -1;

	// m_charge_rewards
	if (decoder.remain() == 0) return msglen;
	uint32 charge_rewards_count = 0;
	if (!decoder.get_uint32(charge_rewards_count)) return -1;
	for(uint32 i = 0; i < charge_rewards_count; i++)
	{
		m_charge_rewards.emplace_back(H5ChargeRewardInfo());
		H5ChargeRewardInfo& charge_rewards_ = m_charge_rewards.back();
		int charge_rewards_ret = charge_rewards_.parse_bytes(decoder.position(), decoder.remain());
		if (charge_rewards_ret <= 0) return charge_rewards_ret;
		if (!decoder.set_pos(decoder.position() + charge_rewards_ret)) return -1;
	}

	// m_h5_oversea_coin
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_h5_oversea_coin)) return -1;

	return msglen;
}

int H5RolePayInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_role_id
	if (!coder.set_uint32(m_role_id)) return -1;

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_group_id
	if (!coder.set_uint32(m_group_id)) return -1;

	// m_role_name
	if (!coder.set_string(m_role_name)) return -1;

	// m_role_level
	if (!coder.set_uint32(m_role_level)) return -1;

	// m_vip_level
	if (!coder.set_uint32(m_vip_level)) return -1;

	// m_product_items
	if (!coder.set_uint32(m_product_items.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_product_items.size(); i++)
	{
		int product_items_ret = m_product_items[i].to_bytes(coder.position(), coder.remain());
		if (product_items_ret <= 0) return product_items_ret;
		coder.set_pos(coder.position() + product_items_ret);
	}

	// m_role_channel
	if (!coder.set_string(m_role_channel)) return -1;

	// m_group_name
	if (!coder.set_string(m_group_name)) return -1;

	// m_charge_sum
	if (!coder.set_uint32(m_charge_sum)) return -1;

	// m_charge_count
	if (!coder.set_uint32(m_charge_count)) return -1;

	// m_charge_rewards
	if (!coder.set_uint32(m_charge_rewards.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_charge_rewards.size(); i++)
	{
		int charge_rewards_ret = m_charge_rewards[i].to_bytes(coder.position(), coder.remain());
		if (charge_rewards_ret <= 0) return charge_rewards_ret;
		coder.set_pos(coder.position() + charge_rewards_ret);
	}

	// m_h5_oversea_coin
	if (!coder.set_uint32(m_h5_oversea_coin)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 H5RolePayInfo::calc_length()
{
	uint32 length = 0;

	// m_role_id
	length += Aone2Coder::size_uint32(m_role_id);

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_group_id
	length += Aone2Coder::size_uint32(m_group_id);

	// m_role_name
	length += Aone2Coder::size_string(m_role_name);

	// m_role_level
	length += Aone2Coder::size_uint32(m_role_level);

	// m_vip_level
	length += Aone2Coder::size_uint32(m_vip_level);

	// m_product_items
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_product_items.size(); i++)
	{
		length += m_product_items[i].calc_length();
	}

	// m_role_channel
	length += Aone2Coder::size_string(m_role_channel);

	// m_group_name
	length += Aone2Coder::size_string(m_group_name);

	// m_charge_sum
	length += Aone2Coder::size_uint32(m_charge_sum);

	// m_charge_count
	length += Aone2Coder::size_uint32(m_charge_count);

	// m_charge_rewards
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_charge_rewards.size(); i++)
	{
		length += m_charge_rewards[i].calc_length();
	}

	// m_h5_oversea_coin
	length += Aone2Coder::size_uint32(m_h5_oversea_coin);

	return length + sizeof(uint32);
}


////////////////////////////////////////////////////////////////////////////////
// message register
////////////////////////////////////////////////////////////////////////////////


}//namespace message
