// File: msg_xx_entryserver.cpp
// Auth: generated by auto tool 'lazybone'
// Desc: message define


#include "msg_xx_entryserver.h"
#include "aone2_helper.h"

namespace message {

///////////////////////////////////////////////////////////////////////////////
// class GameGroupInfo
///////////////////////////////////////////////////////////////////////////////
GameGroupInfo::GameGroupInfo()
{
	m_group_id = 0;
	m_server_port = 0;
	m_status = 0;
	m_is_recommend = 0;
	m_is_initialed = 0;
}

GameGroupInfo::~GameGroupInfo()
{
	// empty
}

int GameGroupInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_group_id)) return -1;

	// m_group_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_group_name)) return -1;

	// m_server_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_server_ip)) return -1;

	// m_server_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_server_port)) return -1;

	// m_status
	if (decoder.remain() == 0) return msglen;
	int32 status_ = 0;
	if (!decoder.get_int32(status_)) return -1;
	m_status = status_;

	// m_is_recommend
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_recommend)) return -1;

	// m_is_initialed
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_bool(m_is_initialed)) return -1;

	return msglen;
}

int GameGroupInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_group_id
	if (!coder.set_uint32(m_group_id)) return -1;

	// m_group_name
	if (!coder.set_string(m_group_name)) return -1;

	// m_server_ip
	if (!coder.set_string(m_server_ip)) return -1;

	// m_server_port
	if (!coder.set_uint16(m_server_port)) return -1;

	// m_status
	if (!coder.set_int32(m_status)) return -1;

	// m_is_recommend
	if (!coder.set_bool(m_is_recommend)) return -1;

	// m_is_initialed
	if (!coder.set_bool(m_is_initialed)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 GameGroupInfo::calc_length()
{
	uint32 length = 0;

	// m_group_id
	length += Aone2Coder::size_uint32(m_group_id);

	// m_group_name
	length += Aone2Coder::size_string(m_group_name);

	// m_server_ip
	length += Aone2Coder::size_string(m_server_ip);

	// m_server_port
	length += Aone2Coder::size_uint16(m_server_port);

	// m_status
	length += Aone2Coder::size_int32(m_status);

	// m_is_recommend
	length += Aone2Coder::size_bool(m_is_recommend);

	// m_is_initialed
	length += Aone2Coder::size_bool(m_is_initialed);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class CheckVerReqBody
///////////////////////////////////////////////////////////////////////////////
CheckVerReqBody::CheckVerReqBody()
{
}

CheckVerReqBody::~CheckVerReqBody()
{
	// empty
}

int CheckVerReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	return msglen;
}

int CheckVerReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 CheckVerReqBody::calc_length()
{
	uint32 length = 0;

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class CheckVerRespBody
///////////////////////////////////////////////////////////////////////////////
CheckVerRespBody::CheckVerRespBody()
{
	m_major_version = 0;
	m_minor_version = 0;
	m_revision_version = 0;
	m_status = 0;
}

CheckVerRespBody::~CheckVerRespBody()
{
	// empty
}

int CheckVerRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_major_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_major_version)) return -1;

	// m_minor_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_minor_version)) return -1;

	// m_revision_version
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint8(m_revision_version)) return -1;

	// m_status
	if (decoder.remain() == 0) return msglen;
	int32 status_ = 0;
	if (!decoder.get_int32(status_)) return -1;
	m_status = status_;

	// m_notice
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_notice)) return -1;

	// m_download_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_download_url)) return -1;

	// m_update_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_update_url)) return -1;

	// m_big_patcher_url
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_big_patcher_url)) return -1;

	return msglen;
}

int CheckVerRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_major_version
	if (!coder.set_uint8(m_major_version)) return -1;

	// m_minor_version
	if (!coder.set_uint8(m_minor_version)) return -1;

	// m_revision_version
	if (!coder.set_uint8(m_revision_version)) return -1;

	// m_status
	if (!coder.set_int32(m_status)) return -1;

	// m_notice
	if (!coder.set_string(m_notice)) return -1;

	// m_download_url
	if (!coder.set_string(m_download_url)) return -1;

	// m_update_url
	if (!coder.set_string(m_update_url)) return -1;

	// m_big_patcher_url
	if (!coder.set_string(m_big_patcher_url)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 CheckVerRespBody::calc_length()
{
	uint32 length = 0;

	// m_major_version
	length += Aone2Coder::size_uint8(m_major_version);

	// m_minor_version
	length += Aone2Coder::size_uint8(m_minor_version);

	// m_revision_version
	length += Aone2Coder::size_uint8(m_revision_version);

	// m_status
	length += Aone2Coder::size_int32(m_status);

	// m_notice
	length += Aone2Coder::size_string(m_notice);

	// m_download_url
	length += Aone2Coder::size_string(m_download_url);

	// m_update_url
	length += Aone2Coder::size_string(m_update_url);

	// m_big_patcher_url
	length += Aone2Coder::size_string(m_big_patcher_url);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class GetGameGroupsReqBody
///////////////////////////////////////////////////////////////////////////////
GetGameGroupsReqBody::GetGameGroupsReqBody()
{
}

GetGameGroupsReqBody::~GetGameGroupsReqBody()
{
	// empty
}

int GetGameGroupsReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	return msglen;
}

int GetGameGroupsReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 GetGameGroupsReqBody::calc_length()
{
	uint32 length = 0;

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class GetGameGroupsRespBody
///////////////////////////////////////////////////////////////////////////////
GetGameGroupsRespBody::GetGameGroupsRespBody()
{
	// empty
}

GetGameGroupsRespBody::~GetGameGroupsRespBody()
{
	// empty
}

int GetGameGroupsRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_groups
	if (decoder.remain() == 0) return msglen;
	uint32 groups_count = 0;
	if (!decoder.get_uint32(groups_count)) return -1;
	for(uint32 i = 0; i < groups_count; i++)
	{
		m_groups.push_back(GameGroupInfo());
		GameGroupInfo& groups_ = m_groups.back();
		int groups_ret = groups_.parse_bytes(decoder.position(), decoder.remain());
		if (groups_ret <= 0) return groups_ret;
		if (!decoder.set_pos(decoder.position() + groups_ret)) return -1;
	}

	return msglen;
}

int GetGameGroupsRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_groups
	if (!coder.set_uint32(m_groups.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_groups.size(); i++)
	{
		int groups_ret = m_groups[i].to_bytes(coder.position(), coder.remain());
		if (groups_ret <= 0) return groups_ret;
		coder.set_pos(coder.position() + groups_ret);
	}

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 GetGameGroupsRespBody::calc_length()
{
	uint32 length = 0;

	// m_groups
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_groups.size(); i++)
	{
		length += m_groups[i].calc_length();
	}

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class CreateRoleReqBody
///////////////////////////////////////////////////////////////////////////////
CreateRoleReqBody::CreateRoleReqBody()
{
	m_user_id = 0;
	m_user_token = 0;
	m_group_id = 0;
	m_role_type = 0;
}

CreateRoleReqBody::~CreateRoleReqBody()
{
	// empty
}

int CreateRoleReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_user_account
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_user_account)) return -1;

	// m_user_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_token)) return -1;

	// m_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_group_id)) return -1;

	// m_role_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_type)) return -1;

	// m_role_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_name)) return -1;

	// m_role_features
	if (decoder.remain() == 0) return msglen;
	uint32 role_features_count = 0;
	if (!decoder.get_uint32(role_features_count)) return -1;
	for(uint32 i = 0; i < role_features_count; i++)
	{
		m_role_features.emplace_back(KVPair());
		KVPair& role_features_ = m_role_features.back();
		int role_features_ret = role_features_.parse_bytes(decoder.position(), decoder.remain());
		if (role_features_ret <= 0) return role_features_ret;
		if (!decoder.set_pos(decoder.position() + role_features_ret)) return -1;
	}

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_encrypt_number
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_encrypt_number)) return -1;

	return msglen;
}

int CreateRoleReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_user_account
	if (!coder.set_string(m_user_account)) return -1;

	// m_user_token
	if (!coder.set_uint32(m_user_token)) return -1;

	// m_group_id
	if (!coder.set_uint32(m_group_id)) return -1;

	// m_role_type
	if (!coder.set_uint32(m_role_type)) return -1;

	// m_role_name
	if (!coder.set_string(m_role_name)) return -1;

	// m_role_features
	if (!coder.set_uint32(m_role_features.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_role_features.size(); i++)
	{
		int role_features_ret = m_role_features[i].to_bytes(coder.position(), coder.remain());
		if (role_features_ret <= 0) return role_features_ret;
		coder.set_pos(coder.position() + role_features_ret);
	}

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_encrypt_number
	if (!coder.set_string(m_encrypt_number)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 CreateRoleReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_user_account
	length += Aone2Coder::size_string(m_user_account);

	// m_user_token
	length += Aone2Coder::size_uint32(m_user_token);

	// m_group_id
	length += Aone2Coder::size_uint32(m_group_id);

	// m_role_type
	length += Aone2Coder::size_uint32(m_role_type);

	// m_role_name
	length += Aone2Coder::size_string(m_role_name);

	// m_role_features
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_role_features.size(); i++)
	{
		length += m_role_features[i].calc_length();
	}

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_encrypt_number
	length += Aone2Coder::size_string(m_encrypt_number);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class CreateRoleRespBody
///////////////////////////////////////////////////////////////////////////////
CreateRoleRespBody::CreateRoleRespBody()
{
	// empty
}

CreateRoleRespBody::~CreateRoleRespBody()
{
	// empty
}

int CreateRoleRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_role
	if (decoder.remain() == 0) return msglen;
	int role_ret = m_role.parse_bytes(decoder.position(), decoder.remain());
	if (role_ret <= 0) return role_ret;
	if (!decoder.set_pos(decoder.position() + role_ret)) return -1;

	return msglen;
}

int CreateRoleRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_role
	int role_ret = m_role.to_bytes(coder.position(), coder.remain());
	if (role_ret <= 0) return role_ret;
	coder.set_pos(coder.position() + role_ret);

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 CreateRoleRespBody::calc_length()
{
	uint32 length = 0;

	// m_role
	length += m_role.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class UserLoginReqBody
///////////////////////////////////////////////////////////////////////////////
UserLoginReqBody::UserLoginReqBody()
{
	m_user_id = 0;
}

UserLoginReqBody::~UserLoginReqBody()
{
	// empty
}

int UserLoginReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_token)) return -1;

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	return msglen;
}

int UserLoginReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_token
	if (!coder.set_string(m_token)) return -1;

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 UserLoginReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_token
	length += Aone2Coder::size_string(m_token);

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class UserLoginRespBody
///////////////////////////////////////////////////////////////////////////////
UserLoginRespBody::UserLoginRespBody()
{
	m_user_token = 0;
}

UserLoginRespBody::~UserLoginRespBody()
{
	// empty
}

int UserLoginRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_token)) return -1;

	// m_roles
	if (decoder.remain() == 0) return msglen;
	uint32 roles_count = 0;
	if (!decoder.get_uint32(roles_count)) return -1;
	for(uint32 i = 0; i < roles_count; i++)
	{
		m_roles.push_back(RoleShortInfo());
		RoleShortInfo& roles_ = m_roles.back();
		int roles_ret = roles_.parse_bytes(decoder.position(), decoder.remain());
		if (roles_ret <= 0) return roles_ret;
		if (!decoder.set_pos(decoder.position() + roles_ret)) return -1;
	}

	// m_groups
	if (decoder.remain() == 0) return msglen;
	uint32 groups_count = 0;
	if (!decoder.get_uint32(groups_count)) return -1;
	for(uint32 i = 0; i < groups_count; i++)
	{
		m_groups.push_back(GameGroupInfo());
		GameGroupInfo& groups_ = m_groups.back();
		int groups_ret = groups_.parse_bytes(decoder.position(), decoder.remain());
		if (groups_ret <= 0) return groups_ret;
		if (!decoder.set_pos(decoder.position() + groups_ret)) return -1;
	}

	return msglen;
}

int UserLoginRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_token
	if (!coder.set_uint32(m_user_token)) return -1;

	// m_roles
	if (!coder.set_uint32(m_roles.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_roles.size(); i++)
	{
		int roles_ret = m_roles[i].to_bytes(coder.position(), coder.remain());
		if (roles_ret <= 0) return roles_ret;
		coder.set_pos(coder.position() + roles_ret);
	}

	// m_groups
	if (!coder.set_uint32(m_groups.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_groups.size(); i++)
	{
		int groups_ret = m_groups[i].to_bytes(coder.position(), coder.remain());
		if (groups_ret <= 0) return groups_ret;
		coder.set_pos(coder.position() + groups_ret);
	}

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 UserLoginRespBody::calc_length()
{
	uint32 length = 0;

	// m_user_token
	length += Aone2Coder::size_uint32(m_user_token);

	// m_roles
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_roles.size(); i++)
	{
		length += m_roles[i].calc_length();
	}

	// m_groups
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_groups.size(); i++)
	{
		length += m_groups[i].calc_length();
	}

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class GetRoleInfoReqBody
///////////////////////////////////////////////////////////////////////////////
GetRoleInfoReqBody::GetRoleInfoReqBody()
{
	m_role_id = 0;
}

GetRoleInfoReqBody::~GetRoleInfoReqBody()
{
	// empty
}

int GetRoleInfoReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_role_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_role_id)) return -1;

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	return msglen;
}

int GetRoleInfoReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_role_id
	if (!coder.set_uint32(m_role_id)) return -1;

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 GetRoleInfoReqBody::calc_length()
{
	uint32 length = 0;

	// m_role_id
	length += Aone2Coder::size_uint32(m_role_id);

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class GetRoleInfoRespBody
///////////////////////////////////////////////////////////////////////////////
GetRoleInfoRespBody::GetRoleInfoRespBody()
{
	// empty
}

GetRoleInfoRespBody::~GetRoleInfoRespBody()
{
	// empty
}

int GetRoleInfoRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_role
	if (decoder.remain() == 0) return msglen;
	int role_ret = m_role.parse_bytes(decoder.position(), decoder.remain());
	if (role_ret <= 0) return role_ret;
	if (!decoder.set_pos(decoder.position() + role_ret)) return -1;

	return msglen;
}

int GetRoleInfoRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_role
	int role_ret = m_role.to_bytes(coder.position(), coder.remain());
	if (role_ret <= 0) return role_ret;
	coder.set_pos(coder.position() + role_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 GetRoleInfoRespBody::calc_length()
{
	uint32 length = 0;

	// m_role
	length += m_role.calc_length();

	return length + sizeof(uint32);
}


////////////////////////////////////////////////////////////////////////////////
// message register
////////////////////////////////////////////////////////////////////////////////
static XMessageCreatorRegister<Aone2BaseMessage, CheckVerRequest, uint32> regCheckVerRequest(CheckVerRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, CheckVerResponse, uint32> regCheckVerResponse(CheckVerResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, GetGameGroupsRequest, uint32> regGetGameGroupsRequest(GetGameGroupsRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, GetGameGroupsResponse, uint32> regGetGameGroupsResponse(GetGameGroupsResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, CreateRoleRequest, uint32> regCreateRoleRequest(CreateRoleRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, CreateRoleResponse, uint32> regCreateRoleResponse(CreateRoleResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, UserLoginRequest, uint32> regUserLoginRequest(UserLoginRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, UserLoginResponse, uint32> regUserLoginResponse(UserLoginResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, GetRoleInfoRequest, uint32> regGetRoleInfoRequest(GetRoleInfoRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, GetRoleInfoResponse, uint32> regGetRoleInfoResponse(GetRoleInfoResponse::NUMBER);


}//namespace message

