// File: msg_xx_global.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 定义一些公司内部使用的全局常量
// APP应用(AppId) ---> 发行渠道(channel) ----> 各平台支付方式(本文档只定义本公司平台支付方式)
//                                       |---> 各平台登陆方式(本文档只定义本公司平台登陆方式)
// 注：本公司平台与第三方平台同等看待，同等管理


#ifndef _MESSAGE_MSG_XX_GLOBAL_H_
#define _MESSAGE_MSG_XX_GLOBAL_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"
#include "msg_xx_config.h"

namespace message {

// 设备激活监控枚举
// Device Activation
class DA
{
public:
	enum _tagDA
	{
		STEP_NONO = 0,  // 未知
		STEP_APP_START = 10,  // 客户端启动
		STEP_CHECK_VERSION = 20,  // 检查版本前
		STEP_UPDATE_START = 30,  // 热更新开始
		STEP_UPDATE_FINISH = 40,  // 热更新完成
		STEP_SDK_CALL = 50,  // SDK界面弹出
		STEP_SDK_LOGIN = 60,  // SDK登录成功
		STEP_NOTICE_TIPS = 70,  // 公告界面
		STEP_CREATE_ROLE_START = 80,  // 到创角页面数
		STEP_CREATE_ROLE_FINISH = 90,  // 创建成功
		STEP_ENTRY_GAME = 100,  // 进入游戏
		STEP_END = 9999,  // 枚举结束
	} m_value;

	DA() : m_value((_tagDA)0) {}
	DA(int i) : m_value((_tagDA)i) {}
	DA& operator=(int i) { m_value = (_tagDA)i; return *this; }
	operator int() { return m_value; }
	operator int() const { return m_value; }
};

////////////////////////////////////////////////////////////////////////////////
// 终端设备信息
// class DeviceInfo
////////////////////////////////////////////////////////////////////////////////
class DeviceInfo : public Aone2MessageBody
{
public:
	DeviceInfo();

	virtual ~DeviceInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_device_id;  // 设备ID(唯一标识该设备)
	string  m_locale;  // (手机上设置的)国家和地区
	string  m_language;  // (手机上设置的)语言
	string  m_model;  // 设备型号(HTC渴望v5、Iphone5)
	string  m_os;  // 操作系统(IOS5、Android4.2)
	string  m_imei;  // IMEI码(不能获取则置空)
	string  m_ip;  // IP地址(客户端可能获取的为内网地址,服务端需要对该字段更新)
	string  m_mac;  // MAC地址(不能获取则置空)
	string  m_idfa;  // IOS填IDFA，安卓填安卓ID
};

////////////////////////////////////////////////////////////////////////////////
// App应用信息
// class AppVersionInfo
////////////////////////////////////////////////////////////////////////////////
class AppVersionInfo : public Aone2MessageBody
{
public:
	AppVersionInfo();

	virtual ~AppVersionInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_app_id;  // 应用ID(向平台申请得到)
	string  m_app_lang;  // 应用语言
	string  m_channel;  // 联运(发行)渠道商(见联运渠道编码表)
	uint8  m_major_version;  // 客户端主版本号
	uint8  m_minor_version;  // 客户端子版本号
	uint8  m_revision_version;  // 客户端修正版本号
	string  m_ext;  // 扩展参数
};

////////////////////////////////////////////////////////////////////////////////
// 通用键值对
// class KVPair
////////////////////////////////////////////////////////////////////////////////
class KVPair : public Aone2MessageBody
{
public:
	KVPair();

	virtual ~KVPair();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_key;  // 键
	string  m_value;  // 值
};

////////////////////////////////////////////////////////////////////////////////
// 角色简短信息
// class RoleShortInfo
////////////////////////////////////////////////////////////////////////////////
class RoleShortInfo : public Aone2MessageBody
{
public:
	RoleShortInfo();

	virtual ~RoleShortInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	uint32  m_role_id;  // 角色ID
	uint32  m_owner_groupid;  // 所属分区ID
	uint32  m_last_groupid;  // 最后登陆分区ID
	string  m_last_logintime;  // 最后登陆时间
	string  m_role_createtime;  // 角色创建时间
	uint32  m_role_type;  // 角色类型
	uint32  m_role_level;  // 角色等级
	string  m_role_name;  // 角色名
	vector<KVPair>  m_role_features;  // 角色扩展特性列表(kv键值对)
	string  m_channel;  // 联运(发行)渠道商(见联运渠道编码表)
	string  m_device_id;  // 角色最后一次登陆的设备ID
	uint32  m_role_vip;  // 角色VIP等级
};

////////////////////////////////////////////////////////////////////////////////
// 支付商品信息
// class PayProductInfo
////////////////////////////////////////////////////////////////////////////////
class PayProductInfo : public Aone2MessageBody
{
public:
	PayProductInfo();

	virtual ~PayProductInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_id;  // 商口ID(如：com.aonesoft.sanguo.item1)
	string  m_name;  // 商品名称(如：小袋金币)
	string  m_describe;  // 商品描述信息
	string  m_currency;  // 币种(如人民币:CNY,港币:HKY,美元:USD)
	double  m_amount;  // 币值(人民币单位为元,美元单位为美元)
	double  m_amount_usd;  // 转换为美元后的币值
	uint32  m_coin;  // 游戏代币数(不同游戏叫法不同,如金币,元宝等)
	string  m_type;  // 商品类型('' or 'normal': 空字符串表示定额普通商品; 'mol_pinpay': MOL pinPay(MOL钱包按normal处理); 'fortumo': fortumo支付)
	string  m_discount;  //折扣
};

////////////////////////////////////////////////////////////////////////////////
// 支付商品扩展信息
// class PayProductExtInfo
////////////////////////////////////////////////////////////////////////////////
class PayProductExtInfo : public Aone2MessageBody
{
public:
	PayProductExtInfo();

	virtual ~PayProductExtInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_id;  // 商口ID(如：com.aonesoft.sanguo.item1)
	string  m_cp_product_id;  // cp 商品id
	string  m_history_discount;  // 最近历史折扣(如：95|85|75)
};

////////////////////////////////////////////////////////////////////////////////
// Payways 支付渠道方式
// class Payways
////////////////////////////////////////////////////////////////////////////////
class Payways : public Aone2MessageBody
{
public:
	Payways();

	virtual ~Payways();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_pay_channel;
	vector<string>  m_pay_type;
};

////////////////////////////////////////////////////////////////////////////////
// class ChannelVersionInfo
////////////////////////////////////////////////////////////////////////////////
class ChannelVersionInfo : public Aone2MessageBody
{
public:
	ChannelVersionInfo();

	virtual ~ChannelVersionInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint8  m_major_version;  // 客户端主版本号
	uint8  m_minor_version;  // 客户端子版本号
	uint8  m_revision_version;  // 客户端修正版本号
	string  m_update_addr;  // 强更地址
	string  m_announce_addr;  // 公告地址
	string  m_announce_begin;  // 公告开始时间
	string  m_announce_end;  // 公告结束时间
	uint32  m_announce_rate;  // 公告显示频率
	bool  m_is_show_announce;  // 是否显示公告
	string  m_version_desc;  // 版本描述
	uint32  m_update_option;  // 更新选项 (0:不更新 1:可选更新 2:强更)
	bool  m_is_test;  // 是否测试
	bool  m_is_whitelist;  // 是否白名单
};

////////////////////////////////////////////////////////////////////////////////
// 渠道信息
// class ChannelInfo
////////////////////////////////////////////////////////////////////////////////
class ChannelInfo : public Aone2MessageBody
{
public:
	ChannelInfo();

	virtual ~ChannelInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_id;  // 渠道ID   aone_ios
	string  m_alias;  //渠道别名
	string  m_name;  // 渠道名
	vector<KVPair>  m_channel_params;  // 渠道(SDK)参数配置列表
	vector<PayProductInfo>  m_channel_products;  // 渠道支付商品列表
	vector<KVPair>  m_mcc_codes;  //mcc列表 key存code,value存name
	vector<Payways>  m_bank_payways;  //银行充值方式
	vector<Payways>  m_card_payways;  // 点卡充值方式
	vector<PayProductExtInfo>  m_channel_products_ext;  // 渠道支付商品列表扩展
	vector<ChannelVersionInfo>  m_channel_version_info;  // 渠道版本信息
};

////////////////////////////////////////////////////////////////////////////////
//语言信息
// class LanguagesInfo
////////////////////////////////////////////////////////////////////////////////
class LanguagesInfo : public Aone2MessageBody
{
public:
	LanguagesInfo();

	virtual ~LanguagesInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_code;  // 语言代码 En-us
	string  m_name;  // 语言名字(直接用所指语言写成的名字例如阿拉伯文) English
	string  m_describe;  //语言表述(汉语的表示) 英文
};

////////////////////////////////////////////////////////////////////////////////
//分区信息
// class GroupInfo
////////////////////////////////////////////////////////////////////////////////
class GroupInfo : public Aone2MessageBody
{
public:
	GroupInfo();

	virtual ~GroupInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_aone_group_id;  //aone 发行平台分配的分区ID
	string  m_cp_group_id;  //cp 方游戏自己分配的分区ID
};

////////////////////////////////////////////////////////////////////////////////
//禁止登陆信息
// class ForbidInfo
////////////////////////////////////////////////////////////////////////////////
class ForbidInfo : public Aone2MessageBody
{
public:
	ForbidInfo();

	virtual ~ForbidInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<string>  m_forbid_ip;  // 禁止的ip
	vector<string>  m_forbid_device_id;  // 禁止的设备
	vector<uint32>  m_forbid_uid;  // 禁止的uid
};

////////////////////////////////////////////////////////////////////////////////
// 产品白名单
// class ProductWhiteList
////////////////////////////////////////////////////////////////////////////////
class ProductWhiteList : public Aone2MessageBody
{
public:
	ProductWhiteList();

	virtual ~ProductWhiteList();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<string>  m_ip;
};

////////////////////////////////////////////////////////////////////////////////
// 站点产品信息
// class WebsiteProductInfo
////////////////////////////////////////////////////////////////////////////////
class WebsiteProductInfo : public Aone2MessageBody
{
public:
	WebsiteProductInfo();

	virtual ~WebsiteProductInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_id;  // 产品ID
	string  m_key;  //产品密钥（规则自定义）
	string  m_name;  // 产品名称
	string  m_describe;  // 产品描述
	string  m_product_line_name;  //隶属产品线名称
	string  m_paynotify_url;  // 通知cp支付服的地址
	SecurityServerInfo  m_payserver;  // 自有支付服务地址，例如：aonepay.com:8000
	string  m_bbs_url;  // 游戏论坛地址（设计字段默认为"",不显示）
	vector<ServerInfo>  m_entryservers;  // 入口服务列表 key存ip value存port 例如:  192.168.7.1:8000 key=192.168.7.1 value=8000（设计字段默认为"",不显示）
	vector<LanguagesInfo>  m_languages;  // 语言列表
	vector<GroupInfo>  m_groups;
	vector<ChannelInfo>  m_channels;  // 渠道列表
	string  m_share_url;  // 推荐下载地址
	string  m_redirect_url;  // 应用内跳转地址
	string  m_share_domain;  // 分享域名
	ForbidInfo  m_forbid_info;  // 禁止登陆信息
	uint32  m_max_group_id;  // (0:表示手动设置group_id)
	ProductWhiteList  m_product_whitelist;  // 产品白名单
};

////////////////////////////////////////////////////////////////////////////////
// H5支付商品信息
// class H5ProductInfo
////////////////////////////////////////////////////////////////////////////////
class H5ProductInfo : public Aone2MessageBody
{
public:
	H5ProductInfo();

	virtual ~H5ProductInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_id;  // 商品Id
	string  m_title;  // 商品标题
	string  m_content;  // 商品内容
	string  m_desc;  // 商品描述
	uint32  m_limit_count;  // 限购次数
	string  m_pay_index;  // cp_ext参数
	uint32  m_show_type;  // 展示类型(热门等)
	bool  m_is_first;  // 是否是首冲
	uint32  m_give_token;  // 额外赠送
};

////////////////////////////////////////////////////////////////////////////////
// 可领取奖励信息
// class H5ChargeRewardInfo
////////////////////////////////////////////////////////////////////////////////
class H5ChargeRewardInfo : public Aone2MessageBody
{
public:
	H5ChargeRewardInfo();

	virtual ~H5ChargeRewardInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_index;  // 累计档位
	uint32  m_charge_sum;  // 累计额度
	bool  m_is_reward;  // 是否已经领取
	vector<KVPair>  m_goods;  // 道具信息(k:道具名字;v:道具数量)
	string  m_name;  // 礼包名字
};

////////////////////////////////////////////////////////////////////////////////
// H5网页支付信息
// class H5RolePayInfo
////////////////////////////////////////////////////////////////////////////////
class H5RolePayInfo : public Aone2MessageBody
{
public:
	H5RolePayInfo();

	virtual ~H5RolePayInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_role_id;  // 角色Id
	uint32  m_user_id;  // 账号Id
	uint32  m_group_id;  // 分区Id
	string  m_role_name;  // 角色名字
	uint32  m_role_level;  // 角色等级
	uint32  m_vip_level;  // vip等级
	vector<H5ProductInfo>  m_product_items;  // 商品信息
	string  m_role_channel;  // 角色channel
	string  m_group_name;  // 分区名
	uint32  m_charge_sum;  // 累计充值额度(包括游戏中充值)
	uint32  m_charge_count;  // 累计充值次数(包括游戏中充值)
	vector<H5ChargeRewardInfo>  m_charge_rewards;  // 累计充值领取道具信息
	uint32  m_h5_oversea_coin;  // h5海外网页充值代币
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_GLOBAL_H_
