// File: msg_xx_apiserver_ex.cpp
// Auth: generated by auto tool 'lazybone'
// Desc: message define


#include "msg_xx_apiserver_ex.h"
#include "aone2_helper.h"

namespace message {

///////////////////////////////////////////////////////////////////////////////
// class RecordClientCoreReqBody
///////////////////////////////////////////////////////////////////////////////
RecordClientCoreReqBody::RecordClientCoreReqBody()
{
	m_user_id = 0;
}

RecordClientCoreReqBody::~RecordClientCoreReqBody()
{
	// empty
}

int RecordClientCoreReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_role_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_id)) return -1;

	// m_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_group_id)) return -1;

	// m_role_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_role_name)) return -1;

	// m_errorLine
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_errorLine)) return -1;

	// m_errorStack
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_errorStack)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	return msglen;
}

int RecordClientCoreReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_role_id
	if (!coder.set_string(m_role_id)) return -1;

	// m_group_id
	if (!coder.set_string(m_group_id)) return -1;

	// m_role_name
	if (!coder.set_string(m_role_name)) return -1;

	// m_errorLine
	if (!coder.set_string(m_errorLine)) return -1;

	// m_errorStack
	if (!coder.set_string(m_errorStack)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 RecordClientCoreReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_role_id
	length += Aone2Coder::size_string(m_role_id);

	// m_group_id
	length += Aone2Coder::size_string(m_group_id);

	// m_role_name
	length += Aone2Coder::size_string(m_role_name);

	// m_errorLine
	length += Aone2Coder::size_string(m_errorLine);

	// m_errorStack
	length += Aone2Coder::size_string(m_errorStack);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class HolidayInfoRespBody
///////////////////////////////////////////////////////////////////////////////
HolidayInfoRespBody::HolidayInfoRespBody()
{
	// empty
}

HolidayInfoRespBody::~HolidayInfoRespBody()
{
	// empty
}

int HolidayInfoRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_days
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string_vector(m_days)) return -1;

	return msglen;
}

int HolidayInfoRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_days
	if (!coder.set_string_vector(m_days)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 HolidayInfoRespBody::calc_length()
{
	uint32 length = 0;

	// m_days
	length += Aone2Coder::size_string_vector(m_days);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class SwapUidReqBody
///////////////////////////////////////////////////////////////////////////////
SwapUidReqBody::SwapUidReqBody()
{
	m_user_id1 = 0;
	m_user_id2 = 0;
}

SwapUidReqBody::~SwapUidReqBody()
{
	// empty
}

int SwapUidReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id1
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id1)) return -1;

	// m_user_id2
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id2)) return -1;

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_token)) return -1;

	return msglen;
}

int SwapUidReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id1
	if (!coder.set_uint32(m_user_id1)) return -1;

	// m_user_id2
	if (!coder.set_uint32(m_user_id2)) return -1;

	// m_token
	if (!coder.set_string(m_token)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 SwapUidReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id1
	length += Aone2Coder::size_uint32(m_user_id1);

	// m_user_id2
	length += Aone2Coder::size_uint32(m_user_id2);

	// m_token
	length += Aone2Coder::size_string(m_token);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QueryAoneAccountReqBody
///////////////////////////////////////////////////////////////////////////////
QueryAoneAccountReqBody::QueryAoneAccountReqBody()
{
	m_delay_ms = 0;
}

QueryAoneAccountReqBody::~QueryAoneAccountReqBody()
{
	// empty
}

int QueryAoneAccountReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_account
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_account)) return -1;

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_delay_ms
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_delay_ms)) return -1;

	return msglen;
}

int QueryAoneAccountReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_account
	if (!coder.set_string(m_account)) return -1;

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_delay_ms
	if (!coder.set_uint32(m_delay_ms)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QueryAoneAccountReqBody::calc_length()
{
	uint32 length = 0;

	// m_account
	length += Aone2Coder::size_string(m_account);

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_delay_ms
	length += Aone2Coder::size_uint32(m_delay_ms);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QueryAoneAccountRespBody
///////////////////////////////////////////////////////////////////////////////
QueryAoneAccountRespBody::QueryAoneAccountRespBody()
{
	m_user_id = 0;
	m_flag = 0;
}

QueryAoneAccountRespBody::~QueryAoneAccountRespBody()
{
	// empty
}

int QueryAoneAccountRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_account
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_account)) return -1;

	// m_device_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_device_id)) return -1;

	// m_phone
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_phone)) return -1;

	// m_mail
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_mail)) return -1;

	// m_weixin
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_weixin)) return -1;

	// m_flag
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_flag)) return -1;

	// m_create_time
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_create_time)) return -1;

	return msglen;
}

int QueryAoneAccountRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_account
	if (!coder.set_string(m_account)) return -1;

	// m_device_id
	if (!coder.set_string(m_device_id)) return -1;

	// m_phone
	if (!coder.set_string(m_phone)) return -1;

	// m_mail
	if (!coder.set_string(m_mail)) return -1;

	// m_weixin
	if (!coder.set_string(m_weixin)) return -1;

	// m_flag
	if (!coder.set_uint32(m_flag)) return -1;

	// m_create_time
	if (!coder.set_string(m_create_time)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QueryAoneAccountRespBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_account
	length += Aone2Coder::size_string(m_account);

	// m_device_id
	length += Aone2Coder::size_string(m_device_id);

	// m_phone
	length += Aone2Coder::size_string(m_phone);

	// m_mail
	length += Aone2Coder::size_string(m_mail);

	// m_weixin
	length += Aone2Coder::size_string(m_weixin);

	// m_flag
	length += Aone2Coder::size_uint32(m_flag);

	// m_create_time
	length += Aone2Coder::size_string(m_create_time);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class CheckPhoneTokenReqBody
///////////////////////////////////////////////////////////////////////////////
CheckPhoneTokenReqBody::CheckPhoneTokenReqBody()
{
	m_delay_ms = 0;
}

CheckPhoneTokenReqBody::~CheckPhoneTokenReqBody()
{
	// empty
}

int CheckPhoneTokenReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_phone
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_phone)) return -1;

	// m_phone_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_phone_token)) return -1;

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_delay_ms
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_delay_ms)) return -1;

	return msglen;
}

int CheckPhoneTokenReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_phone
	if (!coder.set_string(m_phone)) return -1;

	// m_phone_token
	if (!coder.set_string(m_phone_token)) return -1;

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_delay_ms
	if (!coder.set_uint32(m_delay_ms)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 CheckPhoneTokenReqBody::calc_length()
{
	uint32 length = 0;

	// m_phone
	length += Aone2Coder::size_string(m_phone);

	// m_phone_token
	length += Aone2Coder::size_string(m_phone_token);

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_delay_ms
	length += Aone2Coder::size_uint32(m_delay_ms);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QueryAoneUidReqBody
///////////////////////////////////////////////////////////////////////////////
QueryAoneUidReqBody::QueryAoneUidReqBody()
{
	m_delay_ms = 0;
}

QueryAoneUidReqBody::~QueryAoneUidReqBody()
{
	// empty
}

int QueryAoneUidReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_account
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_account)) return -1;

	// m_phone
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_phone)) return -1;

	// m_auth_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_auth_key)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_delay_ms
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_delay_ms)) return -1;

	return msglen;
}

int QueryAoneUidReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_account
	if (!coder.set_string(m_account)) return -1;

	// m_phone
	if (!coder.set_string(m_phone)) return -1;

	// m_auth_key
	if (!coder.set_string(m_auth_key)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_delay_ms
	if (!coder.set_uint32(m_delay_ms)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QueryAoneUidReqBody::calc_length()
{
	uint32 length = 0;

	// m_account
	length += Aone2Coder::size_string(m_account);

	// m_phone
	length += Aone2Coder::size_string(m_phone);

	// m_auth_key
	length += Aone2Coder::size_string(m_auth_key);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_delay_ms
	length += Aone2Coder::size_uint32(m_delay_ms);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QueryAoneUidRespBody
///////////////////////////////////////////////////////////////////////////////
QueryAoneUidRespBody::QueryAoneUidRespBody()
{
	m_user_id = 0;
}

QueryAoneUidRespBody::~QueryAoneUidRespBody()
{
	// empty
}

int QueryAoneUidRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	return msglen;
}

int QueryAoneUidRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QueryAoneUidRespBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QueryUidByAccountReqBody
///////////////////////////////////////////////////////////////////////////////
QueryUidByAccountReqBody::QueryUidByAccountReqBody()
{
}

QueryUidByAccountReqBody::~QueryUidByAccountReqBody()
{
	// empty
}

int QueryUidByAccountReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_type)) return -1;

	// m_account
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_account)) return -1;

	return msglen;
}

int QueryUidByAccountReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_type
	if (!coder.set_string(m_type)) return -1;

	// m_account
	if (!coder.set_string(m_account)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QueryUidByAccountReqBody::calc_length()
{
	uint32 length = 0;

	// m_type
	length += Aone2Coder::size_string(m_type);

	// m_account
	length += Aone2Coder::size_string(m_account);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QueryUidByAccountRespBody
///////////////////////////////////////////////////////////////////////////////
QueryUidByAccountRespBody::QueryUidByAccountRespBody()
{
	m_uid = 0;
}

QueryUidByAccountRespBody::~QueryUidByAccountRespBody()
{
	// empty
}

int QueryUidByAccountRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_uid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_uid)) return -1;

	return msglen;
}

int QueryUidByAccountRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_uid
	if (!coder.set_uint32(m_uid)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QueryUidByAccountRespBody::calc_length()
{
	uint32 length = 0;

	// m_uid
	length += Aone2Coder::size_uint32(m_uid);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class AccountWriteOffReqBody
///////////////////////////////////////////////////////////////////////////////
AccountWriteOffReqBody::AccountWriteOffReqBody()
{
}

AccountWriteOffReqBody::~AccountWriteOffReqBody()
{
	// empty
}

int AccountWriteOffReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_account
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_account)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	return msglen;
}

int AccountWriteOffReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_account
	if (!coder.set_string(m_account)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 AccountWriteOffReqBody::calc_length()
{
	uint32 length = 0;

	// m_account
	length += Aone2Coder::size_string(m_account);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class AccountDelayWriteOffReqBody
///////////////////////////////////////////////////////////////////////////////
AccountDelayWriteOffReqBody::AccountDelayWriteOffReqBody()
{
	m_user_id = 0;
	m_type = 0;
}

AccountDelayWriteOffReqBody::~AccountDelayWriteOffReqBody()
{
	// empty
}

int AccountDelayWriteOffReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_token)) return -1;

	// m_type
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_type)) return -1;

	// m_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_ip)) return -1;

	// m_device_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_device_id)) return -1;

	// m_channel
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_channel)) return -1;

	return msglen;
}

int AccountDelayWriteOffReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_token
	if (!coder.set_string(m_token)) return -1;

	// m_type
	if (!coder.set_uint32(m_type)) return -1;

	// m_ip
	if (!coder.set_string(m_ip)) return -1;

	// m_device_id
	if (!coder.set_string(m_device_id)) return -1;

	// m_channel
	if (!coder.set_string(m_channel)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 AccountDelayWriteOffReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_token
	length += Aone2Coder::size_string(m_token);

	// m_type
	length += Aone2Coder::size_uint32(m_type);

	// m_ip
	length += Aone2Coder::size_string(m_ip);

	// m_device_id
	length += Aone2Coder::size_string(m_device_id);

	// m_channel
	length += Aone2Coder::size_string(m_channel);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class AccountDelayWriteOffRespBody
///////////////////////////////////////////////////////////////////////////////
AccountDelayWriteOffRespBody::AccountDelayWriteOffRespBody()
{
	m_write_off_time = 0;
}

AccountDelayWriteOffRespBody::~AccountDelayWriteOffRespBody()
{
	// empty
}

int AccountDelayWriteOffRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_write_off_time
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_write_off_time)) return -1;

	return msglen;
}

int AccountDelayWriteOffRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_write_off_time
	if (!coder.set_uint32(m_write_off_time)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 AccountDelayWriteOffRespBody::calc_length()
{
	uint32 length = 0;

	// m_write_off_time
	length += Aone2Coder::size_uint32(m_write_off_time);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class MidasPayReqBody
///////////////////////////////////////////////////////////////////////////////
MidasPayReqBody::MidasPayReqBody()
{
	m_user_id = 0;
	m_product_quantity = 1;
	m_appmode = "1";
}

MidasPayReqBody::~MidasPayReqBody()
{
	// empty
}

int MidasPayReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_product_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_product_id)) return -1;

	// m_product_quantity
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_product_quantity)) return -1;

	// m_cp_role_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_role_id)) return -1;

	// m_cp_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_group_id)) return -1;

	// m_cp_ext
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_ext)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_openid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_openid)) return -1;

	// m_openkey
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_openkey)) return -1;

	// m_pf
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pf)) return -1;

	// m_pfkey
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pfkey)) return -1;

	// m_payitem
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_payitem)) return -1;

	// m_appmode
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_appmode)) return -1;

	// m_goodsmeta
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_goodsmeta)) return -1;

	// m_goodsurl
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_goodsurl)) return -1;

	return msglen;
}

int MidasPayReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_product_id
	if (!coder.set_string(m_product_id)) return -1;

	// m_product_quantity
	if (!coder.set_uint32(m_product_quantity)) return -1;

	// m_cp_role_id
	if (!coder.set_string(m_cp_role_id)) return -1;

	// m_cp_group_id
	if (!coder.set_string(m_cp_group_id)) return -1;

	// m_cp_ext
	if (!coder.set_string(m_cp_ext)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_openid
	if (!coder.set_string(m_openid)) return -1;

	// m_openkey
	if (!coder.set_string(m_openkey)) return -1;

	// m_pf
	if (!coder.set_string(m_pf)) return -1;

	// m_pfkey
	if (!coder.set_string(m_pfkey)) return -1;

	// m_payitem
	if (!coder.set_string(m_payitem)) return -1;

	// m_appmode
	if (!coder.set_string(m_appmode)) return -1;

	// m_goodsmeta
	if (!coder.set_string(m_goodsmeta)) return -1;

	// m_goodsurl
	if (!coder.set_string(m_goodsurl)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 MidasPayReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_product_id
	length += Aone2Coder::size_string(m_product_id);

	// m_product_quantity
	length += Aone2Coder::size_uint32(m_product_quantity);

	// m_cp_role_id
	length += Aone2Coder::size_string(m_cp_role_id);

	// m_cp_group_id
	length += Aone2Coder::size_string(m_cp_group_id);

	// m_cp_ext
	length += Aone2Coder::size_string(m_cp_ext);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_openid
	length += Aone2Coder::size_string(m_openid);

	// m_openkey
	length += Aone2Coder::size_string(m_openkey);

	// m_pf
	length += Aone2Coder::size_string(m_pf);

	// m_pfkey
	length += Aone2Coder::size_string(m_pfkey);

	// m_payitem
	length += Aone2Coder::size_string(m_payitem);

	// m_appmode
	length += Aone2Coder::size_string(m_appmode);

	// m_goodsmeta
	length += Aone2Coder::size_string(m_goodsmeta);

	// m_goodsurl
	length += Aone2Coder::size_string(m_goodsurl);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class MidasPayRespBody
///////////////////////////////////////////////////////////////////////////////
MidasPayRespBody::MidasPayRespBody()
{
	m_discount = 0;
}

MidasPayRespBody::~MidasPayRespBody()
{
	// empty
}

int MidasPayRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_pay_no
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pay_no)) return -1;

	// m_discount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_discount)) return -1;

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_token)) return -1;

	// m_url_params
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_url_params)) return -1;

	return msglen;
}

int MidasPayRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_pay_no
	if (!coder.set_string(m_pay_no)) return -1;

	// m_discount
	if (!coder.set_uint32(m_discount)) return -1;

	// m_token
	if (!coder.set_string(m_token)) return -1;

	// m_url_params
	if (!coder.set_string(m_url_params)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 MidasPayRespBody::calc_length()
{
	uint32 length = 0;

	// m_pay_no
	length += Aone2Coder::size_string(m_pay_no);

	// m_discount
	length += Aone2Coder::size_uint32(m_discount);

	// m_token
	length += Aone2Coder::size_string(m_token);

	// m_url_params
	length += Aone2Coder::size_string(m_url_params);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QQGameHallPayReqBody
///////////////////////////////////////////////////////////////////////////////
QQGameHallPayReqBody::QQGameHallPayReqBody()
{
	m_user_id = 0;
	m_product_quantity = 1;
	m_appmode = "1";
}

QQGameHallPayReqBody::~QQGameHallPayReqBody()
{
	// empty
}

int QQGameHallPayReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_product_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_product_id)) return -1;

	// m_product_quantity
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_product_quantity)) return -1;

	// m_cp_role_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_role_id)) return -1;

	// m_cp_group_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_group_id)) return -1;

	// m_cp_ext
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cp_ext)) return -1;

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_openid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_openid)) return -1;

	// m_openkey
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_openkey)) return -1;

	// m_pf
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pf)) return -1;

	// m_pfkey
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pfkey)) return -1;

	// m_amt
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_amt)) return -1;

	// m_payitem
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_payitem)) return -1;

	// m_appmode
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_appmode)) return -1;

	// m_goodsmeta
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_goodsmeta)) return -1;

	// m_goodsurl
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_goodsurl)) return -1;

	return msglen;
}

int QQGameHallPayReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_product_id
	if (!coder.set_string(m_product_id)) return -1;

	// m_product_quantity
	if (!coder.set_uint32(m_product_quantity)) return -1;

	// m_cp_role_id
	if (!coder.set_string(m_cp_role_id)) return -1;

	// m_cp_group_id
	if (!coder.set_string(m_cp_group_id)) return -1;

	// m_cp_ext
	if (!coder.set_string(m_cp_ext)) return -1;

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_openid
	if (!coder.set_string(m_openid)) return -1;

	// m_openkey
	if (!coder.set_string(m_openkey)) return -1;

	// m_pf
	if (!coder.set_string(m_pf)) return -1;

	// m_pfkey
	if (!coder.set_string(m_pfkey)) return -1;

	// m_amt
	if (!coder.set_string(m_amt)) return -1;

	// m_payitem
	if (!coder.set_string(m_payitem)) return -1;

	// m_appmode
	if (!coder.set_string(m_appmode)) return -1;

	// m_goodsmeta
	if (!coder.set_string(m_goodsmeta)) return -1;

	// m_goodsurl
	if (!coder.set_string(m_goodsurl)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QQGameHallPayReqBody::calc_length()
{
	uint32 length = 0;

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_product_id
	length += Aone2Coder::size_string(m_product_id);

	// m_product_quantity
	length += Aone2Coder::size_uint32(m_product_quantity);

	// m_cp_role_id
	length += Aone2Coder::size_string(m_cp_role_id);

	// m_cp_group_id
	length += Aone2Coder::size_string(m_cp_group_id);

	// m_cp_ext
	length += Aone2Coder::size_string(m_cp_ext);

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_openid
	length += Aone2Coder::size_string(m_openid);

	// m_openkey
	length += Aone2Coder::size_string(m_openkey);

	// m_pf
	length += Aone2Coder::size_string(m_pf);

	// m_pfkey
	length += Aone2Coder::size_string(m_pfkey);

	// m_amt
	length += Aone2Coder::size_string(m_amt);

	// m_payitem
	length += Aone2Coder::size_string(m_payitem);

	// m_appmode
	length += Aone2Coder::size_string(m_appmode);

	// m_goodsmeta
	length += Aone2Coder::size_string(m_goodsmeta);

	// m_goodsurl
	length += Aone2Coder::size_string(m_goodsurl);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class QQGameHallPayRespBody
///////////////////////////////////////////////////////////////////////////////
QQGameHallPayRespBody::QQGameHallPayRespBody()
{
	m_discount = 0;
}

QQGameHallPayRespBody::~QQGameHallPayRespBody()
{
	// empty
}

int QQGameHallPayRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_pay_no
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_pay_no)) return -1;

	// m_discount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_discount)) return -1;

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_token)) return -1;

	// m_url_params
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_url_params)) return -1;

	return msglen;
}

int QQGameHallPayRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_pay_no
	if (!coder.set_string(m_pay_no)) return -1;

	// m_discount
	if (!coder.set_uint32(m_discount)) return -1;

	// m_token
	if (!coder.set_string(m_token)) return -1;

	// m_url_params
	if (!coder.set_string(m_url_params)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	return *(uint32*)dst;
}

uint32 QQGameHallPayRespBody::calc_length()
{
	uint32 length = 0;

	// m_pay_no
	length += Aone2Coder::size_string(m_pay_no);

	// m_discount
	length += Aone2Coder::size_uint32(m_discount);

	// m_token
	length += Aone2Coder::size_string(m_token);

	// m_url_params
	length += Aone2Coder::size_string(m_url_params);

	return length + sizeof(uint32);
}


////////////////////////////////////////////////////////////////////////////////
// message register
////////////////////////////////////////////////////////////////////////////////
static XMessageCreatorRegister<Aone2BaseMessage, RecordClientCoreRequest, uint32> regRecordClientCoreRequest(RecordClientCoreRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, RecordClientCoreResponse, uint32> regRecordClientCoreResponse(RecordClientCoreResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, HolidayInfoRequest, uint32> regHolidayInfoRequest(HolidayInfoRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, HolidayInfoResponse, uint32> regHolidayInfoResponse(HolidayInfoResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, SwapUidRequest, uint32> regSwapUidRequest(SwapUidRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, SwapUidResponse, uint32> regSwapUidResponse(SwapUidResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QueryAoneAccountRequest, uint32> regQueryAoneAccountRequest(QueryAoneAccountRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QueryAoneAccountResponse, uint32> regQueryAoneAccountResponse(QueryAoneAccountResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, CheckPhoneTokenRequest, uint32> regCheckPhoneTokenRequest(CheckPhoneTokenRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, CheckPhoneTokenResponse, uint32> regCheckPhoneTokenResponse(CheckPhoneTokenResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QueryAoneUidRequest, uint32> regQueryAoneUidRequest(QueryAoneUidRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QueryAoneUidResponse, uint32> regQueryAoneUidResponse(QueryAoneUidResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QueryUidByAccountRequest, uint32> regQueryUidByAccountRequest(QueryUidByAccountRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QueryUidByAccountResponse, uint32> regQueryUidByAccountResponse(QueryUidByAccountResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, AccountWriteOffRequest, uint32> regAccountWriteOffRequest(AccountWriteOffRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, AccountWriteOffResponse, uint32> regAccountWriteOffResponse(AccountWriteOffResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, AccountDelayWriteOffRequest, uint32> regAccountDelayWriteOffRequest(AccountDelayWriteOffRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, AccountDelayWriteOffResponse, uint32> regAccountDelayWriteOffResponse(AccountDelayWriteOffResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, MidasPayRequest, uint32> regMidasPayRequest(MidasPayRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, MidasPayResponse, uint32> regMidasPayResponse(MidasPayResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QQGameHallPayRequest, uint32> regQQGameHallPayRequest(QQGameHallPayRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, QQGameHallPayResponse, uint32> regQQGameHallPayResponse(QQGameHallPayResponse::NUMBER);


}//namespace message
