/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aonesoft_lib_AoneClient */

#ifndef _Included_com_aonesoft_lib_AoneClient
#define _Included_com_aonesoft_lib_AoneClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeHasExitUI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_aonesoft_lib_AoneClient_nativeHasExitUI
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeExit
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeInitSDK
 * Signature: (Lcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeInitSDK
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeAoneConfigData
 */
JNIEXPORT jstring JNICALL Java_com_aonesoft_lib_AoneClient_nativeAoneConfigData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeAllProducts
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeAllProducts
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeAllLangs
 * Signature: ()Ljava/util/Hashtable;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeAllLangs
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeSelectLang
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aonesoft_lib_AoneClient_nativeSelectLang
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeCheckVersion
 * Signature: (LCCCLcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeCheckVersion
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeGetGameVersion
 * Signature: ()Lcom/aonesoft/lib/AoneClient/GameVersion;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeGetGameVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeLogin
 * Signature: (Lcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeLogin
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeOauthLogin
(JNIEnv* , jobject, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeUserID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aonesoft_lib_AoneClient_nativeUserID
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeUserToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_aonesoft_lib_AoneClient_nativeUserToken
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_aonesoft_lib_AoneClient_nativeToken
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeAllGroups
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeAllGroups
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeAllRoles
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeAllRoles
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeAoneAccount
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aonesoft_lib_AoneClient_nativeAoneAccount
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeCreateRole
 * Signature: (Ljava/lang/String;ILjava/util/Hashtable;ILcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeCreateRole
  (JNIEnv *, jobject, jstring, jint, jobject, jint, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeCreateRoleCP
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/util/Hashtable;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aonesoft_lib_AoneClient_nativeCreateRoleCP
  (JNIEnv *, jobject, jstring, jstring, jint, jobject, jstring, jstring, jint);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeSubmitRoleData
 * Signature: (Ljava/lang/String;Ljava/lang/String;I;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeSubmitRoleData
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jboolean, jstring,jlong);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeSelectRoleAndGroup
 * Signature: (IILcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeSelectRoleAndGroup
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativePullGameGroup
 * Signature: (Lcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativePullGameGroup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeGetSelectedRole
 * Signature: ()Lcom/aonesoft/lib/AoneClient/GameRole;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeGetSelectedRole
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeGetSelectedGroup
 * Signature: ()Lcom/aonesoft/lib/AoneClient/GameGroup;
 */
JNIEXPORT jobject JNICALL Java_com_aonesoft_lib_AoneClient_nativeGetSelectedGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativePay
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativePay
  (JNIEnv *, jobject, jstring,jint, jstring, jobject);

/*
 * Class:     com_aonesoft_lib_AoneClient
 * Method:    nativeLogout
 * Signature: (Lcom/aonesoft/lib/AoneResultListener;)V
 */
JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeLogout
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeLogEvent
(JNIEnv* env, jobject thiz, jstring eventId);

JNIEXPORT void JNICALL Java_com_aonesoft_lib_AoneClient_nativeLogEventParams
(JNIEnv* env, jobject thiz, jstring eventId, jobject cpInfo);

#ifdef __cplusplus
}
#endif
#endif
