// File: msg_xx_idcard.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 本文档定义API服务通用协议
// 1700 -- 1999:  API服务(I)


#ifndef _MESSAGE_MSG_XX_IDCARD_H_
#define _MESSAGE_MSG_XX_IDCARD_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"
#include "msg_xx_global.h"

namespace message {

////////////////////////////////////////////////////////////////////////////////
// 实名认证登录请求
// 接口1:http post+json,url路径:/idcard/login.do
// 接口2:aone2协议,协议号:2700
// class IdcardLoginReqBody = 2700
////////////////////////////////////////////////////////////////////////////////
class IdcardLoginReqBody : public Aone2MessageBody
{
public:
	IdcardLoginReqBody();

	virtual ~IdcardLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 实名认证登录回复
// class IdcardLoginRespBody = 2701
////////////////////////////////////////////////////////////////////////////////
class IdcardLoginRespBody : public Aone2MessageBody
{
public:
	IdcardLoginRespBody();

	virtual ~IdcardLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_token;  // 会话标识
	uint32  m_flag;  // 标识
	string  m_date_birth;  // 出生年月日(2021-05-31)
	uint32  m_online_time;  // 今日在线时长
	double  m_pay_amount;  // 本月充值额度
};

////////////////////////////////////////////////////////////////////////////////
// 实名认证登出请求
// 接口1:http post+json,url路径:/idcard/logout.do
// 接口2:aone2协议,协议号:2702
// class IdcardLogoutReqBody = 2702
////////////////////////////////////////////////////////////////////////////////
class IdcardLogoutReqBody : public Aone2MessageBody
{
public:
	IdcardLogoutReqBody();

	virtual ~IdcardLogoutReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 实名认证登出回复
// class IdcardLogoutRespBody = 2703
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody IdcardLogoutRespBody;


////////////////////////////////////////////////////////////////////////////////
// 用户心跳请求(5分钟一次)
// 接口1:http post+json,url路径:/idcard/heart.do
// 接口2:aone2协议,协议号:2704
// class IdcardHeartReqBody = 2704
////////////////////////////////////////////////////////////////////////////////
class IdcardHeartReqBody : public Aone2MessageBody
{
public:
	IdcardHeartReqBody();

	virtual ~IdcardHeartReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_user_id;  // 用户ID
	uint32  m_token;  // 会话标识(登录时获得)
};

////////////////////////////////////////////////////////////////////////////////
// 用户心跳回复
// class IdcardHeartRespBody = 2705
////////////////////////////////////////////////////////////////////////////////
class IdcardHeartRespBody : public Aone2MessageBody
{
public:
	IdcardHeartRespBody();

	virtual ~IdcardHeartRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
	string  m_date_birth;  // 出生年月日(2021-05-31)
	uint32  m_online_time;  // 今日在线时长
	double  m_pay_amount;  // 本月充值额度
};

////////////////////////////////////////////////////////////////////////////////
// 实名认证请求
// 接口1:http post+json,url路径:/idcard/certificate.do
// 接口2:aone2协议,协议号:2720
// class IdcardCertificateReqBody = 2720
////////////////////////////////////////////////////////////////////////////////
class IdcardCertificateReqBody : public Aone2MessageBody
{
public:
	IdcardCertificateReqBody();

	virtual ~IdcardCertificateReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_user_id;  // 用户id
	string  m_real_name;  // 真实姓名
	string  m_identity_number;  // 身份证号
};

////////////////////////////////////////////////////////////////////////////////
// 实名认证回复
// class IdcardCertificateRespBody = 2721
////////////////////////////////////////////////////////////////////////////////
class IdcardCertificateRespBody : public Aone2MessageBody
{
public:
	IdcardCertificateRespBody();

	virtual ~IdcardCertificateRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
	string  m_date_birth;  // 出生年月日
	uint32  m_online_time;  // 今日在线时长
	double  m_pay_amount;  // 本月充值额度
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////
typedef Aone2Request <IdcardLoginReqBody, 2700> IdcardLoginRequest;
typedef Aone2Response<IdcardLoginRespBody, 2701> IdcardLoginResponse;
typedef Aone2Request <IdcardLogoutReqBody, 2702> IdcardLogoutRequest;
typedef Aone2Response<IdcardLogoutRespBody, 2703> IdcardLogoutResponse;
typedef Aone2Request <IdcardHeartReqBody, 2704> IdcardHeartRequest;
typedef Aone2Response<IdcardHeartRespBody, 2705> IdcardHeartResponse;
typedef Aone2Request <IdcardCertificateReqBody, 2720> IdcardCertificateRequest;
typedef Aone2Response<IdcardCertificateRespBody, 2721> IdcardCertificateResponse;


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_IDCARD_H_
