// File: msg_xx_config.cpp
// Auth: generated by auto tool 'lazybone'
// Desc: message define


#include "msg_xx_config.h"
#include "aone2_helper.h"

namespace message {

///////////////////////////////////////////////////////////////////////////////
// class LogInfo
///////////////////////////////////////////////////////////////////////////////
LogInfo::LogInfo()
{
	m_level = 5;
	m_keep_days = 30;
	m_port = 0;
}

LogInfo::~LogInfo()
{
	// empty
}

int LogInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_level
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_level)) return -1;

	// m_keep_days
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_keep_days)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	return msglen;
}

int LogInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_level
	if (!coder.set_uint32(m_level)) return -1;

	// m_keep_days
	if (!coder.set_uint32(m_keep_days)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 LogInfo::calc_length()
{
	uint32 length = 0;

	// m_level
	length += Aone2Coder::size_uint32(m_level);

	// m_keep_days
	length += Aone2Coder::size_uint32(m_keep_days);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ServerInfo
///////////////////////////////////////////////////////////////////////////////
ServerInfo::ServerInfo()
{
	m_port = 0;
}

ServerInfo::~ServerInfo()
{
	// empty
}

int ServerInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_host)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	return msglen;
}

int ServerInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_host
	if (!coder.set_string(m_host)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 ServerInfo::calc_length()
{
	uint32 length = 0;

	// m_host
	length += Aone2Coder::size_string(m_host);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class SecurityServerInfo
///////////////////////////////////////////////////////////////////////////////
SecurityServerInfo::SecurityServerInfo()
{
	m_port = 0;
}

SecurityServerInfo::~SecurityServerInfo()
{
	// empty
}

int SecurityServerInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_host)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	// m_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_key)) return -1;

	return msglen;
}

int SecurityServerInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_host
	if (!coder.set_string(m_host)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	// m_key
	if (!coder.set_string(m_key)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 SecurityServerInfo::calc_length()
{
	uint32 length = 0;

	// m_host
	length += Aone2Coder::size_string(m_host);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	// m_key
	length += Aone2Coder::size_string(m_key);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ListenInfo
///////////////////////////////////////////////////////////////////////////////
ListenInfo::ListenInfo()
{
	m_port = 0;
}

ListenInfo::~ListenInfo()
{
	// empty
}

int ListenInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_ip)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	return msglen;
}

int ListenInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_ip
	if (!coder.set_string(m_ip)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 ListenInfo::calc_length()
{
	uint32 length = 0;

	// m_ip
	length += Aone2Coder::size_string(m_ip);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class SecurityListenInfo
///////////////////////////////////////////////////////////////////////////////
SecurityListenInfo::SecurityListenInfo()
{
	m_port = 0;
}

SecurityListenInfo::~SecurityListenInfo()
{
	// empty
}

int SecurityListenInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_ip
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_ip)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	// m_key
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_key)) return -1;

	return msglen;
}

int SecurityListenInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_ip
	if (!coder.set_string(m_ip)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	// m_key
	if (!coder.set_string(m_key)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 SecurityListenInfo::calc_length()
{
	uint32 length = 0;

	// m_ip
	length += Aone2Coder::size_string(m_ip);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	// m_key
	length += Aone2Coder::size_string(m_key);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class RedisInfo
///////////////////////////////////////////////////////////////////////////////
RedisInfo::RedisInfo()
{
	m_host = "127.0.0.1";
	m_port = 6379;
	m_db = 0;
	m_conn_count = 2;
}

RedisInfo::~RedisInfo()
{
	// empty
}

int RedisInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_host)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	// m_password
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_password)) return -1;

	// m_db
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_db)) return -1;

	// m_conn_count
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_conn_count)) return -1;

	return msglen;
}

int RedisInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_host
	if (!coder.set_string(m_host)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	// m_password
	if (!coder.set_string(m_password)) return -1;

	// m_db
	if (!coder.set_uint32(m_db)) return -1;

	// m_conn_count
	if (!coder.set_uint32(m_conn_count)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 RedisInfo::calc_length()
{
	uint32 length = 0;

	// m_host
	length += Aone2Coder::size_string(m_host);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	// m_password
	length += Aone2Coder::size_string(m_password);

	// m_db
	length += Aone2Coder::size_uint32(m_db);

	// m_conn_count
	length += Aone2Coder::size_uint32(m_conn_count);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class MysqlInfo
///////////////////////////////////////////////////////////////////////////////
MysqlInfo::MysqlInfo()
{
	m_host = "127.0.0.1";
	m_port = 3306;
	m_scheme = "";
	m_name = "";
	m_group = "";
}

MysqlInfo::~MysqlInfo()
{
	// empty
}

int MysqlInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_host)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	// m_user
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_user)) return -1;

	// m_password
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_password)) return -1;

	// m_scheme
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_scheme)) return -1;

	// m_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_name)) return -1;

	// m_group
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_group)) return -1;

	return msglen;
}

int MysqlInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_host
	if (!coder.set_string(m_host)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	// m_user
	if (!coder.set_string(m_user)) return -1;

	// m_password
	if (!coder.set_string(m_password)) return -1;

	// m_scheme
	if (!coder.set_string(m_scheme)) return -1;

	// m_name
	if (!coder.set_string(m_name)) return -1;

	// m_group
	if (!coder.set_string(m_group)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 MysqlInfo::calc_length()
{
	uint32 length = 0;

	// m_host
	length += Aone2Coder::size_string(m_host);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	// m_user
	length += Aone2Coder::size_string(m_user);

	// m_password
	length += Aone2Coder::size_string(m_password);

	// m_scheme
	length += Aone2Coder::size_string(m_scheme);

	// m_name
	length += Aone2Coder::size_string(m_name);

	// m_group
	length += Aone2Coder::size_string(m_group);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class LeveldbInfo
///////////////////////////////////////////////////////////////////////////////
LeveldbInfo::LeveldbInfo()
{
	m_path = "./data/cache";
}

LeveldbInfo::~LeveldbInfo()
{
	// empty
}

int LeveldbInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_path
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_path)) return -1;

	return msglen;
}

int LeveldbInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_path
	if (!coder.set_string(m_path)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 LeveldbInfo::calc_length()
{
	uint32 length = 0;

	// m_path
	length += Aone2Coder::size_string(m_path);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class SMTPInfo
///////////////////////////////////////////////////////////////////////////////
SMTPInfo::SMTPInfo()
{
	m_port = 0;
}

SMTPInfo::~SMTPInfo()
{
	// empty
}

int SMTPInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_host)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	// m_user
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_user)) return -1;

	// m_password
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_password)) return -1;

	return msglen;
}

int SMTPInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_host
	if (!coder.set_string(m_host)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	// m_user
	if (!coder.set_string(m_user)) return -1;

	// m_password
	if (!coder.set_string(m_password)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 SMTPInfo::calc_length()
{
	uint32 length = 0;

	// m_host
	length += Aone2Coder::size_string(m_host);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	// m_user
	length += Aone2Coder::size_string(m_user);

	// m_password
	length += Aone2Coder::size_string(m_password);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ApnsInfo
///////////////////////////////////////////////////////////////////////////////
ApnsInfo::ApnsInfo()
{
	m_appid = 0;
	m_port = 0;
}

ApnsInfo::~ApnsInfo()
{
	// empty
}

int ApnsInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_appid
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_appid)) return -1;

	// m_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_host)) return -1;

	// m_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_port)) return -1;

	// m_cert_file
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_cert_file)) return -1;

	// m_key_file
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_key_file)) return -1;

	return msglen;
}

int ApnsInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_appid
	if (!coder.set_uint32(m_appid)) return -1;

	// m_host
	if (!coder.set_string(m_host)) return -1;

	// m_port
	if (!coder.set_uint16(m_port)) return -1;

	// m_cert_file
	if (!coder.set_string(m_cert_file)) return -1;

	// m_key_file
	if (!coder.set_string(m_key_file)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 ApnsInfo::calc_length()
{
	uint32 length = 0;

	// m_appid
	length += Aone2Coder::size_uint32(m_appid);

	// m_host
	length += Aone2Coder::size_string(m_host);

	// m_port
	length += Aone2Coder::size_uint16(m_port);

	// m_cert_file
	length += Aone2Coder::size_string(m_cert_file);

	// m_key_file
	length += Aone2Coder::size_string(m_key_file);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class ServerConfigInfo
///////////////////////////////////////////////////////////////////////////////
ServerConfigInfo::ServerConfigInfo()
{
	m_server_id = 0;
	m_center_port = 0;
}

ServerConfigInfo::~ServerConfigInfo()
{
	// empty
}

int ServerConfigInfo::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_server_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_server_id)) return -1;

	// m_password
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_password)) return -1;

	// m_center_host
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_center_host)) return -1;

	// m_center_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_center_port)) return -1;

	return msglen;
}

int ServerConfigInfo::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_server_id
	if (!coder.set_uint32(m_server_id)) return -1;

	// m_password
	if (!coder.set_string(m_password)) return -1;

	// m_center_host
	if (!coder.set_string(m_center_host)) return -1;

	// m_center_port
	if (!coder.set_uint32(m_center_port)) return -1;

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 ServerConfigInfo::calc_length()
{
	uint32 length = 0;

	// m_server_id
	length += Aone2Coder::size_uint32(m_server_id);

	// m_password
	length += Aone2Coder::size_string(m_password);

	// m_center_host
	length += Aone2Coder::size_string(m_center_host);

	// m_center_port
	length += Aone2Coder::size_uint32(m_center_port);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_CenterServer
///////////////////////////////////////////////////////////////////////////////
Config_CenterServer::Config_CenterServer()
{
	m_aone_listen_port = 8899;
	m_http_listen_port = 8000;
}

Config_CenterServer::~Config_CenterServer()
{
	// empty
}

int Config_CenterServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_aone_listen_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_aone_listen_port)) return -1;

	// m_http_listen_port
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_http_listen_port)) return -1;

	// m_log
	if (decoder.remain() == 0) return msglen;
	int log_ret = m_log.parse_bytes(decoder.position(), decoder.remain());
	if (log_ret <= 0) return log_ret;
	if (!decoder.set_pos(decoder.position() + log_ret)) return -1;

	// m_db
	if (decoder.remain() == 0) return msglen;
	int db_ret = m_db.parse_bytes(decoder.position(), decoder.remain());
	if (db_ret <= 0) return db_ret;
	if (!decoder.set_pos(decoder.position() + db_ret)) return -1;

	return msglen;
}

int Config_CenterServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_aone_listen_port
	if (!coder.set_uint16(m_aone_listen_port)) return -1;

	// m_http_listen_port
	if (!coder.set_uint16(m_http_listen_port)) return -1;

	// m_log
	int log_ret = m_log.to_bytes(coder.position(), coder.remain());
	if (log_ret <= 0) return log_ret;
	coder.set_pos(coder.position() + log_ret);

	// m_db
	int db_ret = m_db.to_bytes(coder.position(), coder.remain());
	if (db_ret <= 0) return db_ret;
	coder.set_pos(coder.position() + db_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_CenterServer::calc_length()
{
	uint32 length = 0;

	// m_aone_listen_port
	length += Aone2Coder::size_uint16(m_aone_listen_port);

	// m_http_listen_port
	length += Aone2Coder::size_uint16(m_http_listen_port);

	// m_log
	length += m_log.calc_length();

	// m_db
	length += m_db.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_ApiRecordServer
///////////////////////////////////////////////////////////////////////////////
Config_ApiRecordServer::Config_ApiRecordServer()
{
	// empty
}

Config_ApiRecordServer::~Config_ApiRecordServer()
{
	// empty
}

int Config_ApiRecordServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_mysql_info
	if (decoder.remain() == 0) return msglen;
	int mysql_info_ret = m_mysql_info.parse_bytes(decoder.position(), decoder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	if (!decoder.set_pos(decoder.position() + mysql_info_ret)) return -1;

	// m_leveldb_info
	if (decoder.remain() == 0) return msglen;
	int leveldb_info_ret = m_leveldb_info.parse_bytes(decoder.position(), decoder.remain());
	if (leveldb_info_ret <= 0) return leveldb_info_ret;
	if (!decoder.set_pos(decoder.position() + leveldb_info_ret)) return -1;

	// m_api_server
	if (decoder.remain() == 0) return msglen;
	int api_server_ret = m_api_server.parse_bytes(decoder.position(), decoder.remain());
	if (api_server_ret <= 0) return api_server_ret;
	if (!decoder.set_pos(decoder.position() + api_server_ret)) return -1;

	return msglen;
}

int Config_ApiRecordServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_mysql_info
	int mysql_info_ret = m_mysql_info.to_bytes(coder.position(), coder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	coder.set_pos(coder.position() + mysql_info_ret);

	// m_leveldb_info
	int leveldb_info_ret = m_leveldb_info.to_bytes(coder.position(), coder.remain());
	if (leveldb_info_ret <= 0) return leveldb_info_ret;
	coder.set_pos(coder.position() + leveldb_info_ret);

	// m_api_server
	int api_server_ret = m_api_server.to_bytes(coder.position(), coder.remain());
	if (api_server_ret <= 0) return api_server_ret;
	coder.set_pos(coder.position() + api_server_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_ApiRecordServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_mysql_info
	length += m_mysql_info.calc_length();

	// m_leveldb_info
	length += m_leveldb_info.calc_length();

	// m_api_server
	length += m_api_server.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_ApiServer
///////////////////////////////////////////////////////////////////////////////
Config_ApiServer::Config_ApiServer()
{
	// empty
}

Config_ApiServer::~Config_ApiServer()
{
	// empty
}

int Config_ApiServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_listen_http
	if (decoder.remain() == 0) return msglen;
	int listen_http_ret = m_listen_http.parse_bytes(decoder.position(), decoder.remain());
	if (listen_http_ret <= 0) return listen_http_ret;
	if (!decoder.set_pos(decoder.position() + listen_http_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_mysql_info
	if (decoder.remain() == 0) return msglen;
	int mysql_info_ret = m_mysql_info.parse_bytes(decoder.position(), decoder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	if (!decoder.set_pos(decoder.position() + mysql_info_ret)) return -1;

	// m_redis_infos
	if (decoder.remain() == 0) return msglen;
	uint32 redis_infos_count = 0;
	if (!decoder.get_uint32(redis_infos_count)) return -1;
	for(uint32 i = 0; i < redis_infos_count; i++)
	{
		m_redis_infos.push_back(RedisInfo());
		RedisInfo& redis_infos_ = m_redis_infos.back();
		int redis_infos_ret = redis_infos_.parse_bytes(decoder.position(), decoder.remain());
		if (redis_infos_ret <= 0) return redis_infos_ret;
		if (!decoder.set_pos(decoder.position() + redis_infos_ret)) return -1;
	}

	// m_account_servers
	if (decoder.remain() == 0) return msglen;
	uint32 account_servers_count = 0;
	if (!decoder.get_uint32(account_servers_count)) return -1;
	for(uint32 i = 0; i < account_servers_count; i++)
	{
		m_account_servers.push_back(SecurityServerInfo());
		SecurityServerInfo& account_servers_ = m_account_servers.back();
		int account_servers_ret = account_servers_.parse_bytes(decoder.position(), decoder.remain());
		if (account_servers_ret <= 0) return account_servers_ret;
		if (!decoder.set_pos(decoder.position() + account_servers_ret)) return -1;
	}

	// m_sms_server
	if (decoder.remain() == 0) return msglen;
	int sms_server_ret = m_sms_server.parse_bytes(decoder.position(), decoder.remain());
	if (sms_server_ret <= 0) return sms_server_ret;
	if (!decoder.set_pos(decoder.position() + sms_server_ret)) return -1;

	// m_mail_server
	if (decoder.remain() == 0) return msglen;
	int mail_server_ret = m_mail_server.parse_bytes(decoder.position(), decoder.remain());
	if (mail_server_ret <= 0) return mail_server_ret;
	if (!decoder.set_pos(decoder.position() + mail_server_ret)) return -1;

	// m_push_server
	if (decoder.remain() == 0) return msglen;
	int push_server_ret = m_push_server.parse_bytes(decoder.position(), decoder.remain());
	if (push_server_ret <= 0) return push_server_ret;
	if (!decoder.set_pos(decoder.position() + push_server_ret)) return -1;

	// m_record_server
	if (decoder.remain() == 0) return msglen;
	int record_server_ret = m_record_server.parse_bytes(decoder.position(), decoder.remain());
	if (record_server_ret <= 0) return record_server_ret;
	if (!decoder.set_pos(decoder.position() + record_server_ret)) return -1;

	// m_datacenter_server
	if (decoder.remain() == 0) return msglen;
	int datacenter_server_ret = m_datacenter_server.parse_bytes(decoder.position(), decoder.remain());
	if (datacenter_server_ret <= 0) return datacenter_server_ret;
	if (!decoder.set_pos(decoder.position() + datacenter_server_ret)) return -1;

	return msglen;
}

int Config_ApiServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_listen_http
	int listen_http_ret = m_listen_http.to_bytes(coder.position(), coder.remain());
	if (listen_http_ret <= 0) return listen_http_ret;
	coder.set_pos(coder.position() + listen_http_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_mysql_info
	int mysql_info_ret = m_mysql_info.to_bytes(coder.position(), coder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	coder.set_pos(coder.position() + mysql_info_ret);

	// m_redis_infos
	if (!coder.set_uint32(m_redis_infos.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_redis_infos.size(); i++)
	{
		int redis_infos_ret = m_redis_infos[i].to_bytes(coder.position(), coder.remain());
		if (redis_infos_ret <= 0) return redis_infos_ret;
		coder.set_pos(coder.position() + redis_infos_ret);
	}

	// m_account_servers
	if (!coder.set_uint32(m_account_servers.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_account_servers.size(); i++)
	{
		int account_servers_ret = m_account_servers[i].to_bytes(coder.position(), coder.remain());
		if (account_servers_ret <= 0) return account_servers_ret;
		coder.set_pos(coder.position() + account_servers_ret);
	}

	// m_sms_server
	int sms_server_ret = m_sms_server.to_bytes(coder.position(), coder.remain());
	if (sms_server_ret <= 0) return sms_server_ret;
	coder.set_pos(coder.position() + sms_server_ret);

	// m_mail_server
	int mail_server_ret = m_mail_server.to_bytes(coder.position(), coder.remain());
	if (mail_server_ret <= 0) return mail_server_ret;
	coder.set_pos(coder.position() + mail_server_ret);

	// m_push_server
	int push_server_ret = m_push_server.to_bytes(coder.position(), coder.remain());
	if (push_server_ret <= 0) return push_server_ret;
	coder.set_pos(coder.position() + push_server_ret);

	// m_record_server
	int record_server_ret = m_record_server.to_bytes(coder.position(), coder.remain());
	if (record_server_ret <= 0) return record_server_ret;
	coder.set_pos(coder.position() + record_server_ret);

	// m_datacenter_server
	int datacenter_server_ret = m_datacenter_server.to_bytes(coder.position(), coder.remain());
	if (datacenter_server_ret <= 0) return datacenter_server_ret;
	coder.set_pos(coder.position() + datacenter_server_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_ApiServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_listen_http
	length += m_listen_http.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_mysql_info
	length += m_mysql_info.calc_length();

	// m_redis_infos
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_redis_infos.size(); i++)
	{
		length += m_redis_infos[i].calc_length();
	}

	// m_account_servers
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_account_servers.size(); i++)
	{
		length += m_account_servers[i].calc_length();
	}

	// m_sms_server
	length += m_sms_server.calc_length();

	// m_mail_server
	length += m_mail_server.calc_length();

	// m_push_server
	length += m_push_server.calc_length();

	// m_record_server
	length += m_record_server.calc_length();

	// m_datacenter_server
	length += m_datacenter_server.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_PayServer
///////////////////////////////////////////////////////////////////////////////
Config_PayServer::Config_PayServer()
{
	// empty
}

Config_PayServer::~Config_PayServer()
{
	// empty
}

int Config_PayServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_listen_http
	if (decoder.remain() == 0) return msglen;
	int listen_http_ret = m_listen_http.parse_bytes(decoder.position(), decoder.remain());
	if (listen_http_ret <= 0) return listen_http_ret;
	if (!decoder.set_pos(decoder.position() + listen_http_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_mysql_info
	if (decoder.remain() == 0) return msglen;
	int mysql_info_ret = m_mysql_info.parse_bytes(decoder.position(), decoder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	if (!decoder.set_pos(decoder.position() + mysql_info_ret)) return -1;

	// m_leveldb_info
	if (decoder.remain() == 0) return msglen;
	int leveldb_info_ret = m_leveldb_info.parse_bytes(decoder.position(), decoder.remain());
	if (leveldb_info_ret <= 0) return leveldb_info_ret;
	if (!decoder.set_pos(decoder.position() + leveldb_info_ret)) return -1;

	// m_record_server
	if (decoder.remain() == 0) return msglen;
	int record_server_ret = m_record_server.parse_bytes(decoder.position(), decoder.remain());
	if (record_server_ret <= 0) return record_server_ret;
	if (!decoder.set_pos(decoder.position() + record_server_ret)) return -1;

	return msglen;
}

int Config_PayServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_listen_http
	int listen_http_ret = m_listen_http.to_bytes(coder.position(), coder.remain());
	if (listen_http_ret <= 0) return listen_http_ret;
	coder.set_pos(coder.position() + listen_http_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_mysql_info
	int mysql_info_ret = m_mysql_info.to_bytes(coder.position(), coder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	coder.set_pos(coder.position() + mysql_info_ret);

	// m_leveldb_info
	int leveldb_info_ret = m_leveldb_info.to_bytes(coder.position(), coder.remain());
	if (leveldb_info_ret <= 0) return leveldb_info_ret;
	coder.set_pos(coder.position() + leveldb_info_ret);

	// m_record_server
	int record_server_ret = m_record_server.to_bytes(coder.position(), coder.remain());
	if (record_server_ret <= 0) return record_server_ret;
	coder.set_pos(coder.position() + record_server_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_PayServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_listen_http
	length += m_listen_http.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_mysql_info
	length += m_mysql_info.calc_length();

	// m_leveldb_info
	length += m_leveldb_info.calc_length();

	// m_record_server
	length += m_record_server.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_AccountServer
///////////////////////////////////////////////////////////////////////////////
Config_AccountServer::Config_AccountServer()
{
	// empty
}

Config_AccountServer::~Config_AccountServer()
{
	// empty
}

int Config_AccountServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_mysql_info
	if (decoder.remain() == 0) return msglen;
	int mysql_info_ret = m_mysql_info.parse_bytes(decoder.position(), decoder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	if (!decoder.set_pos(decoder.position() + mysql_info_ret)) return -1;

	// m_redis_infos
	if (decoder.remain() == 0) return msglen;
	uint32 redis_infos_count = 0;
	if (!decoder.get_uint32(redis_infos_count)) return -1;
	for(uint32 i = 0; i < redis_infos_count; i++)
	{
		m_redis_infos.push_back(RedisInfo());
		RedisInfo& redis_infos_ = m_redis_infos.back();
		int redis_infos_ret = redis_infos_.parse_bytes(decoder.position(), decoder.remain());
		if (redis_infos_ret <= 0) return redis_infos_ret;
		if (!decoder.set_pos(decoder.position() + redis_infos_ret)) return -1;
	}

	// m_leveldb_info
	if (decoder.remain() == 0) return msglen;
	int leveldb_info_ret = m_leveldb_info.parse_bytes(decoder.position(), decoder.remain());
	if (leveldb_info_ret <= 0) return leveldb_info_ret;
	if (!decoder.set_pos(decoder.position() + leveldb_info_ret)) return -1;

	// m_record_server
	if (decoder.remain() == 0) return msglen;
	int record_server_ret = m_record_server.parse_bytes(decoder.position(), decoder.remain());
	if (record_server_ret <= 0) return record_server_ret;
	if (!decoder.set_pos(decoder.position() + record_server_ret)) return -1;

	return msglen;
}

int Config_AccountServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_mysql_info
	int mysql_info_ret = m_mysql_info.to_bytes(coder.position(), coder.remain());
	if (mysql_info_ret <= 0) return mysql_info_ret;
	coder.set_pos(coder.position() + mysql_info_ret);

	// m_redis_infos
	if (!coder.set_uint32(m_redis_infos.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_redis_infos.size(); i++)
	{
		int redis_infos_ret = m_redis_infos[i].to_bytes(coder.position(), coder.remain());
		if (redis_infos_ret <= 0) return redis_infos_ret;
		coder.set_pos(coder.position() + redis_infos_ret);
	}

	// m_leveldb_info
	int leveldb_info_ret = m_leveldb_info.to_bytes(coder.position(), coder.remain());
	if (leveldb_info_ret <= 0) return leveldb_info_ret;
	coder.set_pos(coder.position() + leveldb_info_ret);

	// m_record_server
	int record_server_ret = m_record_server.to_bytes(coder.position(), coder.remain());
	if (record_server_ret <= 0) return record_server_ret;
	coder.set_pos(coder.position() + record_server_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_AccountServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_mysql_info
	length += m_mysql_info.calc_length();

	// m_redis_infos
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_redis_infos.size(); i++)
	{
		length += m_redis_infos[i].calc_length();
	}

	// m_leveldb_info
	length += m_leveldb_info.calc_length();

	// m_record_server
	length += m_record_server.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_MailServer
///////////////////////////////////////////////////////////////////////////////
Config_MailServer::Config_MailServer()
{
	// empty
}

Config_MailServer::~Config_MailServer()
{
	// empty
}

int Config_MailServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_redis_info
	if (decoder.remain() == 0) return msglen;
	int redis_info_ret = m_redis_info.parse_bytes(decoder.position(), decoder.remain());
	if (redis_info_ret <= 0) return redis_info_ret;
	if (!decoder.set_pos(decoder.position() + redis_info_ret)) return -1;

	// m_smtp_info
	if (decoder.remain() == 0) return msglen;
	int smtp_info_ret = m_smtp_info.parse_bytes(decoder.position(), decoder.remain());
	if (smtp_info_ret <= 0) return smtp_info_ret;
	if (!decoder.set_pos(decoder.position() + smtp_info_ret)) return -1;

	return msglen;
}

int Config_MailServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_redis_info
	int redis_info_ret = m_redis_info.to_bytes(coder.position(), coder.remain());
	if (redis_info_ret <= 0) return redis_info_ret;
	coder.set_pos(coder.position() + redis_info_ret);

	// m_smtp_info
	int smtp_info_ret = m_smtp_info.to_bytes(coder.position(), coder.remain());
	if (smtp_info_ret <= 0) return smtp_info_ret;
	coder.set_pos(coder.position() + smtp_info_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_MailServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_redis_info
	length += m_redis_info.calc_length();

	// m_smtp_info
	length += m_smtp_info.calc_length();

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_PushServer
///////////////////////////////////////////////////////////////////////////////
Config_PushServer::Config_PushServer()
{
	m_apns_production = 0;
}

Config_PushServer::~Config_PushServer()
{
	// empty
}

int Config_PushServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_redis_info
	if (decoder.remain() == 0) return msglen;
	int redis_info_ret = m_redis_info.parse_bytes(decoder.position(), decoder.remain());
	if (redis_info_ret <= 0) return redis_info_ret;
	if (!decoder.set_pos(decoder.position() + redis_info_ret)) return -1;

	// m_apns_production
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint16(m_apns_production)) return -1;

	// m_apns
	if (decoder.remain() == 0) return msglen;
	uint32 apns_count = 0;
	if (!decoder.get_uint32(apns_count)) return -1;
	for(uint32 i = 0; i < apns_count; i++)
	{
		m_apns.push_back(ApnsInfo());
		ApnsInfo& apns_ = m_apns.back();
		int apns_ret = apns_.parse_bytes(decoder.position(), decoder.remain());
		if (apns_ret <= 0) return apns_ret;
		if (!decoder.set_pos(decoder.position() + apns_ret)) return -1;
	}

	return msglen;
}

int Config_PushServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_redis_info
	int redis_info_ret = m_redis_info.to_bytes(coder.position(), coder.remain());
	if (redis_info_ret <= 0) return redis_info_ret;
	coder.set_pos(coder.position() + redis_info_ret);

	// m_apns_production
	if (!coder.set_uint16(m_apns_production)) return -1;

	// m_apns
	if (!coder.set_uint32(m_apns.size())) return -1;
	for(uint32 i = 0; i < (uint32)m_apns.size(); i++)
	{
		int apns_ret = m_apns[i].to_bytes(coder.position(), coder.remain());
		if (apns_ret <= 0) return apns_ret;
		coder.set_pos(coder.position() + apns_ret);
	}

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_PushServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_redis_info
	length += m_redis_info.calc_length();

	// m_apns_production
	length += Aone2Coder::size_uint16(m_apns_production);

	// m_apns
	length += sizeof(uint32);
	for(uint32 i = 0; i < m_apns.size(); i++)
	{
		length += m_apns[i].calc_length();
	}

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class Config_SmsServer
///////////////////////////////////////////////////////////////////////////////
Config_SmsServer::Config_SmsServer()
{
	// empty
}

Config_SmsServer::~Config_SmsServer()
{
	// empty
}

int Config_SmsServer::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen;
	memcpy(&msglen, src, sizeof(uint32));
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_listen_aone_rc4
	if (decoder.remain() == 0) return msglen;
	int listen_aone_rc4_ret = m_listen_aone_rc4.parse_bytes(decoder.position(), decoder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	if (!decoder.set_pos(decoder.position() + listen_aone_rc4_ret)) return -1;

	// m_log_info
	if (decoder.remain() == 0) return msglen;
	int log_info_ret = m_log_info.parse_bytes(decoder.position(), decoder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	if (!decoder.set_pos(decoder.position() + log_info_ret)) return -1;

	// m_redis_info
	if (decoder.remain() == 0) return msglen;
	int redis_info_ret = m_redis_info.parse_bytes(decoder.position(), decoder.remain());
	if (redis_info_ret <= 0) return redis_info_ret;
	if (!decoder.set_pos(decoder.position() + redis_info_ret)) return -1;

	return msglen;
}

int Config_SmsServer::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_listen_aone_rc4
	int listen_aone_rc4_ret = m_listen_aone_rc4.to_bytes(coder.position(), coder.remain());
	if (listen_aone_rc4_ret <= 0) return listen_aone_rc4_ret;
	coder.set_pos(coder.position() + listen_aone_rc4_ret);

	// m_log_info
	int log_info_ret = m_log_info.to_bytes(coder.position(), coder.remain());
	if (log_info_ret <= 0) return log_info_ret;
	coder.set_pos(coder.position() + log_info_ret);

	// m_redis_info
	int redis_info_ret = m_redis_info.to_bytes(coder.position(), coder.remain());
	if (redis_info_ret <= 0) return redis_info_ret;
	coder.set_pos(coder.position() + redis_info_ret);

	uint32 l = (coder.position() - dst);
	memcpy(dst, &l, sizeof(uint32));
	return l;
}

uint32 Config_SmsServer::calc_length()
{
	uint32 length = 0;

	// m_listen_aone_rc4
	length += m_listen_aone_rc4.calc_length();

	// m_log_info
	length += m_log_info.calc_length();

	// m_redis_info
	length += m_redis_info.calc_length();

	return length + sizeof(uint32);
}


////////////////////////////////////////////////////////////////////////////////
// message register
////////////////////////////////////////////////////////////////////////////////


}//namespace message

