// File: msg_xx_config.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 中心服务配置


#ifndef _MESSAGE_MSG_XX_CONFIG_H_
#define _MESSAGE_MSG_XX_CONFIG_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"

namespace message {

////////////////////////////////////////////////////////////////////////////////
// 日志系统信息
// class LogInfo
////////////////////////////////////////////////////////////////////////////////
class LogInfo : public Aone2MessageBody
{
public:
	LogInfo();

	virtual ~LogInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_level;  // 日志级别(level 0:none, 1:crash, 2:error, 3:warning, 4:notice, 5:info, 6:debug, 7:trace)
	uint32  m_keep_days;  // 日志保留天数
	uint16  m_port;  // 监听端口(0表示不监听)
};

////////////////////////////////////////////////////////////////////////////////
// 服务信息
// class ServerInfo
////////////////////////////////////////////////////////////////////////////////
class ServerInfo : public Aone2MessageBody
{
public:
	ServerInfo();

	virtual ~ServerInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_host;  // 服务地址或IP
	uint16  m_port;  // 服务监听端口
};

////////////////////////////////////////////////////////////////////////////////
// (安全通信)服务信息
// class SecurityServerInfo
////////////////////////////////////////////////////////////////////////////////
class SecurityServerInfo : public Aone2MessageBody
{
public:
	SecurityServerInfo();

	virtual ~SecurityServerInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_host;  // 服务地址或IP
	uint16  m_port;  // 服务监听端口
	string  m_key;  // RC4加密key
};

////////////////////////////////////////////////////////////////////////////////
// 监听信息
// class ListenInfo
////////////////////////////////////////////////////////////////////////////////
class ListenInfo : public Aone2MessageBody
{
public:
	ListenInfo();

	virtual ~ListenInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_ip;  // 监听IP(若监听本机所有IP则置为空)
	uint16  m_port;  // 监听端口
};

////////////////////////////////////////////////////////////////////////////////
// (安全通信)监听信息
// class SecurityListenInfo
////////////////////////////////////////////////////////////////////////////////
class SecurityListenInfo : public Aone2MessageBody
{
public:
	SecurityListenInfo();

	virtual ~SecurityListenInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_ip;  // 监听IP(若监听本机所有IP则置为空)
	uint16  m_port;  // 监听端口
	string  m_key;  // RC4加密key
};

////////////////////////////////////////////////////////////////////////////////
// redis数据库信息
// class RedisInfo
////////////////////////////////////////////////////////////////////////////////
class RedisInfo : public Aone2MessageBody
{
public:
	RedisInfo();

	virtual ~RedisInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_host;  // 主机或IP
	uint16  m_port;  // 端口
	string  m_password;  // redis数据库密码
	uint32  m_db;  // 选择的库
	uint32  m_conn_count;  // 与redis保持连接数
};

////////////////////////////////////////////////////////////////////////////////
// mysql数据库信息
// class MysqlInfo
////////////////////////////////////////////////////////////////////////////////
class MysqlInfo : public Aone2MessageBody
{
public:
	MysqlInfo();

	virtual ~MysqlInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_host;  // 主机或IP
	uint16  m_port;  // 端口
	string  m_user;  // 用户名
	string  m_password;  // 密码
	string  m_scheme;  // 选择库
	string  m_name;  // 该库名字(库名字不要重复)
	string  m_group;  // 该库所属分组(用于作集群负载)
};

////////////////////////////////////////////////////////////////////////////////
// leveldb数据库信息
// class LeveldbInfo
////////////////////////////////////////////////////////////////////////////////
class LeveldbInfo : public Aone2MessageBody
{
public:
	LeveldbInfo();

	virtual ~LeveldbInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_path;  // 存储路径
};

////////////////////////////////////////////////////////////////////////////////
// SMTP服务配置
// class SMTPInfo
////////////////////////////////////////////////////////////////////////////////
class SMTPInfo : public Aone2MessageBody
{
public:
	SMTPInfo();

	virtual ~SMTPInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_host;  // smtp服务主机域名或IP
	uint16  m_port;  // smtp服务监听端口
	string  m_user;  // 登陆账号(邮件地址)
	string  m_password;  // 登陆密码
};

////////////////////////////////////////////////////////////////////////////////
// APNS服务配置
// class ApnsInfo
////////////////////////////////////////////////////////////////////////////////
class ApnsInfo : public Aone2MessageBody
{
public:
	ApnsInfo();

	virtual ~ApnsInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_appid;  // 本配置对应的应用ID
	string  m_host;  // apns主机域名或IP (测试：gateway.sandbox.push.apple.com)
	uint16  m_port;  // apns服务监听端口 (测试：2195)
	string  m_cert_file;  // 公钥文件本地路径(pem格式)
	string  m_key_file;  // 公钥key文件本地路径(pem格式)
};

////////////////////////////////////////////////////////////////////////////////
// 除中心外其他服务的配置信息
// class ServerConfigInfo
////////////////////////////////////////////////////////////////////////////////
class ServerConfigInfo : public Aone2MessageBody
{
public:
	ServerConfigInfo();

	virtual ~ServerConfigInfo();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_server_id;  // 服务ID
	string  m_password;  // 服务向中心验证密码
	string  m_center_host;  // 中心地址
	uint32  m_center_port;  // 中心监听地址
};

////////////////////////////////////////////////////////////////////////////////
// 中心服配置信息
// class Config_CenterServer
////////////////////////////////////////////////////////////////////////////////
class Config_CenterServer : public Aone2MessageBody
{
public:
	Config_CenterServer();

	virtual ~Config_CenterServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint16  m_aone_listen_port;  // Aone协议对外监听端口
	uint16  m_http_listen_port;  // HTTP协议对外监听端口
	LogInfo  m_log;  // 日志系统配置
	RedisInfo  m_db;  // redis数据库配置
};

////////////////////////////////////////////////////////////////////////////////
// apirecordserver配置
// class Config_ApiRecordServer
////////////////////////////////////////////////////////////////////////////////
class Config_ApiRecordServer : public Aone2MessageBody
{
public:
	Config_ApiRecordServer();

	virtual ~Config_ApiRecordServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	LogInfo  m_log_info;  // 日志系统配置
	MysqlInfo  m_mysql_info;  // mysql数据库配置
	LeveldbInfo  m_leveldb_info;  // leveldb数据库配置
	ServerInfo  m_api_server;  // api服http地址信息
};

////////////////////////////////////////////////////////////////////////////////
// apiserver配置
// class Config_ApiServer
////////////////////////////////////////////////////////////////////////////////
class Config_ApiServer : public Aone2MessageBody
{
public:
	Config_ApiServer();

	virtual ~Config_ApiServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	ListenInfo  m_listen_http;  // Http协议监听
	LogInfo  m_log_info;  // 日志系统配置
	MysqlInfo  m_mysql_info;  // mysql数据库配置
	vector<RedisInfo>  m_redis_infos;  // Redis数据库列表
	vector<SecurityServerInfo>  m_account_servers;  // 账号服务列表
	SecurityServerInfo  m_sms_server;  // 短信服务
	SecurityServerInfo  m_mail_server;  // 邮件服务
	SecurityServerInfo  m_push_server;  // 推送服务
	SecurityServerInfo  m_record_server;  // 日志服务
	ServerConfigInfo  m_datacenter_server;  //数据中心服务
};

////////////////////////////////////////////////////////////////////////////////
// 支付服务(payserver)配置
// class Config_PayServer
////////////////////////////////////////////////////////////////////////////////
class Config_PayServer : public Aone2MessageBody
{
public:
	Config_PayServer();

	virtual ~Config_PayServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	ListenInfo  m_listen_http;  // Http协议监听
	LogInfo  m_log_info;  // 日志系统配置
	MysqlInfo  m_mysql_info;  // mysql数据库配置
	LeveldbInfo  m_leveldb_info;  // leveldb数据库配置
	SecurityServerInfo  m_record_server;  // 日志服务
};

////////////////////////////////////////////////////////////////////////////////
// 账号服务(accountserver)配置
// class Config_AccountServer
////////////////////////////////////////////////////////////////////////////////
class Config_AccountServer : public Aone2MessageBody
{
public:
	Config_AccountServer();

	virtual ~Config_AccountServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	LogInfo  m_log_info;  // 日志系统配置
	MysqlInfo  m_mysql_info;  // mysql数据库配置
	vector<RedisInfo>  m_redis_infos;  // Redis数据库配置
	LeveldbInfo  m_leveldb_info;  // leveldb数据库配置
	SecurityServerInfo  m_record_server;  // 日志服务
};

////////////////////////////////////////////////////////////////////////////////
// 邮件服务(sendserver)配置
// class Config_MailServer
////////////////////////////////////////////////////////////////////////////////
class Config_MailServer : public Aone2MessageBody
{
public:
	Config_MailServer();

	virtual ~Config_MailServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	LogInfo  m_log_info;  // 日志系统配置
	RedisInfo  m_redis_info;  // redis数据库配置
	SMTPInfo  m_smtp_info;  // SMTP服务信息
};

////////////////////////////////////////////////////////////////////////////////
// 推送服务(pushserver)配置
// class Config_PushServer
////////////////////////////////////////////////////////////////////////////////
class Config_PushServer : public Aone2MessageBody
{
public:
	Config_PushServer();

	virtual ~Config_PushServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	LogInfo  m_log_info;  // 日志系统配置
	RedisInfo  m_redis_info;  // redis数据库配置
	uint16  m_apns_production;  //0 ios生产环境,1 ios开发环境
	vector<ApnsInfo>  m_apns;  // apns列表
};

////////////////////////////////////////////////////////////////////////////////
// 短信服务(smsserver)配置
// class Config_SmsServer
////////////////////////////////////////////////////////////////////////////////
class Config_SmsServer : public Aone2MessageBody
{
public:
	Config_SmsServer();

	virtual ~Config_SmsServer();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	SecurityListenInfo  m_listen_aone_rc4;  // Aone协议RC4加密监听
	LogInfo  m_log_info;  // 日志系统配置
	RedisInfo  m_redis_info;  // redis数据库配置
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_CONFIG_H_
