// File: msg_xx_apiserver.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 本文档定义API服务通用协议
// 1700 -- 1999:  API服务(I)
// auth_key算法。
// 首字母为标志位，表示使用哪种加密算法。目前传'A'
//
// 算法AuthKeyA()密码加密传输算法
// 1. 把用户密码做32位MD5计算，得到32位字符串1，并转换为大写得到字符串2。
// 2. 在'0'~'9'和'A'~'F'中随机生成两个字符，替换字符串2第0和第31两个字符，得到字符串3。
// 3. 对字符串3再做一次32位MD5计算得到字符串4，并转换为大写得到字符串5。
// 4. 使用刚得到的两个随机值分别替换字符串5的第0和第31两个字符，得到字符串6。
// 5. 'A'与字符串6连接即为验证码(auth_key)。
//
// 对于aone2协议接口的 auth_key = AuthKeyA(device_id + appkey)
//
// 对于http协议接口的 sign = md5(http_body + appkey)转小写
//
// 请求频率限制策略????
//
// HTTP协议统一用http post方法,消息头Content-Type设为application/json,消息体为json字符串
// 所有url地址后面均需要添加serverid和sign参数，sign参数的计算方法：sign = md5(http消息体+appkey)转为小写字母
// http请求消息body: 消息体序列化为json即可
// http回复消息body: {"retcode":xxxx,"retmsg":"xxxxxx","body":{......}}
//                   其中省略的部分为消息体序列化后的json;当retcode为非0时body部分为空json对象{}
// HTTP连接优化方案：http协议连接复用，API服不主动关闭连接，由请求服务自主决定。
// 推送渠道编码定义
// push_ios_apns
// push_ios_baidu
// push_ios_jiguang
// push_ios_xinge
// push_android_gcm
// push_android_baidu
// push_android_jiguang
// push_android_xinge
// push_wp_mpns
// push_wp_jiguang
// 推送风格定义
// low: 最安静，最温和的表现
// medium: 一般的，默认的表现
// high: 最显眼，最丰富的表现


#ifndef _MESSAGE_MSG_XX_APISERVER_H_
#define _MESSAGE_MSG_XX_APISERVER_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"
#include "msg_xx_global.h"
#include "msg_xx_error.h"

namespace message {

////////////////////////////////////////////////////////////////////////////////
// (临时设备账号)快速登陆请求
// 接口1: http post + json，url路径：/api/quick_login.do
// 接口2: aone2协议，协议号：1700
// class QuickLoginReqBody = 1700
////////////////////////////////////////////////////////////////////////////////
class QuickLoginReqBody : public Aone2MessageBody
{
public:
	QuickLoginReqBody();

	virtual ~QuickLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVer方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// (临时设备账号)快速登陆回复
// class QuickLoginRespBody = 1701
////////////////////////////////////////////////////////////////////////////////
class QuickLoginRespBody : public Aone2MessageBody
{
public:
	QuickLoginRespBody();

	virtual ~QuickLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_user_account;  // (本平台)用户账号名
	string  m_aone_account;  // 设备绑定的Aone账号(没有置空)
	string  m_token;  // (本平台)用户身份验证码(若已绑定过Aone账号，则返回无效的空token)
};

////////////////////////////////////////////////////////////////////////////////
// 各类第三方SDK登陆请求
// 超时时间酌情设置大一些>=10秒
// 第一次登陆自动生成注册
// class SDKLoginReqBody = 1702
////////////////////////////////////////////////////////////////////////////////
class SDKLoginReqBody : public Aone2MessageBody
{
public:
	SDKLoginReqBody();

	virtual ~SDKLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_sdk_userid;  // (第三方平台返回的)用户ID(没有则置空)
	string  m_sdk_token;  // (第三方返回的)用户验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
	string  m_sdk_version;  // 第三方sdk版本(类似于"1.2.3"或"2.3"，防止第三方SDK不兼容升级)
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVer方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// 各类第三方SDK登陆回复
// class SDKLoginRespBody = 1703
////////////////////////////////////////////////////////////////////////////////
class SDKLoginRespBody : public Aone2MessageBody
{
public:
	SDKLoginRespBody();

	virtual ~SDKLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_user_account;  // (本平台)用户账号名
	string  m_token;  // (本平台)用户身份验证码
	string  m_ext;  // 需要回传sdk的数据
};

////////////////////////////////////////////////////////////////////////////////
// 各类开放平台登陆请求
// 采用OAuth2.0协议
// 第一次登陆自动生成注册
// class OAuthLoginReqBody = 1704
////////////////////////////////////////////////////////////////////////////////
class OAuthLoginReqBody : public Aone2MessageBody
{
public:
	OAuthLoginReqBody();

	virtual ~OAuthLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_oauth_type;  // 登陆类型(sina, tencent, facebook, gamecenter, google, weixin, twitter, line, naver)
	string  m_oauth_token;  // 开放平台验证令牌
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息(渠道类型必须填aone_android或aone_ios)
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVer方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// 各类开放平台登陆回复
// class OAuthLoginRespBody = 1705
////////////////////////////////////////////////////////////////////////////////
class OAuthLoginRespBody : public Aone2MessageBody
{
public:
	OAuthLoginRespBody();

	virtual ~OAuthLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_user_account;  // (本平台)用户账号名
	string  m_token;  // (本平台)用户身份验证码
	string  m_ext;  // 需要回传sdk的数据
};

////////////////////////////////////////////////////////////////////////////////
// 各类开放平台手机(Mobile)绑定请求
// class OAuthBindReqBody = 1706
////////////////////////////////////////////////////////////////////////////////
class OAuthBindReqBody : public Aone2MessageBody
{
public:
	OAuthBindReqBody();

	virtual ~OAuthBindReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_oauth_type;  // 登陆类型(sina, tencent, facebook, gamecenter, google)
	string  m_oauth_token;  // 开放平台验证令牌
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息(渠道类型必须填aone_android或aone_ios)
	string  m_oauth_account;  // 第三方账号(目前仅facebook需要)
};

////////////////////////////////////////////////////////////////////////////////
// 各类开放平台手机(Mobile)绑定回复
// class OAuthBindRespBody = 1707
////////////////////////////////////////////////////////////////////////////////
class OAuthBindRespBody : public Aone2MessageBody
{
public:
	OAuthBindRespBody();

	virtual ~OAuthBindRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_user_account;  // (本平台)用户账号名
	string  m_token;  // (本平台)用户身份验证码
	string  m_ext;  // 需要回传sdk的数据
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号手机(Mobile)绑定请求
// 注册并把Aone账号绑定到设备上
// class AoneBindReqBody = 1708
////////////////////////////////////////////////////////////////////////////////
class AoneBindReqBody : public Aone2MessageBody
{
public:
	AoneBindReqBody();

	virtual ~AoneBindReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;  // 账号(6~50个字符，可使用字母、数字、下划线，不能以下划线开头，区分大小写)
	string  m_password;  // 密码(6~16个字符，区分大小写)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号手机(Mobile)绑定回复
// class AoneBindRespBody = 1709
////////////////////////////////////////////////////////////////////////////////
class AoneBindRespBody : public Aone2MessageBody
{
public:
	AoneBindRespBody();

	virtual ~AoneBindRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_user_account;  // 用户账号
	string  m_token;  // (本平台)用户身份验证码(若调用之前已绑定，返回无效的空token)
	string  m_aone_account;  // 绑定的Aone账号
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号注册请求
// 接口1: http post + json，url路径：/api/aone_register.do
// 接口2: aone2协议，协议号：1710
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneRegisterReqBody = 1710
////////////////////////////////////////////////////////////////////////////////
class AoneRegisterReqBody : public Aone2MessageBody
{
public:
	AoneRegisterReqBody();

	virtual ~AoneRegisterReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;  // 账号(6~50个字符，可使用字母、数字、下划线，不能以下划线开头，区分大小写)
	string  m_password;  // 密码(6~16个字符，区分大小写)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号注册回复
// class AoneRegisterRespBody = 1711
////////////////////////////////////////////////////////////////////////////////
class AoneRegisterRespBody : public Aone2MessageBody
{
public:
	AoneRegisterRespBody();

	virtual ~AoneRegisterRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_user_account;  // 用户账号
	string  m_token;  // (本平台)用户身份验证码
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号登陆请求
// 若绑定的设备与本次登陆的设备是同一设备，可以不验证密码。
// 接口1: http post + json，url路径：/api/aone_login.do
// 接口2: aone2协议，协议号：1712
// 采用接口1时，auth_key,device_info,version_info,delay_ms可以省略
// class AoneLoginReqBody = 1712
////////////////////////////////////////////////////////////////////////////////
class AoneLoginReqBody : public Aone2MessageBody
{
public:
	AoneLoginReqBody();

	virtual ~AoneLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;  // 账号(6~50个字符，可使用字母、数字、下划线，不能以下划线开头，区分大小写)
	string  m_password;  // 密码(6~16个字符，区分大小写)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVer方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号登陆回复
// class AoneLoginRespBody = 1713
////////////////////////////////////////////////////////////////////////////////
class AoneLoginRespBody : public Aone2MessageBody
{
public:
	AoneLoginRespBody();

	virtual ~AoneLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_user_account;  // 用户账号
	string  m_token;  // (本平台)用户身份验证码
	string  m_new_password;  // 新密码
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号修改密码请求
// 接口1: http post + json，url路径：/api/aone_change_password.do
// 接口2: aone2，协议号1714
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneChangePasswordReqBody = 1714
////////////////////////////////////////////////////////////////////////////////
class AoneChangePasswordReqBody : public Aone2MessageBody
{
public:
	AoneChangePasswordReqBody();

	virtual ~AoneChangePasswordReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_token;  // (本平台)用户身份验证码
	string  m_old_password;  // 旧密码
	string  m_new_password;  // 新密码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号修改密码回复
// class AoneChangePasswordRespBody = 1715
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneChangePasswordRespBody;


////////////////////////////////////////////////////////////////////////////////
// (通过手机)申请验证码请求
// 接口1: http post + json，url路径：/api/apply_token_by_phone.do?appid=xxx&sign=xxxx
// 接口2: aone2, 协议号1716
// 采用接口1时，auth_key,device_info,version_info可以省略
// 请求频率限制：需要限制!!!
// class ApplyTokenByPhoneReqBody = 1716
////////////////////////////////////////////////////////////////////////////////
class ApplyTokenByPhoneReqBody : public Aone2MessageBody
{
public:
	ApplyTokenByPhoneReqBody();

	virtual ~ApplyTokenByPhoneReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_action;  // 动作(bind:绑定, unbind:解绑, resetpwd:重置密码)
	string  m_phone;  // 手机号
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// (通过手机)申请验证码回复
// class ApplyTokenByPhoneRespBody = 1717
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody ApplyTokenByPhoneRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号绑定手机号
// 接口1: http post + json，url路径：/api/aone_bind_phone.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1718
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneBindPhoneReqBody = 1718
////////////////////////////////////////////////////////////////////////////////
class AoneBindPhoneReqBody : public Aone2MessageBody
{
public:
	AoneBindPhoneReqBody();

	virtual ~AoneBindPhoneReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_phone;  // 手机号
	string  m_phone_token;  // (通过手机获取的)验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号绑定手机号回复
// class AoneBindPhoneRespBody = 1719
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneBindPhoneRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号解除手机号绑定请求
// 接口1: http post + json，url路径：/api/aone_unbind_phone.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1720
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneUnBindPhoneReqBody = 1720
////////////////////////////////////////////////////////////////////////////////
class AoneUnBindPhoneReqBody : public Aone2MessageBody
{
public:
	AoneUnBindPhoneReqBody();

	virtual ~AoneUnBindPhoneReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_phone;  // 手机号
	string  m_phone_token;  // (通过手机获取的)验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号解除手机号绑定回复
// class AoneUnBindPhoneRespBody = 1721
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneUnBindPhoneRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号手机找回密码请求
// 接口1: http post + json，url路径：/api/aone_reset_password_by_phone.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1722
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneResetPasswordByPhoneReqBody = 1722
////////////////////////////////////////////////////////////////////////////////
class AoneResetPasswordByPhoneReqBody : public Aone2MessageBody
{
public:
	AoneResetPasswordByPhoneReqBody();

	virtual ~AoneResetPasswordByPhoneReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_phone;  // 手机号
	string  m_phone_token;  // (通过手机获取的)验证码
	string  m_password;  // 新密码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号手机找回密码请求
// class AoneResetPasswordByPhoneRespBody = 1723
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneResetPasswordByPhoneRespBody;


////////////////////////////////////////////////////////////////////////////////
// (通过邮件)申请验证码请求
// 接口1: http post + json，url路径：/api/apply_token_by_mail.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1724
// 采用接口1时，auth_key,device_info,version_info可以省略
// 请求频率限制：限制限制!!!
// class ApplyTokenByMailReqBody = 1724
////////////////////////////////////////////////////////////////////////////////
class ApplyTokenByMailReqBody : public Aone2MessageBody
{
public:
	ApplyTokenByMailReqBody();

	virtual ~ApplyTokenByMailReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_action;  // 动作(bind:绑定, unbind:解绑,resetpwd:重置密码)
	string  m_mail;  // 邮箱
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// (通过邮件)申请验证码回复
// class ApplyTokenByMailRespBody = 1725
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody ApplyTokenByMailRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号绑定邮箱请求
// 接口1: http post + json，url路径：/api/aone_bind_mail.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1726
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneBindMailReqBody = 1726
////////////////////////////////////////////////////////////////////////////////
class AoneBindMailReqBody : public Aone2MessageBody
{
public:
	AoneBindMailReqBody();

	virtual ~AoneBindMailReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_mail;  // 邮箱
	string  m_mail_token;  // (通过邮箱获取的)验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号绑定邮箱回复
// class AoneBindMailRespBody = 1727
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneBindMailRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号解除邮箱绑定请求
// 接口1: http post + json，url路径：/api/aone_unbind_mail.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1732
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneUnBindMailReqBody = 1728
////////////////////////////////////////////////////////////////////////////////
class AoneUnBindMailReqBody : public Aone2MessageBody
{
public:
	AoneUnBindMailReqBody();

	virtual ~AoneUnBindMailReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_mail;  // 邮箱
	string  m_mail_token;  // (通过邮箱获取的)验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号解除邮箱绑定回复
// class AoneUnBindMailRespBody = 1729
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneUnBindMailRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号邮箱找回密码请求
// 接口1: http post + json，url路径：/api/aone_reset_password_by_mail.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1730
// 采用接口1时，auth_key,device_info,version_info可以省略
// class AoneResetPasswordByMailReqBody = 1730
////////////////////////////////////////////////////////////////////////////////
class AoneResetPasswordByMailReqBody : public Aone2MessageBody
{
public:
	AoneResetPasswordByMailReqBody();

	virtual ~AoneResetPasswordByMailReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_mail;  // 邮箱
	string  m_mail_token;  // (通过邮箱获取的)验证码
	string  m_password;  // 新密码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号邮箱找回密码回复
// class AoneResetPasswordByMailRespBody = 1731
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneResetPasswordByMailRespBody;


////////////////////////////////////////////////////////////////////////////////
// 按用户ID查询Aone账号信息
// 接口1: http post + json，url路径：/api/aone_account_info.do?appid=xxx&sign=xxxx
// 暂时只支持一种接口
// class AoneAccountInfoReqBody = 1732
////////////////////////////////////////////////////////////////////////////////
class AoneAccountInfoReqBody : public Aone2MessageBody
{
public:
	AoneAccountInfoReqBody();

	virtual ~AoneAccountInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 按用户ID查询Aone账号信息
// class AoneAccountInfoRespBody = 1733
////////////////////////////////////////////////////////////////////////////////
class AoneAccountInfoRespBody : public Aone2MessageBody
{
public:
	AoneAccountInfoRespBody();

	virtual ~AoneAccountInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_account;  // Aone账号
	string  m_device_id;  // 绑定设备ID
	string  m_phone;  // 绑定电话
	string  m_mail;  // 绑定邮箱
	string  m_weixin;  // 绑定微信
	string  m_real_name;  // 真实姓名
	string  m_identity_number;  // 身份证号
	uint32  m_flag;  // 标识
	string  m_create_time;  // 账号创建时间(yyyy-mm-dd hh:mm:ss)
};

////////////////////////////////////////////////////////////////////////////////
// 各类开放平台信息查询请求
// class OAuthInfoReqBody = 1734
////////////////////////////////////////////////////////////////////////////////
class OAuthInfoReqBody : public Aone2MessageBody
{
public:
	OAuthInfoReqBody();

	virtual ~OAuthInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_oauth_type;  // 登陆类型(sina, tencent, facebook, gamecenter, google)
	string  m_oauth_token;  // 开放平台验证令牌
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
};

////////////////////////////////////////////////////////////////////////////////
// 各类开放平台信息查询回复
// class OAuthInfoRespBody = 1735
////////////////////////////////////////////////////////////////////////////////
class OAuthInfoRespBody : public Aone2MessageBody
{
public:
	OAuthInfoRespBody();

	virtual ~OAuthInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	bool  m_is_register_device;  // 设备ID是否已注册
	bool  m_is_register_oauth;  // 第三方账号是否已注册
};

////////////////////////////////////////////////////////////////////////////////
// (设备)快速注册请求
// 若没有绑定Aone账号，则同时随机生成一个Aone账号和密码与该设备绑定
// class QuickRegisterReqBody = 1736
////////////////////////////////////////////////////////////////////////////////
class QuickRegisterReqBody : public Aone2MessageBody
{
public:
	QuickRegisterReqBody();

	virtual ~QuickRegisterReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_delay_ms;  // 客户端与游戏服间延时(记录SDK中向入口服调用CheckVer方法花费的毫秒时间)
};

////////////////////////////////////////////////////////////////////////////////
// (设备)快速注册回复
// class QuickRegisterRespBody = 1737
////////////////////////////////////////////////////////////////////////////////
class QuickRegisterRespBody : public Aone2MessageBody
{
public:
	QuickRegisterRespBody();

	virtual ~QuickRegisterRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	string  m_user_account;  // 用户设备账号: ******@device
	string  m_aone_account;  // 绑定的Aone账号
	string  m_aone_password;  // Aone密码,如果不为空，表示该设备是第一次快速注册
	string  m_token;  // (本平台)用户身份验证码
};

////////////////////////////////////////////////////////////////////////////////
// 实名制账号信息请求
// 接口1: http post + json，url路径：/api/aone_account_certificate.do?appid=xxx&sign=xxxx
// class AoneAccountCertificateReqBody = 1738
////////////////////////////////////////////////////////////////////////////////
class AoneAccountCertificateReqBody : public Aone2MessageBody
{
public:
	AoneAccountCertificateReqBody();

	virtual ~AoneAccountCertificateReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_real_name;  // 真实姓名
	string  m_identity_number;  // 身份证号
};

////////////////////////////////////////////////////////////////////////////////
// 实名制账号信息回复
// class AoneAccountCertificateRespBody = 1739
////////////////////////////////////////////////////////////////////////////////
class AoneAccountCertificateRespBody : public Aone2MessageBody
{
public:
	AoneAccountCertificateRespBody();

	virtual ~AoneAccountCertificateRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
};

////////////////////////////////////////////////////////////////////////////////
// AoneSdk版本检测
// class AoneSdkCheckVerReqBody = 1740
////////////////////////////////////////////////////////////////////////////////
class AoneSdkCheckVerReqBody : public Aone2MessageBody
{
public:
	AoneSdkCheckVerReqBody();

	virtual ~AoneSdkCheckVerReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// class AoneSdkCheckVerRespBody = 1741
////////////////////////////////////////////////////////////////////////////////
class AoneSdkCheckVerRespBody : public Aone2MessageBody
{
public:
	AoneSdkCheckVerRespBody();

	virtual ~AoneSdkCheckVerRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<ChannelVersionInfo>  m_new_version_info;  // 最新版本信息
	vector<ChannelVersionInfo>  m_cur_version_info;  // 当前版本信息
	string  m_server_time;  // 服务器当前时间
};

////////////////////////////////////////////////////////////////////////////////
// 账号实名认证信息查询请求
// 接口1: http post + json，url路径：/api/account_identify_info.do?appid=xxx&sign=xxxx
// class AccountIdentityInfoReqBody = 1742
////////////////////////////////////////////////////////////////////////////////
class AccountIdentityInfoReqBody : public Aone2MessageBody
{
public:
	AccountIdentityInfoReqBody();

	virtual ~AccountIdentityInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 账号实名认证信息查询回复
// class AccountIdentityInfoRespBody = 1743
////////////////////////////////////////////////////////////////////////////////
class AccountIdentityInfoRespBody : public Aone2MessageBody
{
public:
	AccountIdentityInfoRespBody();

	virtual ~AccountIdentityInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
};

////////////////////////////////////////////////////////////////////////////////
// 账号实名认证请求
// 接口1: http post + json，url路径：/api/account_certificate.do?appid=xxx&sign=xxxx
// class AccountCertificateReqBody = 1744
////////////////////////////////////////////////////////////////////////////////
class AccountCertificateReqBody : public Aone2MessageBody
{
public:
	AccountCertificateReqBody();

	virtual ~AccountCertificateReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_real_name;  // 真实姓名
	string  m_identity_number;  // 身份证号
};

////////////////////////////////////////////////////////////////////////////////
// 账号实名认证回复
// class AccountCertificateRespBody = 1745
////////////////////////////////////////////////////////////////////////////////
class AccountCertificateRespBody : public Aone2MessageBody
{
public:
	AccountCertificateRespBody();

	virtual ~AccountCertificateRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
	string  m_real_name;  // 带隐藏的真实姓名
	string  m_identity_number;  // 带隐藏的身份证号
};
////////////////////////////////////////////////////////////////////////////////
// Aone账号绑定到其他账号上
// class AoneBindOtherAccountReqBody = 1746
////////////////////////////////////////////////////////////////////////////////
class AoneBindOtherAccountReqBody : public Aone2MessageBody
{
public:
	AoneBindOtherAccountReqBody();

	virtual ~AoneBindOtherAccountReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_type;  // 账号类型（apple/facebook/google/twitter/gamecenter）
	string  m_new_account;  // 绑定新账号
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号绑定到其他账号回复
// class AoneBindOtherAccountRespBody = 1747
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneBindOtherAccountRespBody;


////////////////////////////////////////////////////////////////////////////////
// Aone账号从其他账号上解绑
// class AoneUnbindOtherAccountReqBody = 1748
////////////////////////////////////////////////////////////////////////////////
class AoneUnbindOtherAccountReqBody : public Aone2MessageBody
{
public:
	AoneUnbindOtherAccountReqBody();

	virtual ~AoneUnbindOtherAccountReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_type;  // 账号类型
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// Aone账号从其他账号上解绑回复
// class AoneUnbindOtherAccountRespBody = 1749
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody AoneUnbindOtherAccountRespBody;


////////////////////////////////////////////////////////////////////////////////
// 查询aone账号绑定的其他账号
// class AoneQueryBindOtherAccountReqBody = 1750
////////////////////////////////////////////////////////////////////////////////
class AoneQueryBindOtherAccountReqBody : public Aone2MessageBody
{
public:
	AoneQueryBindOtherAccountReqBody();

	virtual ~AoneQueryBindOtherAccountReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_type;  // 账号类型
};

////////////////////////////////////////////////////////////////////////////////
// 查询aone账号绑定的其他账号回复
// class AoneQueryBindOtherAccountRespBody = 1751
////////////////////////////////////////////////////////////////////////////////
class AoneQueryBindOtherAccountRespBody : public Aone2MessageBody
{
public:
	AoneQueryBindOtherAccountRespBody();

	virtual ~AoneQueryBindOtherAccountRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_account;
};

////////////////////////////////////////////////////////////////////////////////
// Facebook Game Instant登录请求
// 第一次登陆自动生成注册
// 接口: http post + json，url路径：/api/fbinstant_login.do
// class FBInstantLoginReqBody = 1764
////////////////////////////////////////////////////////////////////////////////
class FBInstantLoginReqBody : public Aone2MessageBody
{
public:
	FBInstantLoginReqBody();

	virtual ~FBInstantLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_id;  // FB用户ID
	string  m_name;  // FB用户名字
	string  m_photo;  // FB用户头像
	string  m_signature;  // 对id的签名，该字符串是base64url编码的，使用 HMAC 对您应用的 Secret 进行签名
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 客户端设备信息
	AppVersionInfo  m_version_info;  // APP应用信息
};

////////////////////////////////////////////////////////////////////////////////
// Facebook Game Instant登录回复
// class FBInstantLoginRespBody = 1765
////////////////////////////////////////////////////////////////////////////////
class FBInstantLoginRespBody : public Aone2MessageBody
{
public:
	FBInstantLoginRespBody();

	virtual ~FBInstantLoginRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_user_account;  // (本平台)用户账号名
	string  m_token;  // (本平台)用户身份验证码
};


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////
// 获取渠道配置信息请求
// 各类第三方账号(如sina微博)属于aone渠道
// 接口1: http post + json，url路径：/api/query_channel_config.do?appid=xxx
// class QueryChannelConfigReqBody = 1790
////////////////////////////////////////////////////////////////////////////////
class QueryChannelConfigReqBody : public Aone2MessageBody
{
public:
	QueryChannelConfigReqBody();

	virtual ~QueryChannelConfigReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	string  m_code;  // 移动国家和网络代码，例：42104
	bool  m_is_wifi;  // 客户端是否使用wifi
};

////////////////////////////////////////////////////////////////////////////////
// 获取渠道配置信息回复
// class QueryChannelConfigRespBody = 1791
////////////////////////////////////////////////////////////////////////////////
class QueryChannelConfigRespBody : public Aone2MessageBody
{
public:
	QueryChannelConfigRespBody();

	virtual ~QueryChannelConfigRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<KVPair>  m_channel_params;  // 渠道(SDK)参数配置列表
	vector<PayProductInfo>  m_channel_products;  // 渠道支付商品列表
	string  m_entryserver_ip;  // 入口服IP
	uint16  m_entryserver_port;  // 入口服端口
	vector<KVPair>  m_app_langs;  // 应用支持的语言列表
	string  m_bbs_url;  // 游戏论坛(以及用户中心)URL地址
	bool  m_is_enable;  // 是否显示当地支付
	vector<PayProductExtInfo>  m_channel_products_ext;  // 渠道支付商品列表扩展
};

////////////////////////////////////////////////////////////////////////////////
// SDK内部检测资源下载异常日志请求
// class RecordSDKDownloadExceptionReqBody = 1792
////////////////////////////////////////////////////////////////////////////////
class RecordSDKDownloadExceptionReqBody : public Aone2MessageBody
{
public:
	RecordSDKDownloadExceptionReqBody();

	virtual ~RecordSDKDownloadExceptionReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_dns;  // 域名解析使用的DNS服务器地址
	string  m_ip;  // url中域名解析出来的IP地址
	string  m_url;  // 资源下载url地址
	string  m_code;  // 错误码
	string  m_detail;  // 资源下载详情(http回复等)
	uint32  m_use_ms;  // 从请求资源到得到回复使用的时长(毫秒)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// SDK内部检测资源下载异常日志回复
// class RecordSDKDownloadExceptionRespBody = 1793
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody RecordSDKDownloadExceptionRespBody;


////////////////////////////////////////////////////////////////////////////////
// SDK收集游戏中资源下载异常日志请求
// class RecordGameDownloadExceptionReqBody = 1794
////////////////////////////////////////////////////////////////////////////////
class RecordGameDownloadExceptionReqBody : public Aone2MessageBody
{
public:
	RecordGameDownloadExceptionReqBody();

	virtual ~RecordGameDownloadExceptionReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_url;  // 资源下载url地址
	string  m_code;  // 错误码
	string  m_detail;  // 资源下载详情(http回复等)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// SDK收集游戏中资源下载异常日志回复
// class RecordGameDownloadExceptionRespBody = 1795
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody RecordGameDownloadExceptionRespBody;


////////////////////////////////////////////////////////////////////////////////
// SDK收集支付异常日志请求
// class recordSDKPayExceptionReqBody = 1796
////////////////////////////////////////////////////////////////////////////////
class recordSDKPayExceptionReqBody : public Aone2MessageBody
{
public:
	recordSDKPayExceptionReqBody();

	virtual ~recordSDKPayExceptionReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_code;  // SDK返回的错误码
	string  m_detail;  // 异常详情(错误描述等)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// SDK收集支付异常日志回复
// class recordSDKPayExceptionRespBody = 1797
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody recordSDKPayExceptionRespBody;


////////////////////////////////////////////////////////////////////////////////
// 判定是否显示当地支付支付商页面请求
// 用于海外发行避开谷歌审查
// class QueryIsEnableLocalPayReqBody = 1798
////////////////////////////////////////////////////////////////////////////////
class QueryIsEnableLocalPayReqBody : public Aone2MessageBody
{
public:
	QueryIsEnableLocalPayReqBody();

	virtual ~QueryIsEnableLocalPayReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_code;  // 移动国家和网络代码，例：42104
	bool  m_is_wifi;  // 客户端是否使用wifi
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 判定是否显示当地支付支付商页面回复
// 用于海外发行避开谷歌审查
// class QueryIsEnableLocalPayRespBody = 1799
////////////////////////////////////////////////////////////////////////////////
class QueryIsEnableLocalPayRespBody : public Aone2MessageBody
{
public:
	QueryIsEnableLocalPayRespBody();

	virtual ~QueryIsEnableLocalPayRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	bool  m_is_enable;  // 是否显示
};

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////
// 用户登陆验证请求
// 接口1: http post + json，url路径：/api/user_verify.do?appid=xxx&sign=xxxx
// 接口2: aone2，协议号1800
// 采用接口1时，auth_key,device_info,version_info可以省略
// class UserVerifyReqBody = 1800
////////////////////////////////////////////////////////////////////////////////
class UserVerifyReqBody : public Aone2MessageBody
{
public:
	UserVerifyReqBody();

	virtual ~UserVerifyReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_token;  // (本平台)用户身份验证码
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 用户登陆验证回复
// class UserVerifyRespBody = 1801
////////////////////////////////////////////////////////////////////////////////
class UserVerifyRespBody : public Aone2MessageBody
{
public:
	UserVerifyRespBody();

	virtual ~UserVerifyRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // (本平台)用户ID
	string  m_user_account;  // (本平台)用户账号名
};

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////
// 支付请求
// 1.订单号由UUSDK按规则生成
// 2.订单号置空由服务器生成
// 以后都按2执行，pay_no存在只为兼容较早版本sdk
// 接口1: http post + json，url路径：/api/pay.do
// 接口2: aone2，协议号1850
// 采用接口1时，auth_key,device_info,version_info可以省略
// class PayReqBody = 1850
////////////////////////////////////////////////////////////////////////////////
class PayReqBody : public Aone2MessageBody
{
public:
	PayReqBody();

	virtual ~PayReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
	uint32  m_role_id;  // 角色ID(已废弃)
	string  m_receipt;  // 第三方收据(没有时置空)
	string  m_pay_channel;  // 支付渠道
	string  m_cp_ext;  // 做发行时留给开发商扩展的字段，回调时原样返回(限长255字节)
	string  m_pay_no;  // 订单号
	string  m_product_id;  // 商品唯一ID(类似于com.aonesoft.zqgame.item1，不特指商品名，不确定的可置空)
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	string  m_cp_role_id;  // cp 角色ID
	string  m_cp_group_id;  // cp 分区ID
	string  m_channel_user_id;  // 第三方渠道user_id(用于支付回调验证)
	uint32  m_product_quantity;  // 商品数量
};

////////////////////////////////////////////////////////////////////////////////
// 支付回复
// class PayRespBody = 1851
////////////////////////////////////////////////////////////////////////////////
class PayRespBody : public Aone2MessageBody
{
public:
	PayRespBody();

	virtual ~PayRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_pay_no;  // 订单号
	uint32  m_discount;  // 折扣
};


////////////////////////////////////////////////////////////////////////////////
// 异常订单信息查询请求
// 最多返回查询结果100条
// 角色ID为0时，角色ID不作为查询限定条件
// 支付渠道为空时，支付渠道不作为查询限定条件
// 接口1: http post + json，url路径：/api/query_exception_payorders.do?appid=xxx&sign=xxxx
// class QueryExceptionPayOrdersReqBody = 1854
////////////////////////////////////////////////////////////////////////////////
class QueryExceptionPayOrdersReqBody : public Aone2MessageBody
{
public:
	QueryExceptionPayOrdersReqBody();

	virtual ~QueryExceptionPayOrdersReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_role_id;  // 角色ID(为0时不作为查询限定条件)
	string  m_pay_channel;  // 支付渠道(为空时不作为查询限定条件)
	string  m_begin_time;  // 查询起始时间(格式：yyyy-mm-dd hh:mm:ss)
	string  m_end_time;  // 查询结束时间(格式：yyyy-mm-dd hh:mm:ss)
};

////////////////////////////////////////////////////////////////////////////////
// 异常订单信息查询回复
// class QueryExceptionPayOrdersRespBody = 1855
////////////////////////////////////////////////////////////////////////////////
class QueryExceptionPayOrdersRespBody : public Aone2MessageBody
{
public:
	// class ExceptionPayOrder
	class ExceptionPayOrder : public Aone2MessageBody
	{
	public:
		ExceptionPayOrder();

		virtual ~ExceptionPayOrder();

		virtual int parse_bytes(const byte* src, uint32 len);

		virtual int to_bytes(byte* dst, uint32 maxlen);

		virtual uint32 calc_length();

	public:
		string  m_pay_no;  // (本平台)订单号
		string  m_pay_out_no;  // 第三方订单号
		bool  m_is_verify;  // 是否主动验证模式(否则为第三方回调模式)
		string  m_status;  // 状态
		uint32  m_user_id;  // 用户id
		uint32  m_role_id;  // 角色id
		string  m_pay_channel;  // 支付渠道
		string  m_cp_ext;  // 做发行时留给开发商扩展的字段，回调时原样返回
		string  m_receipt;  // 第三方收据(回调的渠道填回调http请求原始数据)
		string  m_notify_url;  // 通知游戏支付完成信息的URL地址
		string  m_product_id;  // 购买的商品ID
		string  m_pay_commit_time;  // 订单提交时间(格式：yyyy-mm-dd hh:mm:ss)
		string  m_pay_finished_time;  // 支付成功时间(主动验证和第三方回调)(格式：yyyy-mm-dd hh:mm:ss)
	};

public:
	QueryExceptionPayOrdersRespBody();

	virtual ~QueryExceptionPayOrdersRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<ExceptionPayOrder>  m_pay_orders;  // 订单信息列表
};

////////////////////////////////////////////////////////////////////////////////
// 收据提交请求
// class CommitReceiptReqBody = 1856
////////////////////////////////////////////////////////////////////////////////
class CommitReceiptReqBody : public Aone2MessageBody
{
public:
	CommitReceiptReqBody();

	virtual ~CommitReceiptReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_pay_no;  // 订单号
	string  m_receipt;  // 第三方收据
	string  m_pay_channel;  // 支付渠道
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 收据提交回复
// class CommitReceiptRespBody = 1857
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody CommitReceiptRespBody;


////////////////////////////////////////////////////////////////////////////////
// 订单状态查询请求, 查询用户最近一笔支付状态
// class QueryOrderStatusReqBody = 1858
////////////////////////////////////////////////////////////////////////////////
class QueryOrderStatusReqBody : public Aone2MessageBody
{
public:
	QueryOrderStatusReqBody();

	virtual ~QueryOrderStatusReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_auth_key;  // 验证码 = AuthKeyA(device_id + appkey)
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 订单状态查询回复
// class QueryOrderStatusRespBody = 1859
////////////////////////////////////////////////////////////////////////////////
class QueryOrderStatusRespBody : public Aone2MessageBody
{
public:
	QueryOrderStatusRespBody();

	virtual ~QueryOrderStatusRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_pay_no;
	string  m_currency;
	double  m_amount;
	double  m_amount_usd;
	uint32  m_coin;
};

////////////////////////////////////////////////////////////////////////////////
// 查询具体订单号的支付状态请求
// class QueryPayNoStatusReqBody = 1860
////////////////////////////////////////////////////////////////////////////////
class QueryPayNoStatusReqBody : public Aone2MessageBody
{
public:
	QueryPayNoStatusReqBody();

	virtual ~QueryPayNoStatusReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_app_id;  //	应用ID
	string  m_pay_no;  // 需要查询订单的订单号
};

////////////////////////////////////////////////////////////////////////////////
// 查询具体订单号的支付状态回复
// class QueryPayNoStatusRespBody = 1861
////////////////////////////////////////////////////////////////////////////////
class QueryPayNoStatusRespBody : public Aone2MessageBody
{
public:
	QueryPayNoStatusRespBody();

	virtual ~QueryPayNoStatusRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_status;  // 订单状态
};


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////
// 邮件，短信，推送相关
// 发送邮件请求
// 接口1: http post + json，url路径：/api/send_mail.do?appid=xxx&sign=xxxx
// class SendMailReqBody = 1900
////////////////////////////////////////////////////////////////////////////////
class SendMailReqBody : public Aone2MessageBody
{
public:
	SendMailReqBody();

	virtual ~SendMailReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<string>  m_recipients;  // 邮件接收者列表(完整邮件地址)
	string  m_subject;  // 邮件标题
	string  m_content;  // 邮件正文(text/html;charset=utf-8)
	uint32  m_timeout;  // 超时时长(可选，单位：秒，为0不检测超时；否则排队时长超过指定时长自动丢弃)
};

////////////////////////////////////////////////////////////////////////////////
// 发送邮件回复
// class SendMailRespBody = 1901
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody SendMailRespBody;


////////////////////////////////////////////////////////////////////////////////
// 发送短信请求
// 接口1: http post + json，url路径：/api/send_sms.do?appid=xxx&sign=xxxx
// class SendSMSReqBody = 1902
////////////////////////////////////////////////////////////////////////////////
class SendSMSReqBody : public Aone2MessageBody
{
public:
	SendSMSReqBody();

	virtual ~SendSMSReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<string>  m_phones;  // 要发往的手机号列表
	string  m_content;  // 短信内容
	uint32  m_timeout;  // 超时时长(可选，单位：秒，为0不检测超时；否则排队时长超过指定时长自动丢弃)
	uint32  m_selected;  // 选择短信服务商
};

////////////////////////////////////////////////////////////////////////////////
// 发送短信回复
// class SendSMSRespBody = 1903
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody SendSMSRespBody;


////////////////////////////////////////////////////////////////////////////////
// 向指定的设备(列表)推送消息请求
// 接口1: http post + json，url路径：/api/push_message.do?appid=xxx&sign=xxxx
// class PushMessageReqBody = 1904
////////////////////////////////////////////////////////////////////////////////
class PushMessageReqBody : public Aone2MessageBody
{
public:
	PushMessageReqBody();

	virtual ~PushMessageReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<string>  m_tokens;  // 设备验证码列表(不能为空)
	string  m_title;  // 标题
	string  m_content;  // 内容
	uint32  m_timeout;  // 超时时长(可选，单位：秒，为0不检测超时；否则排队时长超过指定时长自动丢弃)
	string  m_push_style;  // 推送风格定义(见推送风格定义)
	string  m_push_channel;  // 推送渠道(见推送渠道编码定义)
	string  m_channel;  // 发行渠道
};

////////////////////////////////////////////////////////////////////////////////
// 向指定的设备(列表)推送消息回复
// class PushMessageRespBody = 1905
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody PushMessageRespBody;


////////////////////////////////////////////////////////////////////////////////
// 向具有指定标签的设备推送消息请求
// 接口1: http post + json，url路径：/api/push_tag_message.do?appid=xxx&sign=xxxx
// class PushTagMessageReqBody = 1906
////////////////////////////////////////////////////////////////////////////////
class PushTagMessageReqBody : public Aone2MessageBody
{
public:
	PushTagMessageReqBody();

	virtual ~PushTagMessageReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_tag;  // 标签
	string  m_title;  // 标题
	string  m_content;  // 内容
	uint32  m_timeout;  // 超时时长(可选，单位：秒，为0不检测超时；否则排队时长超过指定时长自动丢弃)
	string  m_push_style;  // 推送风格定义(见推送风格定义)
	string  m_push_channel;  // 推送渠道(见推送渠道编码定义)
	string  m_channel;  // 发行渠道
};

////////////////////////////////////////////////////////////////////////////////
// 向具有指定标签的设备推送消息回复
// class PushTagMessageRespBody = 1907
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody PushTagMessageRespBody;


////////////////////////////////////////////////////////////////////////////////
// 向指定应用广播消息请求
// 接口1: http post + json，url路径：/api/push_broadcast_message.do?appid=xxx&sign=xxxx
// apns不支持广播
// class PushBroadcastMessageReqBody = 1908
////////////////////////////////////////////////////////////////////////////////
class PushBroadcastMessageReqBody : public Aone2MessageBody
{
public:
	PushBroadcastMessageReqBody();

	virtual ~PushBroadcastMessageReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_title;  // 标题
	string  m_content;  // 内容
	uint32  m_timeout;  // 超时时长(可选，单位：秒，为0不检测超时；否则排队时长超过指定时长自动丢弃)
	string  m_push_style;  // 推送风格定义(见推送风格定义)
	string  m_push_channel;  // 推送渠道(见推送渠道编码定义)
	string  m_channel;  // 发行渠道
};

////////////////////////////////////////////////////////////////////////////////
// 向指定应用广播消息回复
// class PushBroadcastMessageRespBody = 1909
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody PushBroadcastMessageRespBody;


////////////////////////////////////////////////////////////////////////////////
// 获取站点指定的某个产品的信息请求
// 接口: http post + json，url路径：/api/query_product_info.do?appid=xxx&sign=xxxx
// class QueryProductInfoReqBody = 1920
////////////////////////////////////////////////////////////////////////////////
class QueryProductInfoReqBody : public Aone2MessageBody
{
public:
	QueryProductInfoReqBody();

	virtual ~QueryProductInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_product_id;  //产品ID
};

////////////////////////////////////////////////////////////////////////////////
// 获取站点配置信息回复
// class QueryProductInfoRespBody = 1921
////////////////////////////////////////////////////////////////////////////////
class QueryProductInfoRespBody : public Aone2MessageBody
{
public:
	QueryProductInfoRespBody();

	virtual ~QueryProductInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	WebsiteProductInfo  m_website_product;  // 产品参数配置列表
};

////////////////////////////////////////////////////////////////////////////////
// 获取指定站点的产品列表请求
// 接口: http post + json，url路径：/api/query_website_product_list.do?appid=xxx&sign=xxxx
// class QueryWebsiteProductListReqBody = 1922
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody QueryWebsiteProductListReqBody;


////////////////////////////////////////////////////////////////////////////////
// 获取站点配置信息回复
// class QueryWebsiteProductListRespBody = 1923
////////////////////////////////////////////////////////////////////////////////
class QueryWebsiteProductListRespBody : public Aone2MessageBody
{
public:
	QueryWebsiteProductListRespBody();

	virtual ~QueryWebsiteProductListRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<uint32>  m_website_products;  // 产品id列表
	string  m_channel_name;  // 渠道名映射
};

////////////////////////////////////////////////////////////////////////////////
// 获取渠道列表请求
// 接口1: http post + json，url路径：/api/query_channels.do
// class QueryAppChannelsReqBody = 1950
////////////////////////////////////////////////////////////////////////////////
class QueryAppChannelsReqBody : public Aone2MessageBody
{
public:
	QueryAppChannelsReqBody();

	virtual ~QueryAppChannelsReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_appid;  // 应用ID(必须与url中的appid相等或为0，为0时取所有渠道列表)
	bool  m_is_use_alias;  // 是否使用渠道ID别名
};

////////////////////////////////////////////////////////////////////////////////
// 获取渠道列表回复
// class QueryAppChannelsRespBody = 1951
////////////////////////////////////////////////////////////////////////////////
class QueryAppChannelsRespBody : public Aone2MessageBody
{
public:
	QueryAppChannelsRespBody();

	virtual ~QueryAppChannelsRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<KVPair>  m_channels;  // 渠道列表
};

////////////////////////////////////////////////////////////////////////////////
// 获取语言列表请求
// 接口1: http post + json，url路径：/api/query_langs.do
// class QueryAppLangsReqBody = 1952
////////////////////////////////////////////////////////////////////////////////
class QueryAppLangsReqBody : public Aone2MessageBody
{
public:
	QueryAppLangsReqBody();

	virtual ~QueryAppLangsReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_appid;  // 应用ID(必须与url中的appid相等或为0，为0时取所有渠道列表)
};

////////////////////////////////////////////////////////////////////////////////
// 获取语言列表回复
// class QueryAppLangsRespBody = 1953
////////////////////////////////////////////////////////////////////////////////
class QueryAppLangsRespBody : public Aone2MessageBody
{
public:
	QueryAppLangsRespBody();

	virtual ~QueryAppLangsRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<KVPair>  m_langs;  // 语言列表(语言 -- 描述)
};

////////////////////////////////////////////////////////////////////////////////
// 获取商品列表请求
// channel: 为空时取该应用所有商品；否则只取划分给该渠道的所有商品；渠道无效或该应用未分配该渠道时返回商品列表为空
// 接口1: http post + json，url路径：/api/query_products.do?appid=xxx
// class QueryAppProductsReqBody = 1954
////////////////////////////////////////////////////////////////////////////////
class QueryAppProductsReqBody : public Aone2MessageBody
{
public:
	QueryAppProductsReqBody();

	virtual ~QueryAppProductsReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_channel;  // 渠道ID
};

////////////////////////////////////////////////////////////////////////////////
// 获取商品列表回复
// class QueryAppProductsRespBody = 1955
////////////////////////////////////////////////////////////////////////////////
class QueryAppProductsRespBody : public Aone2MessageBody
{
public:
	QueryAppProductsRespBody();

	virtual ~QueryAppProductsRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	vector<PayProductInfo>  m_products;  // 商品列表
	vector<PayProductExtInfo>  m_channel_products_ext;  // 渠道支付商品列表扩展
};

////////////////////////////////////////////////////////////////////////////////
// 角色登入日志记录
// class RecordRoleLoginReqBody = 1960
////////////////////////////////////////////////////////////////////////////////
class RecordRoleLoginReqBody : public Aone2MessageBody
{
public:
	RecordRoleLoginReqBody();

	virtual ~RecordRoleLoginReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_group_id;  // 分区id
	string  m_role_id;  // 角色id
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	string  m_group_name;  // 分区名字
	string  m_role_name;  // 分区角色名字
};

////////////////////////////////////////////////////////////////////////////////
// 角色登入日志记录回复
// class RecordRoleLoginRespBody = 1961
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody RecordRoleLoginRespBody;


////////////////////////////////////////////////////////////////////////////////
// 查询分享信息
// class QueryShareInfoReqBody = 1962
////////////////////////////////////////////////////////////////////////////////
class QueryShareInfoReqBody : public Aone2MessageBody
{
public:
	QueryShareInfoReqBody();

	virtual ~QueryShareInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// class QueryShareInfoRespBody = 1963
////////////////////////////////////////////////////////////////////////////////
class QueryShareInfoRespBody : public Aone2MessageBody
{
public:
	QueryShareInfoRespBody();

	virtual ~QueryShareInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_url;
	string  m_user_data;  // 用户数据
};

////////////////////////////////////////////////////////////////////////////////
// 发布分享信息
// class PublishShareInfoReqBody = 1964
////////////////////////////////////////////////////////////////////////////////
class PublishShareInfoReqBody : public Aone2MessageBody
{
public:
	PublishShareInfoReqBody();

	virtual ~PublishShareInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	string  m_user_data;
};

////////////////////////////////////////////////////////////////////////////////
// class PublishShareInfoRespBody = 1965
////////////////////////////////////////////////////////////////////////////////
class PublishShareInfoRespBody : public Aone2MessageBody
{
public:
	PublishShareInfoRespBody();

	virtual ~PublishShareInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_url;
};

////////////////////////////////////////////////////////////////////////////////
// 获取aone_group_id请求
// 接口: http post + json，url路径：/api/xxx?appid=xxx&sign=xxxx
// class QueryAoneGroupIdReqBody = 1966
////////////////////////////////////////////////////////////////////////////////
class QueryAoneGroupIdReqBody : public Aone2MessageBody
{
public:
	QueryAoneGroupIdReqBody();

	virtual ~QueryAoneGroupIdReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_app_id;
	string  m_cp_group_id;
	string  m_cp_group_name;
};

////////////////////////////////////////////////////////////////////////////////
// 获取站点配置信息回复
// class QueryAoneGroupIdRespBody = 1967
////////////////////////////////////////////////////////////////////////////////
class QueryAoneGroupIdRespBody : public Aone2MessageBody
{
public:
	QueryAoneGroupIdRespBody();

	virtual ~QueryAoneGroupIdRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_aone_group_id;
};

////////////////////////////////////////////////////////////////////////////////
// 光大银行生成签名请求
// 接口: http post + json，url路径：/api/ceb_sign.do?appid=xxx&sign=xxxx
// class AoneCEBSignReqBody = 1968
////////////////////////////////////////////////////////////////////////////////
class AoneCEBSignReqBody : public Aone2MessageBody
{
public:
	AoneCEBSignReqBody();

	virtual ~AoneCEBSignReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_appid;  // 应用ID
	string  m_channel;  // 发行渠道
	string  m_content;  // 需要签名的内容
};

////////////////////////////////////////////////////////////////////////////////
// 光大银行生成签名回复
// class AoneCEBSignRespBody = 1969
////////////////////////////////////////////////////////////////////////////////
class AoneCEBSignRespBody : public Aone2MessageBody
{
public:
	AoneCEBSignRespBody();

	virtual ~AoneCEBSignRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_sign_content;  // 添加签名后的内容
};

////////////////////////////////////////////////////////////////////////////////
// 查询应用下用户是否绑定过手机号请求
// 接口: http post + json，url路径：/api/query_user_phone_bind.do?appid=xxx&sign=xxxx
// class QueryUserPhoneBindReqBody = 1970
////////////////////////////////////////////////////////////////////////////////
class QueryUserPhoneBindReqBody : public Aone2MessageBody
{
public:
	QueryUserPhoneBindReqBody();

	virtual ~QueryUserPhoneBindReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 查询应用下用户是否绑定过手机号回复
// class QueryUserPhoneBindRespBody = 1971
////////////////////////////////////////////////////////////////////////////////
class QueryUserPhoneBindRespBody : public Aone2MessageBody
{
public:
	QueryUserPhoneBindRespBody();

	virtual ~QueryUserPhoneBindRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	bool  m_is_bind;  //true:已绑定;false:未绑定
	string  m_phone;  //手机号码(已绑定为手机号码，未绑定为空)
};

////////////////////////////////////////////////////////////////////////////////
// 申请短信验证码请求
// 接口: http post + json，url路径：/api/apply_code_by_phone.do?appid=xxx&sign=xxxx
// class ApplyCodeByPhoneReqBody = 1972
////////////////////////////////////////////////////////////////////////////////
class ApplyCodeByPhoneReqBody : public Aone2MessageBody
{
public:
	ApplyCodeByPhoneReqBody();

	virtual ~ApplyCodeByPhoneReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_type;  // 短信验证码类型 (bind:绑定;...)
	string  m_phone;  // 手机号码(接收短信验证码用)
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 申请短信验证码回复
// class ApplyCodeByPhoneRespBody = 1973
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody ApplyCodeByPhoneRespBody;


////////////////////////////////////////////////////////////////////////////////
// 验证短信验证码请求
// 接口: http post + json，url路径：/api/verify_code.do?appid=xxx&sign=xxxx
// class VerifyCodeReqBody = 1974
////////////////////////////////////////////////////////////////////////////////
class VerifyCodeReqBody : public Aone2MessageBody
{
public:
	VerifyCodeReqBody();

	virtual ~VerifyCodeReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	string  m_type;  //短信验证码类型 (bind:绑定;...)
	string  m_phone;  //手机号码(接收短信验证码用)
	string  m_code;  //短信验证码
};

////////////////////////////////////////////////////////////////////////////////
// 验证短信验证码回复
// class VerifyCodeRespBody = 1975
////////////////////////////////////////////////////////////////////////////////
class VerifyCodeRespBody : public Aone2MessageBody
{
public:
	VerifyCodeRespBody();

	virtual ~VerifyCodeRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	bool  m_is_success;  //true:验证通过;false:验证未通过
};

////////////////////////////////////////////////////////////////////////////////
// 设备埋点日志记录
// class RecordDevicePointReqBody = 1976
////////////////////////////////////////////////////////////////////////////////
class RecordDevicePointReqBody : public Aone2MessageBody
{
public:
	RecordDevicePointReqBody();

	virtual ~RecordDevicePointReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_sdk_point;  // 埋点信息
	bool  m_is_first_login;  // 是否第一次登陆
};

////////////////////////////////////////////////////////////////////////////////
// 设备埋点日志记录回复
// class RecordDevicePointRespBody = 1977
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody RecordDevicePointRespBody;


////////////////////////////////////////////////////////////////////////////////
// 角色埋点日志记录
// class RecordRolePointReqBody = 1978
////////////////////////////////////////////////////////////////////////////////
class RecordRolePointReqBody : public Aone2MessageBody
{
public:
	RecordRolePointReqBody();

	virtual ~RecordRolePointReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_cp_role_id;  // CP角色ID（支持非数字）
	string  m_cp_role_name;  // CP角色名
	string  m_cp_group_id;  // cp分区ID
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_game_point;  // 埋点信息
};

////////////////////////////////////////////////////////////////////////////////
// 角色埋点日志记录回复
// class RecordRolePointRespBody = 1979
////////////////////////////////////////////////////////////////////////////////
typedef Aone2EmptyMessageBody RecordRolePointRespBody;


////////////////////////////////////////////////////////////////////////////////
// 查询角色是否达到切支付条件请求
// class QueryPayModeReqBody = 1980
////////////////////////////////////////////////////////////////////////////////
class QueryPayModeReqBody : public Aone2MessageBody
{
public:
	QueryPayModeReqBody();

	virtual ~QueryPayModeReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_user_id;  // 用户id
	string  m_cp_role_id;  // CP角色ID（支持非数字）
	string  m_cp_group_id;  // cp分区ID
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
};

////////////////////////////////////////////////////////////////////////////////
// 查询角色是否达到切支付条件回复
// class QueryPayModeRespBody = 1981
////////////////////////////////////////////////////////////////////////////////
class QueryPayModeRespBody : public Aone2MessageBody
{
public:
	QueryPayModeRespBody();

	virtual ~QueryPayModeRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_pay_mode;  // 非零表示通过
};

////////////////////////////////////////////////////////////////////////////////
// 新实名认证信息查询请求
// class RealnameInfoReqBody = 1990
////////////////////////////////////////////////////////////////////////////////
class RealnameInfoReqBody : public Aone2MessageBody
{
public:
	RealnameInfoReqBody();

	virtual ~RealnameInfoReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_user_id;  // 用户ID
};

////////////////////////////////////////////////////////////////////////////////
// 新实名认证信息查询回复
// class RealnameInfoRespBody = 1991
////////////////////////////////////////////////////////////////////////////////
class RealnameInfoRespBody : public Aone2MessageBody
{
public:
	RealnameInfoRespBody();

	virtual ~RealnameInfoRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
	string  m_date_birth;  // 出生年月日
	string  m_encrypt_number;  // 加密后的身份证号
};

////////////////////////////////////////////////////////////////////////////////
// 新实名认证请求
// class RealnameCertificateReqBody = 1992
////////////////////////////////////////////////////////////////////////////////
class RealnameCertificateReqBody : public Aone2MessageBody
{
public:
	RealnameCertificateReqBody();

	virtual ~RealnameCertificateReqBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	DeviceInfo  m_device_info;  // 设备信息
	AppVersionInfo  m_version_info;  // 应用程序版本信息
	uint32  m_user_id;  // 用户id
	string  m_real_name;  // 真实姓名
	string  m_identity_number;  // 身份证号
};

////////////////////////////////////////////////////////////////////////////////
// 新实名认证回复
// class RealnameCertificateRespBody = 1993
////////////////////////////////////////////////////////////////////////////////
class RealnameCertificateRespBody : public Aone2MessageBody
{
public:
	RealnameCertificateRespBody();

	virtual ~RealnameCertificateRespBody();

	virtual int parse_bytes(const byte* src, uint32 len);

	virtual int to_bytes(byte* dst, uint32 maxlen);

	virtual uint32 calc_length();

public:
	uint32  m_flag;  // 标识
	string  m_real_name;  // 带隐藏的真实姓名
	string  m_encrypt_number;  // 加密后的身份证号(原:带隐藏的身份证号)
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////
typedef Aone2Request <QuickLoginReqBody, 1700> QuickLoginRequest;
typedef Aone2Response<QuickLoginRespBody, 1701> QuickLoginResponse;
typedef Aone2Request <SDKLoginReqBody, 1702> SDKLoginRequest;
typedef Aone2Response<SDKLoginRespBody, 1703> SDKLoginResponse;
typedef Aone2Request <OAuthLoginReqBody, 1704> OAuthLoginRequest;
typedef Aone2Response<OAuthLoginRespBody, 1705> OAuthLoginResponse;
typedef Aone2Request <OAuthBindReqBody, 1706> OAuthBindRequest;
typedef Aone2Response<OAuthBindRespBody, 1707> OAuthBindResponse;
typedef Aone2Request <AoneBindReqBody, 1708> AoneBindRequest;
typedef Aone2Response<AoneBindRespBody, 1709> AoneBindResponse;
typedef Aone2Request <AoneRegisterReqBody, 1710> AoneRegisterRequest;
typedef Aone2Response<AoneRegisterRespBody, 1711> AoneRegisterResponse;
typedef Aone2Request <AoneLoginReqBody, 1712> AoneLoginRequest;
typedef Aone2Response<AoneLoginRespBody, 1713> AoneLoginResponse;
typedef Aone2Request <AoneChangePasswordReqBody, 1714> AoneChangePasswordRequest;
typedef Aone2Response<AoneChangePasswordRespBody, 1715> AoneChangePasswordResponse;
typedef Aone2Request <ApplyTokenByPhoneReqBody, 1716> ApplyTokenByPhoneRequest;
typedef Aone2Response<ApplyTokenByPhoneRespBody, 1717> ApplyTokenByPhoneResponse;
typedef Aone2Request <AoneBindPhoneReqBody, 1718> AoneBindPhoneRequest;
typedef Aone2Response<AoneBindPhoneRespBody, 1719> AoneBindPhoneResponse;
typedef Aone2Request <AoneUnBindPhoneReqBody, 1720> AoneUnBindPhoneRequest;
typedef Aone2Response<AoneUnBindPhoneRespBody, 1721> AoneUnBindPhoneResponse;
typedef Aone2Request <AoneResetPasswordByPhoneReqBody, 1722> AoneResetPasswordByPhoneRequest;
typedef Aone2Response<AoneResetPasswordByPhoneRespBody, 1723> AoneResetPasswordByPhoneResponse;
typedef Aone2Request <ApplyTokenByMailReqBody, 1724> ApplyTokenByMailRequest;
typedef Aone2Response<ApplyTokenByMailRespBody, 1725> ApplyTokenByMailResponse;
typedef Aone2Request <AoneBindMailReqBody, 1726> AoneBindMailRequest;
typedef Aone2Response<AoneBindMailRespBody, 1727> AoneBindMailResponse;
typedef Aone2Request <AoneUnBindMailReqBody, 1728> AoneUnBindMailRequest;
typedef Aone2Response<AoneUnBindMailRespBody, 1729> AoneUnBindMailResponse;
typedef Aone2Request <AoneResetPasswordByMailReqBody, 1730> AoneResetPasswordByMailRequest;
typedef Aone2Response<AoneResetPasswordByMailRespBody, 1731> AoneResetPasswordByMailResponse;
typedef Aone2Request <AoneAccountInfoReqBody, 1732> AoneAccountInfoRequest;
typedef Aone2Response<AoneAccountInfoRespBody, 1733> AoneAccountInfoResponse;
typedef Aone2Request <OAuthInfoReqBody, 1734> OAuthInfoRequest;
typedef Aone2Response<OAuthInfoRespBody, 1735> OAuthInfoResponse;
typedef Aone2Request <QuickRegisterReqBody, 1736> QuickRegisterRequest;
typedef Aone2Response<QuickRegisterRespBody, 1737> QuickRegisterResponse;
typedef Aone2Request <AoneAccountCertificateReqBody, 1738> AoneAccountCertificateRequest;
typedef Aone2Response<AoneAccountCertificateRespBody, 1739> AoneAccountCertificateResponse;
typedef Aone2Request <AoneSdkCheckVerReqBody, 1740> AoneSdkCheckVerRequest;
typedef Aone2Response<AoneSdkCheckVerRespBody, 1741> AoneSdkCheckVerResponse;
typedef Aone2Request <AccountIdentityInfoReqBody, 1742> AccountIdentityInfoRequest;
typedef Aone2Response<AccountIdentityInfoRespBody, 1743> AccountIdentityInfoResponse;
typedef Aone2Request <AccountCertificateReqBody, 1744> AccountCertificateRequest;
typedef Aone2Response<AccountCertificateRespBody, 1745> AccountCertificateResponse;
typedef Aone2Request <AoneBindOtherAccountReqBody, 1746> AoneBindOtherAccountRequest;
typedef Aone2Response<AoneBindOtherAccountRespBody, 1747> AoneBindOtherAccountResponse;
typedef Aone2Request <AoneUnbindOtherAccountReqBody, 1748> AoneUnbindOtherAccountRequest;
typedef Aone2Response<AoneUnbindOtherAccountRespBody, 1749> AoneUnbindOtherAccountResponse;
typedef Aone2Request <AoneQueryBindOtherAccountReqBody, 1750> AoneQueryBindOtherAccountRequest;
typedef Aone2Response<AoneQueryBindOtherAccountRespBody, 1751> AoneQueryBindOtherAccountResponse;
typedef Aone2Request <FBInstantLoginReqBody, 1764> FBInstantLoginRequest;
typedef Aone2Response<FBInstantLoginRespBody, 1765> FBInstantLoginResponse;
typedef Aone2Request <QueryChannelConfigReqBody, 1790> QueryChannelConfigRequest;
typedef Aone2Response<QueryChannelConfigRespBody, 1791> QueryChannelConfigResponse;
typedef Aone2Request <RecordSDKDownloadExceptionReqBody, 1792> RecordSDKDownloadExceptionRequest;
typedef Aone2Response<RecordSDKDownloadExceptionRespBody, 1793> RecordSDKDownloadExceptionResponse;
typedef Aone2Request <RecordGameDownloadExceptionReqBody, 1794> RecordGameDownloadExceptionRequest;
typedef Aone2Response<RecordGameDownloadExceptionRespBody, 1795> RecordGameDownloadExceptionResponse;
typedef Aone2Request <recordSDKPayExceptionReqBody, 1796> recordSDKPayExceptionRequest;
typedef Aone2Response<recordSDKPayExceptionRespBody, 1797> recordSDKPayExceptionResponse;
typedef Aone2Request <QueryIsEnableLocalPayReqBody, 1798> QueryIsEnableLocalPayRequest;
typedef Aone2Response<QueryIsEnableLocalPayRespBody, 1799> QueryIsEnableLocalPayResponse;
typedef Aone2Request <UserVerifyReqBody, 1800> UserVerifyRequest;
typedef Aone2Response<UserVerifyRespBody, 1801> UserVerifyResponse;
typedef Aone2Request <PayReqBody, 1850> PayRequest;
typedef Aone2Response<PayRespBody, 1851> PayResponse;
typedef Aone2Request <QueryExceptionPayOrdersReqBody, 1854> QueryExceptionPayOrdersRequest;
typedef Aone2Response<QueryExceptionPayOrdersRespBody, 1855> QueryExceptionPayOrdersResponse;
typedef Aone2Request <CommitReceiptReqBody, 1856> CommitReceiptRequest;
typedef Aone2Response<CommitReceiptRespBody, 1857> CommitReceiptResponse;
typedef Aone2Request <QueryOrderStatusReqBody, 1858> QueryOrderStatusRequest;
typedef Aone2Response<QueryOrderStatusRespBody, 1859> QueryOrderStatusResponse;
typedef Aone2Request <QueryPayNoStatusReqBody, 1860> QueryPayNoStatusRequest;
typedef Aone2Response<QueryPayNoStatusRespBody, 1861> QueryPayNoStatusResponse;
typedef Aone2Request <SendMailReqBody, 1900> SendMailRequest;
typedef Aone2Response<SendMailRespBody, 1901> SendMailResponse;
typedef Aone2Request <SendSMSReqBody, 1902> SendSMSRequest;
typedef Aone2Response<SendSMSRespBody, 1903> SendSMSResponse;
typedef Aone2Request <PushMessageReqBody, 1904> PushMessageRequest;
typedef Aone2Response<PushMessageRespBody, 1905> PushMessageResponse;
typedef Aone2Request <PushTagMessageReqBody, 1906> PushTagMessageRequest;
typedef Aone2Response<PushTagMessageRespBody, 1907> PushTagMessageResponse;
typedef Aone2Request <PushBroadcastMessageReqBody, 1908> PushBroadcastMessageRequest;
typedef Aone2Response<PushBroadcastMessageRespBody, 1909> PushBroadcastMessageResponse;
typedef Aone2Request <QueryProductInfoReqBody, 1920> QueryProductInfoRequest;
typedef Aone2Response<QueryProductInfoRespBody, 1921> QueryProductInfoResponse;
typedef Aone2Request <QueryWebsiteProductListReqBody, 1922> QueryWebsiteProductListRequest;
typedef Aone2Response<QueryWebsiteProductListRespBody, 1923> QueryWebsiteProductListResponse;
typedef Aone2Request <QueryAppChannelsReqBody, 1950> QueryAppChannelsRequest;
typedef Aone2Response<QueryAppChannelsRespBody, 1951> QueryAppChannelsResponse;
typedef Aone2Request <QueryAppLangsReqBody, 1952> QueryAppLangsRequest;
typedef Aone2Response<QueryAppLangsRespBody, 1953> QueryAppLangsResponse;
typedef Aone2Request <QueryAppProductsReqBody, 1954> QueryAppProductsRequest;
typedef Aone2Response<QueryAppProductsRespBody, 1955> QueryAppProductsResponse;
typedef Aone2Request <RecordRoleLoginReqBody, 1960> RecordRoleLoginRequest;
typedef Aone2Response<RecordRoleLoginRespBody, 1961> RecordRoleLoginResponse;
typedef Aone2Request <QueryShareInfoReqBody, 1962> QueryShareInfoRequest;
typedef Aone2Response<QueryShareInfoRespBody, 1963> QueryShareInfoResponse;
typedef Aone2Request <PublishShareInfoReqBody, 1964> PublishShareInfoRequest;
typedef Aone2Response<PublishShareInfoRespBody, 1965> PublishShareInfoResponse;
typedef Aone2Request <QueryAoneGroupIdReqBody, 1966> QueryAoneGroupIdRequest;
typedef Aone2Response<QueryAoneGroupIdRespBody, 1967> QueryAoneGroupIdResponse;
typedef Aone2Request <AoneCEBSignReqBody, 1968> AoneCEBSignRequest;
typedef Aone2Response<AoneCEBSignRespBody, 1969> AoneCEBSignResponse;
typedef Aone2Request <QueryUserPhoneBindReqBody, 1970> QueryUserPhoneBindRequest;
typedef Aone2Response<QueryUserPhoneBindRespBody, 1971> QueryUserPhoneBindResponse;
typedef Aone2Request <ApplyCodeByPhoneReqBody, 1972> ApplyCodeByPhoneRequest;
typedef Aone2Response<ApplyCodeByPhoneRespBody, 1973> ApplyCodeByPhoneResponse;
typedef Aone2Request <VerifyCodeReqBody, 1974> VerifyCodeRequest;
typedef Aone2Response<VerifyCodeRespBody, 1975> VerifyCodeResponse;
typedef Aone2Request <RecordDevicePointReqBody, 1976> RecordDevicePointRequest;
typedef Aone2Response<RecordDevicePointRespBody, 1977> RecordDevicePointResponse;
typedef Aone2Request <RecordRolePointReqBody, 1978> RecordRolePointRequest;
typedef Aone2Response<RecordRolePointRespBody, 1979> RecordRolePointResponse;
typedef Aone2Request <QueryPayModeReqBody, 1980> QueryPayModeRequest;
typedef Aone2Response<QueryPayModeRespBody, 1981> QueryPayModeResponse;
typedef Aone2Request <RealnameInfoReqBody, 1990> RealnameInfoRequest;
typedef Aone2Response<RealnameInfoRespBody, 1991> RealnameInfoResponse;
typedef Aone2Request <RealnameCertificateReqBody, 1992> RealnameCertificateRequest;
typedef Aone2Response<RealnameCertificateRespBody, 1993> RealnameCertificateResponse;


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_APISERVER_H_
