// File: msg_xx_error.h
// Auth: generated by auto tool 'lazybone'
// Desc: message define
// 本文档用于定义全局错误码(协议号与错误码使用相同的区间)
// 错误码/协议号分配：(客户端自身的错误码均使用负数表示,以区别)
// 0: 表示成功
//   1  -- 99:  保留(与系统错误码兼容)
// 100  -- 199: 管理后台服务(公共)(W)
// 200  -- 999: 保留
// 1000 -- 1499:  账号服务(A)
// 1500 -- 1699:  入口服务(E)
// 1700 -- 1999:  API服务(I)
// 2000 -- 2499:  支付服务(P)
// 2500 -- 2999:  角色服务(R)
// 3000 -- 3199:  (API)日志记录服务(L)
// 3200 -- 3499:  (角色)日志记录服务(L)
// 3500 -- 3999:  (游戏)日志记录服务(L)
// 4000 -- 4899:  中心服务(C)
// 4900 -- 4999:  公共协议(X)
// 5000 -- 5399:  排名服务(N)
// 5400 -- 5499:  邮件发送服务(M)
// 5500 -- 5899:  推送服务(U)
// 5900 -- 5999:  短信发送服务(S)
// 6000 -- 6099:  适配服务(D)
// 6100 -- 6199:  管理后台公共部分(W)
// 6200 -- 6999:  管理后台扩展部分(W)
// 7000 -- 7099:  激活码服务部分
// 8000 -- 9999:  保留给公共模块
// 10000 -- 19999:  游戏服务(G)


#ifndef _MESSAGE_MSG_XX_ERROR_H_
#define _MESSAGE_MSG_XX_ERROR_H_

#include "xcore_define.h"
#include "aone2_message_body.h"
#include "aone2_define.h"
#include "aone2_message.h"

namespace message {

// 全局错误码定义
// ErrorCode
class EC
{
public:
	enum _tagEC
	{
		SUCCESS = 0,  // 成功
		AGENT_ERROR = 100,  // 代理类通用错误
		AGENT_INVALID_ARG = 101,  // 参数错误
		AGENT_AUTH_FAILED = 102,  // 后台管理平台鉴权失败
		AGENT_UNMATCHED_TYPE = 103,  // 代理类型不匹配
		AGENT_INVALID_ROLEID_OR_SESSION = 104,  // roleId或sessionId不匹配
		AGENT_NOSUPPORT_RESTART = 105,  // 服务模块不支持重启
		AGENT_FILE_OPERAT_FORBID = 106,  // 被禁止的文件操作
		AGENT_CANNOT_FIND_FILE = 107,  // 没有找到文件
		AGENT_FILE_TOO_BIG = 108,  // 文件太大(超过10KB)
		AGENT_CAN_NOT_FIND_ROLE = 109,  // 不能查找到该角色
		AGENT_CAN_NOT_FIND_UNION = 110,  // 不能查找到联盟
		AGENT_ITEM_EXIST = 111,  // 物品不存在
		AGENT_ITEM_COUNT_TO_BIG = 112,  // 物品数量太大
		AGENT_FULL = 113,  // 背包，仓库，灵魂背包已满
		AGENT_CANNOT_FIND_UNION = 114,  // 查不到公会
		AGENT_CAN_NOT_ZERO = 115,  // 添加的物品个数不能为0除装备外
		AGENET_CAN_NOT_EMPTY = 116,  // 增加或删除的敏感字不能为空
		AGENT_ERROR_LIMIT = 199,  // 代理类错误码最大值
		XX_SB = 250,  // 外挂返回
		XA_ERROR = 1000,  // 账号服务通用错误码
		XA_INVALID_ARG = 1001,  // 请求参数错误
		XA_NOT_SUPPORT = 1002,  // 功能暂未支持
		XA_VERIFY_KEY = 1003,  // 无效的验证码
		XA_UID_DISABLE = 1004,  // 账号被禁用
		XA_NOT_FOUND_UID = 1005,  // 未找到UID
		XA_NOT_FOUND_ACCOUNT = 1006,  // 未找到账号
		XA_ACCOUNT_EXIST = 1007,  // 账号已存在
		XA_INVALID_TOKEN = 1008,  // 无效的账号操作令牌
		XA_INVALID_PASSWD = 1009,  // 错误的密码(邮箱账号登陆时)
		XA_DUPLICATE_BIND = 1010,  // 重复绑定
		XA_DATABASE_ERROR = 1011,  // 数据库错误
		XA_SENDMAIL_FAILED = 1012,  // 发送邮件错误
		XA_OPERATE_TIMEOUT = 1013,  // 操作超时
		XA_OPEN_API_ERROR = 1014,  // 开放平台api错误
		XA_NOT_FOUND_DEVICEID = 1015,  // 未找到设备ID
		XA_NOT_FOUND_SINA_ACCOUNT = 1017,  // 未找到新浪账号
		XA_NOT_FOUND_TENCENT_ACCOUNT = 1018,  // 未找到腾迅账号
		XA_NOT_FOUND_FACEBOOK_ACCOUNT = 1019,  // 未找到Facebook账号
		XA_NOT_FOUND_AONE_ACCOUNT_BY_UID = 1020,  // 通过用户ID未找到Aone账号
		XA_NOT_FOUND_AONE_ACCOUNT_BY_PHONE = 1021,  // 通过手机号未找到Aone账号
		XA_NOT_FOUND_AONE_ACCOUNT_BY_MAIL = 1022,  // 通过邮箱未找到Aone账号
		XA_NOT_FOUND_AONE_ACCOUNT_BY_WEIXIN = 1023,  // 通过微信号未找到Aone账号
		XA_NOT_FOUND_CHANNEL_NAME = 1024,  // 账号类型未找到
		XA_OTHER_DEVICE_LOGINED = 1025,  // 该账号在其他设备登录
		XA_PHONE_ALREADY_BIND = 1201,  // 手机号已绑定
		XA_MAIL_ALREADY_BIND = 1202,  // 邮箱已绑定
		XA_INVALID_SESSION = 1297,  // 会话ID无效
		XA_INVALID_TICKET = 1298,  // 其他服务向账号服务验证ticket无效
		XA_ERROR_LIMIT = 1299,  // 账号服务最大错误码
		XE_ERROR = 1500,  // 入口服务通用错误码
		XE_TIMEOUT = 1501,  // 超时
		XE_INVALID_ARG = 1502,  // 请求参数错误
		XE_NOT_SUPPORT = 1503,  // 功能暂未支持
		XE_INVALID_VERIFY_KEY = 1504,  // 无效的验证码
		XE_INVALID_GAME_CODE = 1505,  // 无效的游戏代号
		XE_INVALID_CLIENT_VERSION = 1506,  // 无效的客户端版本
		XE_FORBID = 1507,  // 被禁止访问，已加入黑名单
		XE_CREATEROLE_FORBID = 1508,  // 分区维护或者隐藏不允许创建角色
		XE_ERROR_LIMIT = 1699,  // 入口服务最大错误码
		XI_ERROR = 1700,  // API服务通用错误码
		XI_TIMEOUT = 1701,  // 超时
		XI_INVALID_ARG = 1702,  // 请求参数错误
		XI_INVALID_STATUS = 1703,  // 异常的状态
		XI_INVALID_VERIFY_KEY = 1704,  // 无效的验证码
		XI_DB_ERROR = 1705,  // 数据库操作失败
		XI_INVALID_USER_TOKEN = 1706,  // 用户验证码无效
		XI_NOT_FOUND_USER_TOKEN = 1707,  // 用户验证码已过期
		XI_INVALID_PHONE = 1708,  // 无效的手机号
		XI_INVALID_MAIL = 1709,  // 无效的邮箱
		XI_INVALID_AONE_ACCOUNT = 1710,  // 无效的Aone账号
		XI_INVALID_PASSWORD = 1711,  // 无效的密码
		XI_NOT_FOUND_APP = 1712,  // 未找到指定的APP
		XI_INVALID_SIGN = 1713,  // 验签失败
		XI_INVALID_JSON = 1714,  // 无效的json
		XI_INVALID_JSON_STRUCT = 1715,  // 无效的json结构
		XI_NOT_FOUND_CHANNEL_CONFIG = 1716,  // 未找到渠道配置
		XI_NOT_FOUND_CHANNEL_PRODUCTS = 1717,  // 未找到渠道商品列表
		XI_NOT_VALID_ENTRY_SERVER = 1718,  // 未找到有效的入口服务
		XI_INVALID_AONE_ACCOUNT_LEN = 1719,  // 无效的Aone账号长度非法
		XI_INVALID_AONE_ACCOUNT_CHA = 1720,  // 无效的Aone账号违禁字符
		XI_UNSUPPORT_CHANNEL = 1721,  // 未支持的渠道
		XI_LIMITAPICALL_CHANGEPWD = 1722,  // 修改密码api调用限制
		XI_INVALID_REAL_NAME = 1723,  // 无效的真实姓名
		XI_INVALID_IDENTITY_NUMBER = 1724,  // 无效的身份证号
		XI_FORBID_LOGIN = 1725,  // 已被禁止登陆
		XI_IP_NOT_MATCHE = 1726,  // 请求的IP与配置的IP不一致
		XI_COIN_NOT_ENOUGH = 1727,  // 猎人币不足
		XI_ID_CARD_AUTH_FAIL = 1728,  // 实名认证失败
		XI_LIMITAPICALL_SMSSEND = 1729,  // 短信发送api调用限制
		XI_PHONE_ALREADY_BIND = 1730,  // 手机号已绑定
		XI_ERROR_LIMIT = 1999,  // API服务最大错误码
		XP_ERROR = 2000,  // 支付服务通用错误码
		XP_OPERATE_TIMEOUT = 2001,  // 操作超时
		XP_NOT_AUTH = 2002,  // 未验证身份
		XP_GENERATE_PAYNO = 2003,  // 生成订单失败
		XP_SERVERID_NOT_MATCH = 2004,  // 服务ID不匹配
		XP_DB_ERROR = 2005,  // 数据库操作失败
		XP_INVALID_ARG = 2006,  // 请求参数错误
		XP_UNSUPPORT_PAYCHANNEL = 2007,  // 未支持的支付渠道
		XP_EMPTY_PRODUCTS = 2008,  // 支付商品列表为空
		XP_THIRDPARTY_COMM_ERR = 2009,  // 与第三方通信失败
		XP_THIRDPARTY_INVALID_PARAM = 2010,  // 与第三方通信失败
		XP_DEVICE_LIMITED = 2011,  // 支付设备受限
		XP_PAY_FAILED = 2012,  // 支付失败
		XP_PAY_UNFINISHED = 2013,  // 支付未完成
		XP_ERROR_LIMIT = 2499,  // 支付服务最大错误码
		XR_ERROR = 2500,  // 角色服务通用错误码
		XR_OPERATE_TIMEOUT = 2501,  // 操作超时
		XR_INVALID_ARG = 2502,  // 请求参数错误
		XR_SERVER_ALREADY_CONNECTED = 2503,  // 同分区ID已有连接建立，不能建立新连接
		XR_REDIS_ERROR = 2504,  // REDIS操作失败
		XR_MYSQL_ERROR = 2505,  // 数据库操作失败
		XR_AUTH_INVALID_USERTOKEN = 2506,  // 无效usertoken
		XR_AUTH_INVALID_TICKET = 2507,  // 无效ticket
		XR_CHAR_CREATE_NAME_IN_USE = 2508,  // 角色名已存在
		XR_CHAR_CREATE_ACCOUNT_LIMIT = 2509,  // 帐号下角色数超限
		XR_CHAR_CREATE_SERVER_LIMIT = 2510,  // 分区下角色数超限
		XR_CHAR_CREATE_DISABLED = 2511,  // 分区已不允许创建角色
		XR_CHAR_LOGIN_NO_WORLD = 2512,  // 登录分区不存在
		XR_CHAR_LOGIN_DISABLED = 2513,  // 禁止登入该分区
		XR_CHAR_NAME_PROFANE = 2514,  // 违禁词
		XR_CHAR_COIN_NOT_ENOUGH = 2515,  // 代币数不足
		XR_DB_ERROR = 2516,  // 数据库错误
		XR_PAY_SIGN_UNMATCH = 2517,  // 签名不匹配
		XR_NAME_INVALID = 2518,  // 角色名字非法
		XR_NOT_FOUND_ROLE = 2519,  // 未找到找定的角色
		XR_ERROR_LIMIT = 2999,  // 角色服务最大错误码
		XL_ERROR = 3000,  // 公共日志记录服务通用错误码
		XL_ALREADY_CONNECTED = 3001,  // 同服务ID已有连接建立，不能建立新连接
		XL_ERROR_LIMIT = 3499,  // 公共日志记录服务最大错误码
		XL_GAME_ERROR = 3500,  // 游戏日志记录服务通用错误码
		XL_GAME_ERROR_LIMIT = 3999,  // 游戏日志记录服务最大错误码
		XC_ERROR = 4000,  // 中心服务通用错误码
		XC_INVALID_ARG = 4001,  // 请求参数错误
		XC_NOT_SUPPORT = 4002,  // 功能暂未支持
		XC_DB_ERROR = 4003,  // 数据库错误
		XC_INVALID_SESSION = 4004,  // 会话ID无效
		XC_SERVER_ID_NOT_EXIST = 4005,  //服务不存在
		XC_REPEAT_REGISTER = 4006,  // 服务连接重复注册
		XC_INVALID_PASSWORD = 4007,  // 错误的密码
		XC_ALREADY_REGISTER = 4008,  // 服务ID已注册
		XC_INVALID_TICKET = 4009,  // 无效的ticket
		XC_TRANSFER_TIMEOUT = 4010,  // 中转消息操时
		XC_TRANSFER_ERROR = 4011,  // 中转消息失败
		XC_CODE_NOT_EXIST = 4012,  // 激活码不存在
		XC_CODE_ALREADY_USED = 4013,  // 激活码已使用
		XC_CODE_COUNT_LIMIT = 4014,  // 同批次激活码使用个数受限
		XC_CODE_PLATFORM_LIMIT = 4015,  // 激活码使用渠道受限
		XC_CODE_GROUP_LIMIT = 4016,  // 激活码使用分区受限
		XC_CODE_TIME_LIMIT = 4017,  // 激活码在当前时间不能使用
		XC_ERROR_LIMIT = 4799,  // 中心服务最大错误码
		XK_ERROR = 4800,  // 激活码服务通用错误码
		XK_ERROR_LIMIT = 4899,  // 激活码服务最大错误码
		XN_ERROR = 5000,  // 排名服务通用错误码
		XN_TIMEOUT = 5001,  // 超时
		XN_INVALID_ARG = 5002,  // 请求参数错误
		XN_NOT_SUPPORT = 5003,  // 功能暂未支持
		XN_SAVE_FAIL = 5004,  // 存储错误
		XN_ERROR_LIMIT = 5499,  // 排名服务最大错误码
		XU_ERROR = 5500,  // 排送服务通用错误码
		XU_ERROR_LIMIT = 5899,  // 推送服务最大错误码
		XS_ERROR = 5900,  // 短信服务通用错误码
		XS_ERROR_LIMIT = 5999,  // 短信服务最大错误码
		XD_ERROR = 6000,  //适配服务器通用错误
		XD_NO_AUTH = 6001,  //未找到对应的服务器
		XD_SERVER_NOT_FOUND = 6002,  //未找到对应的服务器
		XD_JSON_CONVERT_FAILED = 6003,  //转换JSON错误
		XD_REQUEST_PATH_NOT_FOUND = 6004,  //未找到协议对应的回调路径
		XD_SEND_TO_SERVER_FAILED = 6005,  //向服务器发送报文失败
		XD_ERROR_CONFIG_ITEM_ERROR = 6006,  //适配服在中心的模板配置项错误
		XD_ERROR_OFFLINE = 6007,  //游戏服心跳超时已经掉线,需要重新注册
		XD_REGIST_CENTER_SERVER_ERROR = 6008,  //向中心注册失败
		XD_REGIST_ROLE_SERVER_ERROR = 6009,  //向角色服注册失败
		XD_REGIST_IP_NOT_MATCHE = 6010,  //向中心注册时游戏服配置的IP与消息传送的IP不一致
		XD_REGIST_PORT_NOT_MATCHE = 6011,  //向中心注册时游戏服配置的http_port与消息传送的http_port不一致
		XD_HEATBEAT_FAILED = 6012,  //心跳失败
		XD_TIME_OUT = 6013,  //服务器消息处理超时
		XD_ERROR_LIMIT = 6099,  //适配服务器最大错误
		XG_ERROR = 10000,  // 游戏服务通用错误码
		XG_TIMEOUT = 10001,  // 超时
		XG_INVALID_ARG = 10002,  // 请求参数错误
		XG_NOT_SUPPORT = 10003,  // 功能暂未支持
		XG_INVALID_GAME_CODE = 10004,  // 无效的游戏代号
		XG_INVALID_ROLEID_OR_SESSION = 10005,  // 无效的角色ID或会话ID
		XG_INVALID_LOGIN = 10006,  // 本次登录失效
		XG_NAME_WRONG = 10007,  // 非法名字
		XG_NAME_TOO_LONG = 10008,  // 名字太长
		XG_NAME_REPEATED = 10009,  // 名字重复
		XG_ERROR_LIMIT = 19999,  // 游戏服务最大错误码
	} m_value;

	EC() : m_value((_tagEC)0) {}
	EC(int i) : m_value((_tagEC)i) {}
	EC& operator=(int i) { m_value = (_tagEC)i; return *this; }
	operator int() { return m_value; }
	operator int() const { return m_value; }
};


////////////////////////////////////////////////////////////////////////////////
// message define
////////////////////////////////////////////////////////////////////////////////


}//namespace message

using namespace message;

#endif//_MESSAGE_MSG_XX_ERROR_H_
