// File: msg_xx_idcard.cpp
// Auth: generated by auto tool 'lazybone'
// Desc: message define


#include "msg_xx_idcard.h"
#include "aone2_helper.h"

namespace message {

///////////////////////////////////////////////////////////////////////////////
// class IdcardLoginReqBody
///////////////////////////////////////////////////////////////////////////////
IdcardLoginReqBody::IdcardLoginReqBody()
{
	m_user_id = 0;
}

IdcardLoginReqBody::~IdcardLoginReqBody()
{
	// empty
}

int IdcardLoginReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardLoginReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardLoginReqBody::calc_length()
{
	uint32 length = 0;

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class IdcardLoginRespBody
///////////////////////////////////////////////////////////////////////////////
IdcardLoginRespBody::IdcardLoginRespBody()
{
	m_token = 0;
	m_flag = 0;
	m_online_time = 0;
	m_pay_amount = 0.0f;
}

IdcardLoginRespBody::~IdcardLoginRespBody()
{
	// empty
}

int IdcardLoginRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_token)) return -1;

	// m_flag
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_flag)) return -1;

	// m_date_birth
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_date_birth)) return -1;

	// m_online_time
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_online_time)) return -1;

	// m_pay_amount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_double(m_pay_amount)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardLoginRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_token
	if (!coder.set_uint32(m_token)) return -1;

	// m_flag
	if (!coder.set_uint32(m_flag)) return -1;

	// m_date_birth
	if (!coder.set_string(m_date_birth)) return -1;

	// m_online_time
	if (!coder.set_uint32(m_online_time)) return -1;

	// m_pay_amount
	if (!coder.set_double(m_pay_amount)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardLoginRespBody::calc_length()
{
	uint32 length = 0;

	// m_token
	length += Aone2Coder::size_uint32(m_token);

	// m_flag
	length += Aone2Coder::size_uint32(m_flag);

	// m_date_birth
	length += Aone2Coder::size_string(m_date_birth);

	// m_online_time
	length += Aone2Coder::size_uint32(m_online_time);

	// m_pay_amount
	length += Aone2Coder::size_double(m_pay_amount);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class IdcardLogoutReqBody
///////////////////////////////////////////////////////////////////////////////
IdcardLogoutReqBody::IdcardLogoutReqBody()
{
	m_user_id = 0;
}

IdcardLogoutReqBody::~IdcardLogoutReqBody()
{
	// empty
}

int IdcardLogoutReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardLogoutReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardLogoutReqBody::calc_length()
{
	uint32 length = 0;

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class IdcardHeartReqBody
///////////////////////////////////////////////////////////////////////////////
IdcardHeartReqBody::IdcardHeartReqBody()
{
	m_user_id = 0;
	m_token = 0;
}

IdcardHeartReqBody::~IdcardHeartReqBody()
{
	// empty
}

int IdcardHeartReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_token
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_token)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardHeartReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_token
	if (!coder.set_uint32(m_token)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardHeartReqBody::calc_length()
{
	uint32 length = 0;

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_token
	length += Aone2Coder::size_uint32(m_token);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class IdcardHeartRespBody
///////////////////////////////////////////////////////////////////////////////
IdcardHeartRespBody::IdcardHeartRespBody()
{
	m_flag = 0;
	m_online_time = 0;
	m_pay_amount = 0.0f;
}

IdcardHeartRespBody::~IdcardHeartRespBody()
{
	// empty
}

int IdcardHeartRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_flag
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_flag)) return -1;

	// m_date_birth
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_date_birth)) return -1;

	// m_online_time
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_online_time)) return -1;

	// m_pay_amount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_double(m_pay_amount)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardHeartRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_flag
	if (!coder.set_uint32(m_flag)) return -1;

	// m_date_birth
	if (!coder.set_string(m_date_birth)) return -1;

	// m_online_time
	if (!coder.set_uint32(m_online_time)) return -1;

	// m_pay_amount
	if (!coder.set_double(m_pay_amount)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardHeartRespBody::calc_length()
{
	uint32 length = 0;

	// m_flag
	length += Aone2Coder::size_uint32(m_flag);

	// m_date_birth
	length += Aone2Coder::size_string(m_date_birth);

	// m_online_time
	length += Aone2Coder::size_uint32(m_online_time);

	// m_pay_amount
	length += Aone2Coder::size_double(m_pay_amount);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class IdcardCertificateReqBody
///////////////////////////////////////////////////////////////////////////////
IdcardCertificateReqBody::IdcardCertificateReqBody()
{
	m_user_id = 0;
}

IdcardCertificateReqBody::~IdcardCertificateReqBody()
{
	// empty
}

int IdcardCertificateReqBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_device_info
	if (decoder.remain() == 0) return msglen;
	int device_info_ret = m_device_info.parse_bytes(decoder.position(), decoder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	if (!decoder.set_pos(decoder.position() + device_info_ret)) return -1;

	// m_version_info
	if (decoder.remain() == 0) return msglen;
	int version_info_ret = m_version_info.parse_bytes(decoder.position(), decoder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	if (!decoder.set_pos(decoder.position() + version_info_ret)) return -1;

	// m_user_id
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_user_id)) return -1;

	// m_real_name
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_real_name)) return -1;

	// m_identity_number
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_identity_number)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardCertificateReqBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_device_info
	int device_info_ret = m_device_info.to_bytes(coder.position(), coder.remain());
	if (device_info_ret <= 0) return device_info_ret;
	coder.set_pos(coder.position() + device_info_ret);

	// m_version_info
	int version_info_ret = m_version_info.to_bytes(coder.position(), coder.remain());
	if (version_info_ret <= 0) return version_info_ret;
	coder.set_pos(coder.position() + version_info_ret);

	// m_user_id
	if (!coder.set_uint32(m_user_id)) return -1;

	// m_real_name
	if (!coder.set_string(m_real_name)) return -1;

	// m_identity_number
	if (!coder.set_string(m_identity_number)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardCertificateReqBody::calc_length()
{
	uint32 length = 0;

	// m_device_info
	length += m_device_info.calc_length();

	// m_version_info
	length += m_version_info.calc_length();

	// m_user_id
	length += Aone2Coder::size_uint32(m_user_id);

	// m_real_name
	length += Aone2Coder::size_string(m_real_name);

	// m_identity_number
	length += Aone2Coder::size_string(m_identity_number);

	return length + sizeof(uint32);
}

///////////////////////////////////////////////////////////////////////////////
// class IdcardCertificateRespBody
///////////////////////////////////////////////////////////////////////////////
IdcardCertificateRespBody::IdcardCertificateRespBody()
{
	m_flag = 0;
	m_online_time = 0;
	m_pay_amount = 0.0f;
}

IdcardCertificateRespBody::~IdcardCertificateRespBody()
{
	// empty
}

int IdcardCertificateRespBody::parse_bytes(const byte* src, uint32 len)
{
	if (src == NULL) return -1;
	if (len < sizeof(uint32)) return -1;
	uint32 msglen = *(const uint32*)src;
	if (msglen < sizeof(uint32) || msglen > len) return -1;
	Aone2Decoder decoder(src + sizeof(uint32), msglen - sizeof(uint32));

	// m_flag
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_flag)) return -1;

	// m_date_birth
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_string(m_date_birth)) return -1;

	// m_online_time
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_uint32(m_online_time)) return -1;

	// m_pay_amount
	if (decoder.remain() == 0) return msglen;
	if (!decoder.get_double(m_pay_amount)) return -1;

	//m_msgLen = msglen;
	return msglen;
}

int IdcardCertificateRespBody::to_bytes(byte* dst, uint32 maxlen)
{
	if (dst == NULL) return -1;
	if (maxlen < sizeof(uint32)) return -1;
	Aone2Coder coder(dst + sizeof(uint32), maxlen - sizeof(uint32));

	// m_flag
	if (!coder.set_uint32(m_flag)) return -1;

	// m_date_birth
	if (!coder.set_string(m_date_birth)) return -1;

	// m_online_time
	if (!coder.set_uint32(m_online_time)) return -1;

	// m_pay_amount
	if (!coder.set_double(m_pay_amount)) return -1;

	*(uint32*)dst = (coder.position() - dst);
	//m_msgLen = *(uint32*)dst;
	return *(uint32*)dst;
}

uint32 IdcardCertificateRespBody::calc_length()
{
	uint32 length = 0;

	// m_flag
	length += Aone2Coder::size_uint32(m_flag);

	// m_date_birth
	length += Aone2Coder::size_string(m_date_birth);

	// m_online_time
	length += Aone2Coder::size_uint32(m_online_time);

	// m_pay_amount
	length += Aone2Coder::size_double(m_pay_amount);

	return length + sizeof(uint32);
}


////////////////////////////////////////////////////////////////////////////////
// message register
////////////////////////////////////////////////////////////////////////////////
static XMessageCreatorRegister<Aone2BaseMessage, IdcardLoginRequest, uint32> regIdcardLoginRequest(IdcardLoginRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardLoginResponse, uint32> regIdcardLoginResponse(IdcardLoginResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardLogoutRequest, uint32> regIdcardLogoutRequest(IdcardLogoutRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardLogoutResponse, uint32> regIdcardLogoutResponse(IdcardLogoutResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardHeartRequest, uint32> regIdcardHeartRequest(IdcardHeartRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardHeartResponse, uint32> regIdcardHeartResponse(IdcardHeartResponse::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardCertificateRequest, uint32> regIdcardCertificateRequest(IdcardCertificateRequest::NUMBER);
static XMessageCreatorRegister<Aone2BaseMessage, IdcardCertificateResponse, uint32> regIdcardCertificateResponse(IdcardCertificateResponse::NUMBER);


}//namespace message
